{{- if and .Values.certManager.enabled .Values.proxy.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.issuerName }}
  labels:
    {{- include "laboratory.labels" . | nindent 4 }}
spec:
  {{- if .Values.certManager.selfSigned }}
  selfSigned: { }
  {{- else }}
  acme:
    server: {{ .Values.certManager.acme.server | default (ternary .Values.certManager.acme.presets.staging .Values.certManager.acme.presets.production .Values.certManager.staging) | quote }}
    email: {{ .Values.certManager.email | quote }}
    privateKeySecretRef:
      name: {{ .Values.certManager.issuerName }}-account-key
    solvers:
      {{- with .Values.certManager.dns01.cloudflare.apiTokenSecretRef }}
      {{- if .name }}
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: {{ .name | quote }}
              key: {{ .key | quote }}
      {{- end }}
      {{- end }}
      {{- if not .Values.certManager.dns01.cloudflare.apiTokenSecretRef.name }}
      - http01:
          ingress:
            class: ""
          {{- if or .Values.proxy.wg.nodeSelector .Values.proxy.wg.tolerations }}
            podTemplate:
              spec:
              {{- with .Values.proxy.wg.nodeSelector }}
                nodeSelector:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.proxy.wg.tolerations }}
                tolerations:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
