{{- if and .Values.certManager.enabled .Values.proxy.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.issuerName }}
  labels:
    {{- include "laboratory.labels" . | nindent 4 }}
spec:
  {{- if .Values.certManager.selfSigned }}
  selfSigned: {}
  {{- else }}
  acme:
    {{- if .Values.certManager.staging }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- else }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- end }}
    email: {{ .Values.certManager.email | quote }}
    privateKeySecretRef:
      name: {{ .Values.certManager.issuerName }}-account-key
    solvers:
    - http01:
        ingress:
          class: ""
          {{- if or .Values.proxy.wg.nodeSelector .Values.proxy.wg.tolerations }}
          podTemplate:
            spec:
              {{- with .Values.proxy.wg.nodeSelector }}
              nodeSelector:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.proxy.wg.tolerations }}
              tolerations:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- end }}
  {{- end }}
{{- end }}
