{{- if and .Values.proxy.enabled .Values.proxy.wg.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: laboratory-proxy-wg
  namespace: laboratory-proxy
  labels:
    app: laboratory-proxy-wg
    {{- include "laboratory.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: laboratory-proxy-wg
  template:
    metadata:
      labels:
        app: laboratory-proxy-wg
    spec:
      serviceAccountName: laboratory-proxy
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- with .Values.proxy.wg.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxy.wg.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: proxy-wg
        image: "{{ .Values.proxy.wg.image.repository }}:{{ .Values.proxy.wg.image.tag }}"
        imagePullPolicy: {{ .Values.proxy.wg.image.pullPolicy }}
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_ADMIN"]
        env:
        - name: UDP_LISTEN_ADDR
          value: {{ .Values.proxy.wg.udpListen | quote }}
        - name: VPN_SERVICE_PORT
          value: {{ .Values.operator.vpnServicePort | quote }}
        - name: EXTERNAL_INTERFACE
          value: {{ .Values.proxy.wg.externalInterface | quote }}
        {{- if .Values.proxy.kindMode }}
        - name: KUBERNETES_SERVICE_HOST
          value: "127.0.0.1"
        - name: KUBERNETES_SERVICE_PORT
          value: "6443"
        {{- end }}
        resources:
          {{- toYaml .Values.proxy.wg.resources | nindent 10 }}
{{- end }}
