{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: laboratory-proxy
  namespace: {{ .Values.proxy.namespace }}
  labels:
    {{- include "laboratory.labels" . | nindent 4 }}
{{- end }}
