FROM golang:1.27.1 AS builder
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o vpn ./cmd/vpn

FROM debian:12-slim
RUN apt-get update && apt-get install -y --no-install-recommends iptables iproute2 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /workspace/vpn /vpn
ENTRYPOINT ["/vpn"]
