FROM --platform=$BUILDPLATFORM golang:1.27.1 AS builder
ARG TARGETARCH
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=$TARGETARCH go build -trimpath -ldflags="-s -w" -o vpn ./cmd/vpn && \
    CGO_ENABLED=0 GOOS=linux GOARCH=$TARGETARCH go build -trimpath -ldflags="-s -w" -o gateway ./cmd/gateway

FROM debian:12-slim
RUN apt-get update && apt-get install -y --no-install-recommends iptables iproute2 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /workspace/vpn     /vpn
COPY --from=builder /workspace/gateway /gateway
