FROM golang:1.26 AS builder
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -o proxy-wg ./cmd/proxy-wg

FROM debian:12-slim
COPY --from=builder /workspace/proxy-wg /proxy-wg
ENTRYPOINT ["/proxy-wg"]
