/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ConnectionListerExpansion allows custom methods to be added to
// ConnectionLister.
type ConnectionListerExpansion interface{}

// ConnectionNamespaceListerExpansion allows custom methods to be added to
// ConnectionNamespaceLister.
type ConnectionNamespaceListerExpansion interface{}

// DeviceListerExpansion allows custom methods to be added to
// DeviceLister.
type DeviceListerExpansion interface{}

// DeviceNamespaceListerExpansion allows custom methods to be added to
// DeviceNamespaceLister.
type DeviceNamespaceListerExpansion interface{}

// LaboratoryListerExpansion allows custom methods to be added to
// LaboratoryLister.
type LaboratoryListerExpansion interface{}

// LaboratoryNamespaceListerExpansion allows custom methods to be added to
// LaboratoryNamespaceLister.
type LaboratoryNamespaceListerExpansion interface{}

// UnmanagedSwitchListerExpansion allows custom methods to be added to
// UnmanagedSwitchLister.
type UnmanagedSwitchListerExpansion interface{}

// UnmanagedSwitchNamespaceListerExpansion allows custom methods to be added to
// UnmanagedSwitchNamespaceLister.
type UnmanagedSwitchNamespaceListerExpansion interface{}
