/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ConnectionListerExpansion allows custom methods to be added to
// ConnectionLister.
type ConnectionListerExpansion interface{}

// ConnectionNamespaceListerExpansion allows custom methods to be added to
// ConnectionNamespaceLister.
type ConnectionNamespaceListerExpansion interface{}

// DeviceListerExpansion allows custom methods to be added to
// DeviceLister.
type DeviceListerExpansion interface{}

// DeviceNamespaceListerExpansion allows custom methods to be added to
// DeviceNamespaceLister.
type DeviceNamespaceListerExpansion interface{}

// LabListerExpansion allows custom methods to be added to
// LabLister.
type LabListerExpansion interface{}

// LabNamespaceListerExpansion allows custom methods to be added to
// LabNamespaceLister.
type LabNamespaceListerExpansion interface{}

// LabGatewayListerExpansion allows custom methods to be added to
// LabGatewayLister.
type LabGatewayListerExpansion interface{}

// LabGatewayNamespaceListerExpansion allows custom methods to be added to
// LabGatewayNamespaceLister.
type LabGatewayNamespaceListerExpansion interface{}

// LabGroupListerExpansion allows custom methods to be added to
// LabGroupLister.
type LabGroupListerExpansion interface{}

// LabGroupAccessPolicyListerExpansion allows custom methods to be added to
// LabGroupAccessPolicyLister.
type LabGroupAccessPolicyListerExpansion interface{}

// LabGroupAccessPolicyNamespaceListerExpansion allows custom methods to be added to
// LabGroupAccessPolicyNamespaceLister.
type LabGroupAccessPolicyNamespaceListerExpansion interface{}

// LabGroupClientListerExpansion allows custom methods to be added to
// LabGroupClientLister.
type LabGroupClientListerExpansion interface{}

// LabGroupClientNamespaceListerExpansion allows custom methods to be added to
// LabGroupClientNamespaceLister.
type LabGroupClientNamespaceListerExpansion interface{}

// LabTrafficReportListerExpansion allows custom methods to be added to
// LabTrafficReportLister.
type LabTrafficReportListerExpansion interface{}

// LabTrafficReportNamespaceListerExpansion allows custom methods to be added to
// LabTrafficReportNamespaceLister.
type LabTrafficReportNamespaceListerExpansion interface{}

// LabVPNListerExpansion allows custom methods to be added to
// LabVPNLister.
type LabVPNListerExpansion interface{}

// LabVPNNamespaceListerExpansion allows custom methods to be added to
// LabVPNNamespaceLister.
type LabVPNNamespaceListerExpansion interface{}
