/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	laboratoryv1alpha1 "github.com/cybericebox/laboratory/api/laboratory/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// LabLister helps list Labs.
// All objects returned here must be treated as read-only.
type LabLister interface {
	// List lists all Labs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*laboratoryv1alpha1.Lab, err error)
	// Labs returns an object that can list and get Labs.
	Labs(namespace string) LabNamespaceLister
	LabListerExpansion
}

// labLister implements the LabLister interface.
type labLister struct {
	listers.ResourceIndexer[*laboratoryv1alpha1.Lab]
}

// NewLabLister returns a new LabLister.
func NewLabLister(indexer cache.Indexer) LabLister {
	return &labLister{listers.New[*laboratoryv1alpha1.Lab](indexer, laboratoryv1alpha1.Resource("lab"))}
}

// Labs returns an object that can list and get Labs.
func (s *labLister) Labs(namespace string) LabNamespaceLister {
	return labNamespaceLister{listers.NewNamespaced[*laboratoryv1alpha1.Lab](s.ResourceIndexer, namespace)}
}

// LabNamespaceLister helps list and get Labs.
// All objects returned here must be treated as read-only.
type LabNamespaceLister interface {
	// List lists all Labs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*laboratoryv1alpha1.Lab, err error)
	// Get retrieves the Lab from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*laboratoryv1alpha1.Lab, error)
	LabNamespaceListerExpansion
}

// labNamespaceLister implements the LabNamespaceLister
// interface.
type labNamespaceLister struct {
	listers.ResourceIndexer[*laboratoryv1alpha1.Lab]
}
