/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	laboratoryv1alpha1 "github.com/cybericebox/laboratory/api/laboratory/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// LabGroupLister helps list LabGroups.
// All objects returned here must be treated as read-only.
type LabGroupLister interface {
	// List lists all LabGroups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*laboratoryv1alpha1.LabGroup, err error)
	// Get retrieves the LabGroup from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*laboratoryv1alpha1.LabGroup, error)
	LabGroupListerExpansion
}

// labGroupLister implements the LabGroupLister interface.
type labGroupLister struct {
	listers.ResourceIndexer[*laboratoryv1alpha1.LabGroup]
}

// NewLabGroupLister returns a new LabGroupLister.
func NewLabGroupLister(indexer cache.Indexer) LabGroupLister {
	return &labGroupLister{listers.New[*laboratoryv1alpha1.LabGroup](indexer, laboratoryv1alpha1.Resource("labgroup"))}
}
