/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	laboratoryv1alpha1 "github.com/cybericebox/laboratory/api/laboratory/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// LabGroupClientLister helps list LabGroupClients.
// All objects returned here must be treated as read-only.
type LabGroupClientLister interface {
	// List lists all LabGroupClients in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*laboratoryv1alpha1.LabGroupClient, err error)
	// LabGroupClients returns an object that can list and get LabGroupClients.
	LabGroupClients(namespace string) LabGroupClientNamespaceLister
	LabGroupClientListerExpansion
}

// labGroupClientLister implements the LabGroupClientLister interface.
type labGroupClientLister struct {
	listers.ResourceIndexer[*laboratoryv1alpha1.LabGroupClient]
}

// NewLabGroupClientLister returns a new LabGroupClientLister.
func NewLabGroupClientLister(indexer cache.Indexer) LabGroupClientLister {
	return &labGroupClientLister{listers.New[*laboratoryv1alpha1.LabGroupClient](indexer, laboratoryv1alpha1.Resource("labgroupclient"))}
}

// LabGroupClients returns an object that can list and get LabGroupClients.
func (s *labGroupClientLister) LabGroupClients(namespace string) LabGroupClientNamespaceLister {
	return labGroupClientNamespaceLister{listers.NewNamespaced[*laboratoryv1alpha1.LabGroupClient](s.ResourceIndexer, namespace)}
}

// LabGroupClientNamespaceLister helps list and get LabGroupClients.
// All objects returned here must be treated as read-only.
type LabGroupClientNamespaceLister interface {
	// List lists all LabGroupClients in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*laboratoryv1alpha1.LabGroupClient, err error)
	// Get retrieves the LabGroupClient from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*laboratoryv1alpha1.LabGroupClient, error)
	LabGroupClientNamespaceListerExpansion
}

// labGroupClientNamespaceLister implements the LabGroupClientNamespaceLister
// interface.
type labGroupClientNamespaceLister struct {
	listers.ResourceIndexer[*laboratoryv1alpha1.LabGroupClient]
}
