/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	laboratoryv1alpha1 "github.com/cybericebox/laboratory/api/laboratory/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// LaboratoryLister helps list Laboratories.
// All objects returned here must be treated as read-only.
type LaboratoryLister interface {
	// List lists all Laboratories in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*laboratoryv1alpha1.Laboratory, err error)
	// Laboratories returns an object that can list and get Laboratories.
	Laboratories(namespace string) LaboratoryNamespaceLister
	LaboratoryListerExpansion
}

// laboratoryLister implements the LaboratoryLister interface.
type laboratoryLister struct {
	listers.ResourceIndexer[*laboratoryv1alpha1.Laboratory]
}

// NewLaboratoryLister returns a new LaboratoryLister.
func NewLaboratoryLister(indexer cache.Indexer) LaboratoryLister {
	return &laboratoryLister{listers.New[*laboratoryv1alpha1.Laboratory](indexer, laboratoryv1alpha1.Resource("laboratory"))}
}

// Laboratories returns an object that can list and get Laboratories.
func (s *laboratoryLister) Laboratories(namespace string) LaboratoryNamespaceLister {
	return laboratoryNamespaceLister{listers.NewNamespaced[*laboratoryv1alpha1.Laboratory](s.ResourceIndexer, namespace)}
}

// LaboratoryNamespaceLister helps list and get Laboratories.
// All objects returned here must be treated as read-only.
type LaboratoryNamespaceLister interface {
	// List lists all Laboratories in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*laboratoryv1alpha1.Laboratory, err error)
	// Get retrieves the Laboratory from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*laboratoryv1alpha1.Laboratory, error)
	LaboratoryNamespaceListerExpansion
}

// laboratoryNamespaceLister implements the LaboratoryNamespaceLister
// interface.
type laboratoryNamespaceLister struct {
	listers.ResourceIndexer[*laboratoryv1alpha1.Laboratory]
}
