/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	laboratoryv1alpha1 "github.com/cybericebox/laboratory/api/laboratory/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// LabTrafficReportLister helps list LabTrafficReports.
// All objects returned here must be treated as read-only.
type LabTrafficReportLister interface {
	// List lists all LabTrafficReports in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*laboratoryv1alpha1.LabTrafficReport, err error)
	// LabTrafficReports returns an object that can list and get LabTrafficReports.
	LabTrafficReports(namespace string) LabTrafficReportNamespaceLister
	LabTrafficReportListerExpansion
}

// labTrafficReportLister implements the LabTrafficReportLister interface.
type labTrafficReportLister struct {
	listers.ResourceIndexer[*laboratoryv1alpha1.LabTrafficReport]
}

// NewLabTrafficReportLister returns a new LabTrafficReportLister.
func NewLabTrafficReportLister(indexer cache.Indexer) LabTrafficReportLister {
	return &labTrafficReportLister{listers.New[*laboratoryv1alpha1.LabTrafficReport](indexer, laboratoryv1alpha1.Resource("labtrafficreport"))}
}

// LabTrafficReports returns an object that can list and get LabTrafficReports.
func (s *labTrafficReportLister) LabTrafficReports(namespace string) LabTrafficReportNamespaceLister {
	return labTrafficReportNamespaceLister{listers.NewNamespaced[*laboratoryv1alpha1.LabTrafficReport](s.ResourceIndexer, namespace)}
}

// LabTrafficReportNamespaceLister helps list and get LabTrafficReports.
// All objects returned here must be treated as read-only.
type LabTrafficReportNamespaceLister interface {
	// List lists all LabTrafficReports in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*laboratoryv1alpha1.LabTrafficReport, err error)
	// Get retrieves the LabTrafficReport from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*laboratoryv1alpha1.LabTrafficReport, error)
	LabTrafficReportNamespaceListerExpansion
}

// labTrafficReportNamespaceLister implements the LabTrafficReportNamespaceLister
// interface.
type labTrafficReportNamespaceLister struct {
	listers.ResourceIndexer[*laboratoryv1alpha1.LabTrafficReport]
}
