// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package xdp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type WgDemuxDstEntry struct {
	_    structs.HostLayout
	Ip   uint32
	Port uint16
	Pad  uint16
}

type WgDemuxXdpCfg struct {
	_         structs.HostLayout
	ProxyIp   uint32
	ProxyPort uint16
	GwMac     [6]uint8
	Pad       [2]uint8
	_         [2]byte
}

// LoadWgDemux returns the embedded CollectionSpec for WgDemux.
func LoadWgDemux() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_WgDemuxBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load WgDemux: %w", err)
	}

	return spec, err
}

// LoadWgDemuxObjects loads WgDemux and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*WgDemuxObjects
//	*WgDemuxPrograms
//	*WgDemuxMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadWgDemuxObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadWgDemux()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// WgDemuxSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type WgDemuxSpecs struct {
	WgDemuxProgramSpecs
	WgDemuxMapSpecs
	WgDemuxVariableSpecs
}

// WgDemuxProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type WgDemuxProgramSpecs struct {
	WgDemux *ebpf.ProgramSpec `ebpf:"wg_demux"`
}

// WgDemuxMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type WgDemuxMapSpecs struct {
	WgSessions *ebpf.MapSpec `ebpf:"wg_sessions"`
	XdpCfgMap  *ebpf.MapSpec `ebpf:"xdp_cfg_map"`
}

// WgDemuxVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type WgDemuxVariableSpecs struct {
}

// WgDemuxObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadWgDemuxObjects or ebpf.CollectionSpec.LoadAndAssign.
type WgDemuxObjects struct {
	WgDemuxPrograms
	WgDemuxMaps
	WgDemuxVariables
}

func (o *WgDemuxObjects) Close() error {
	return _WgDemuxClose(
		&o.WgDemuxPrograms,
		&o.WgDemuxMaps,
	)
}

// WgDemuxMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadWgDemuxObjects or ebpf.CollectionSpec.LoadAndAssign.
type WgDemuxMaps struct {
	WgSessions *ebpf.Map `ebpf:"wg_sessions"`
	XdpCfgMap  *ebpf.Map `ebpf:"xdp_cfg_map"`
}

func (m *WgDemuxMaps) Close() error {
	return _WgDemuxClose(
		m.WgSessions,
		m.XdpCfgMap,
	)
}

// WgDemuxVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadWgDemuxObjects or ebpf.CollectionSpec.LoadAndAssign.
type WgDemuxVariables struct {
}

// WgDemuxPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadWgDemuxObjects or ebpf.CollectionSpec.LoadAndAssign.
type WgDemuxPrograms struct {
	WgDemux *ebpf.Program `ebpf:"wg_demux"`
}

func (p *WgDemuxPrograms) Close() error {
	return _WgDemuxClose(
		p.WgDemux,
	)
}

func _WgDemuxClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed wgdemux_bpfeb.o
var _WgDemuxBytes []byte
