{{- if .Values.platform.jwtPublicKey }}
apiVersion: v1
kind: Secret
metadata:
  name: lab-platform-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laboratory.labels" . | nindent 4 }}
type: Opaque
stringData:
  publicKey: {{ .Values.platform.jwtPublicKey | quote }}
{{- end }}
