{{- if .Values.platform.labAccessPublicKey }}
apiVersion: v1
kind: Secret
metadata:
  name: lab-access-public-key
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laboratory.labels" . | nindent 4 }}
type: Opaque
stringData:
  public.pem: {{ .Values.platform.labAccessPublicKey | quote }}
{{- end }}
