{{- if and .Values.agent.enabled .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: laboratory-agent-server
  namespace: laboratory-agent
  labels:
    {{- include "laboratory.labels" . | nindent 4 }}
spec:
  secretName: laboratory-agent-server-tls
  dnsNames:
    - {{ include "laboratory.agentDomain" . | quote }}
  issuerRef:
    name: {{ .Values.certManager.issuerName }}
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
