{{- if .Values.agent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: laboratory-agent
  namespace: laboratory-agent
  labels:
    {{- include "laboratory.labels" . | nindent 4 }}
{{- end }}
