{{- if and .Values.agent.enabled .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: laboratory-agent
  namespace: laboratory-agent
  labels:
    {{- include "laboratory.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: laboratory-gateway
      namespace: {{ .Release.Namespace }}
  hostnames:
    - {{ include "laboratory.agentDomain" . | quote }}
  rules:
    - backendRefs:
        - name: laboratory-agent
          port: {{ .Values.agent.grpcPort }}
{{- end }}
