---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-agent
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-agent
rules:
  - apiGroups: ["laboratory.cybericebox.com"]
    resources: ["labs", "devices", "connections"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["laboratory.cybericebox.com"]
    resources: ["connections/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-agent
subjects:
  - kind: ServiceAccount
    name: node-agent
    namespace: system
