// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: node_agent.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPodAnnotationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodAnnotationRequest) Reset() {
	*x = GetPodAnnotationRequest{}
	mi := &file_node_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodAnnotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodAnnotationRequest) ProtoMessage() {}

func (x *GetPodAnnotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodAnnotationRequest.ProtoReflect.Descriptor instead.
func (*GetPodAnnotationRequest) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{0}
}

func (x *GetPodAnnotationRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetPodAnnotationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPodAnnotationRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetPodAnnotationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodAnnotationResponse) Reset() {
	*x = GetPodAnnotationResponse{}
	mi := &file_node_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodAnnotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodAnnotationResponse) ProtoMessage() {}

func (x *GetPodAnnotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodAnnotationResponse.ProtoReflect.Descriptor instead.
func (*GetPodAnnotationResponse) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GetPodAnnotationResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetPodAnnotationResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type SetupNetworksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PodUid        string                 `protobuf:"bytes,3,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	NetnsPath     string                 `protobuf:"bytes,4,opt,name=netns_path,json=netnsPath,proto3" json:"netns_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupNetworksRequest) Reset() {
	*x = SetupNetworksRequest{}
	mi := &file_node_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupNetworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupNetworksRequest) ProtoMessage() {}

func (x *SetupNetworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupNetworksRequest.ProtoReflect.Descriptor instead.
func (*SetupNetworksRequest) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{2}
}

func (x *SetupNetworksRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SetupNetworksRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetupNetworksRequest) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *SetupNetworksRequest) GetNetnsPath() string {
	if x != nil {
		return x.NetnsPath
	}
	return ""
}

type SetupNetworksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How cni-gate should handle the default k8s interface (eth0).
	// "real"  — delegate to k8s CNI normally (no annotation or annotation == "eth0")
	// "stub"  — stub eth0 only; all OVS interfaces already wired
	// other   — access interface name; delegate k8s CNI to that iface + stub eth0
	DefaultNetwork string `protobuf:"bytes,1,opt,name=default_network,json=defaultNetwork,proto3" json:"default_network,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetupNetworksResponse) Reset() {
	*x = SetupNetworksResponse{}
	mi := &file_node_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupNetworksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupNetworksResponse) ProtoMessage() {}

func (x *SetupNetworksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupNetworksResponse.ProtoReflect.Descriptor instead.
func (*SetupNetworksResponse) Descriptor() ([]byte, []int) {
	return file_node_agent_proto_rawDescGZIP(), []int{3}
}

func (x *SetupNetworksResponse) GetDefaultNetwork() string {
	if x != nil {
		return x.DefaultNetwork
	}
	return ""
}

var File_node_agent_proto protoreflect.FileDescriptor

const file_node_agent_proto_rawDesc = "" +
	"\n" +
	"\x10node_agent.proto\x12\anode.v1\"]\n" +
	"\x17GetPodAnnotationRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"F\n" +
	"\x18GetPodAnnotationResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x80\x01\n" +
	"\x14SetupNetworksRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\apod_uid\x18\x03 \x01(\tR\x06podUid\x12\x1d\n" +
	"\n" +
	"netns_path\x18\x04 \x01(\tR\tnetnsPath\"@\n" +
	"\x15SetupNetworksResponse\x12'\n" +
	"\x0fdefault_network\x18\x01 \x01(\tR\x0edefaultNetwork2\xb4\x01\n" +
	"\tNodeAgent\x12N\n" +
	"\rSetupNetworks\x12\x1d.node.v1.SetupNetworksRequest\x1a\x1e.node.v1.SetupNetworksResponse\x12W\n" +
	"\x10GetPodAnnotation\x12 .node.v1.GetPodAnnotationRequest\x1a!.node.v1.GetPodAnnotationResponseB/Z-github.com/cybericebox/laboratory/api/node/v1b\x06proto3"

var (
	file_node_agent_proto_rawDescOnce sync.Once
	file_node_agent_proto_rawDescData []byte
)

func file_node_agent_proto_rawDescGZIP() []byte {
	file_node_agent_proto_rawDescOnce.Do(func() {
		file_node_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_agent_proto_rawDesc), len(file_node_agent_proto_rawDesc)))
	})
	return file_node_agent_proto_rawDescData
}

var file_node_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_node_agent_proto_goTypes = []any{
	(*GetPodAnnotationRequest)(nil),  // 0: node.v1.GetPodAnnotationRequest
	(*GetPodAnnotationResponse)(nil), // 1: node.v1.GetPodAnnotationResponse
	(*SetupNetworksRequest)(nil),     // 2: node.v1.SetupNetworksRequest
	(*SetupNetworksResponse)(nil),    // 3: node.v1.SetupNetworksResponse
}
var file_node_agent_proto_depIdxs = []int32{
	2, // 0: node.v1.NodeAgent.SetupNetworks:input_type -> node.v1.SetupNetworksRequest
	0, // 1: node.v1.NodeAgent.GetPodAnnotation:input_type -> node.v1.GetPodAnnotationRequest
	3, // 2: node.v1.NodeAgent.SetupNetworks:output_type -> node.v1.SetupNetworksResponse
	1, // 3: node.v1.NodeAgent.GetPodAnnotation:output_type -> node.v1.GetPodAnnotationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_agent_proto_init() }
func file_node_agent_proto_init() {
	if File_node_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_agent_proto_rawDesc), len(file_node_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_agent_proto_goTypes,
		DependencyIndexes: file_node_agent_proto_depIdxs,
		MessageInfos:      file_node_agent_proto_msgTypes,
	}.Build()
	File_node_agent_proto = out.File
	file_node_agent_proto_goTypes = nil
	file_node_agent_proto_depIdxs = nil
}
