---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - namespaces
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingadmissionpolicies
  - validatingadmissionpolicybindings
  verbs:
  - get
- apiGroups:
  - allocation.cybericebox.com
  resources:
  - pools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - allocation.cybericebox.com
  resources:
  - pools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cilium.io
  resources:
  - ciliumnetworkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - laboratory.cybericebox.com
  resources:
  - connections
  - devices
  - labgateways
  - labgroupclients
  - labgroups
  - labs
  - labvpns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - laboratory.cybericebox.com
  resources:
  - connections/finalizers
  - devices/finalizers
  - labgateways/finalizers
  - labgroupclients/finalizers
  - labgroups/finalizers
  - labs/finalizers
  - labvpns/finalizers
  verbs:
  - update
- apiGroups:
  - laboratory.cybericebox.com
  resources:
  - connections/status
  - devices/status
  - labgateways/status
  - labgroupclients/status
  - labgroups/status
  - labs/status
  - labvpns/status
  - tenants/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - laboratory.cybericebox.com
  resources:
  - imagepulls
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - laboratory.cybericebox.com
  resources:
  - labtrafficreports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - laboratory.cybericebox.com
  resources:
  - tenants
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - laboratory-agent-role
  - laboratory-operator-namespaced
  - laboratory-proxy-reports
  - laboratory-vpn-role
  resources:
  - clusterroles
  verbs:
  - bind
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
