apiVersion: laboratory.cybericebox.com/v1alpha1
kind: UnmanagedSwitch
metadata:
  labels:
    app.kubernetes.io/name: laboratory
    app.kubernetes.io/managed-by: kustomize
  name: unmanagedswitch-sample
spec:
# TODO(user): Add fields here
