apiVersion: laboratory.cybericebox.com/v1alpha1
kind: Connection
metadata:
  name: connection-sample
spec:
  laboratory: laboratory-sample
  ports:
    - device: test
      port: net1
    - device: test
      port: net2
---
apiVersion: laboratory.cybericebox.com/v1alpha1
kind: Connection
metadata:
  name: connection-sample1
spec:
  laboratory: laboratory-sample
  ports:
    - device: test
      port: net1
    - device: test
      port: net2
---
apiVersion: laboratory.cybericebox.com/v1alpha1
kind: Connection
metadata:
  name: connection-sample2
spec:
  laboratory: laboratory-sample
  ports:
    - device: test
      port: net1
    - device: test
      port: net2
---
apiVersion: laboratory.cybericebox.com/v1alpha1
kind: Connection
metadata:
  name: connection-sample4
spec:
  laboratory: laboratory-sample
  ports:
    - device: test
      port: net1
    - device: test
      port: net2
---
apiVersion: laboratory.cybericebox.com/v1alpha1
kind: Connection
metadata:
  name: connection-sample5
spec:
  laboratory: laboratory-sample
  ports:
    - device: test
      port: net1
    - device: test
      port: net2
---
apiVersion: laboratory.cybericebox.com/v1alpha1
kind: Connection
metadata:
  name: connection-sample6
spec:
  laboratory: laboratory-sample
  ports:
    - device: test
      port: net1
    - device: test
      port: net2
---
apiVersion: laboratory.cybericebox.com/v1alpha1
kind: Connection
metadata:
  name: connection-sample7
spec:
  laboratory: laboratory-sample
  ports:
    - device: test
      port: net1
    - device: test
      port: net2
---
apiVersion: laboratory.cybericebox.com/v1alpha1
kind: Connection
metadata:
  name: connection-sample8
spec:
  laboratory: laboratory-sample
  ports:
    - device: test
      port: net1
    - device: test
      port: net2
---
apiVersion: laboratory.cybericebox.com/v1alpha1
kind: Connection
metadata:
  name: connection-sample9
spec:
  laboratory: laboratory-sample
  ports:
    - device: test
      port: net1
    - device: test
      port: net2
---
apiVersion: laboratory.cybericebox.com/v1alpha1
kind: Connection
metadata:
  name: connection-sample10
spec:
  laboratory: laboratory-sample
  ports:
    - device: test
      port: net1
    - device: test
      port: net2
---
apiVersion: laboratory.cybericebox.com/v1alpha1
kind: Connection
metadata:
  name: connection-sample11
spec:
  laboratory: laboratory-sample
  ports:
    - device: test
      port: net1
    - device: test
      port: net2
---
apiVersion: laboratory.cybericebox.com/v1alpha1
kind: Connection
metadata:
  name: connection-sample12
spec:
  laboratory: laboratory-sample
  ports:
    - device: test
      port: net1
    - device: test
      port: net2
---
apiVersion: laboratory.cybericebox.com/v1alpha1
kind: Connection
metadata:
  name: connection-sample14
spec:
  laboratory: laboratory-sample
  ports:
    - device: test
      port: net1
    - device: test
      port: net2
---
apiVersion: laboratory.cybericebox.com/v1alpha1
kind: Connection
metadata:
  name: connection-sample15
spec:
  laboratory: laboratory-sample
  ports:
    - device: test
      port: net1
    - device: test
      port: net2
---
apiVersion: laboratory.cybericebox.com/v1alpha1
kind: Connection
metadata:
  name: connection-sample16
spec:
  laboratory: laboratory-sample
  ports:
    - device: test
      port: net1
    - device: test
      port: net2
---
apiVersion: laboratory.cybericebox.com/v1alpha1
kind: Connection
metadata:
  name: connection-sample17
spec:
  laboratory: laboratory-sample
  ports:
    - device: test
      port: net1
    - device: test
      port: net2
---
apiVersion: laboratory.cybericebox.com/v1alpha1
kind: Connection
metadata:
  name: connection-sample18
spec:
  laboratory: laboratory-sample
  ports:
    - device: test
      port: net1
    - device: test
      port: net2
---
apiVersion: laboratory.cybericebox.com/v1alpha1
kind: Connection
metadata:
  name: connection-sample19
spec:
  laboratory: laboratory-sample
  ports:
    - device: test
      port: net1
    - device: test
      port: net2
