// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: pkg/agent/protobuf/agent.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LabGroupAccessAction int32

const (
	LabGroupAccessAction_LAB_GROUP_ACCESS_ACTION_UNSPECIFIED LabGroupAccessAction = 0
	LabGroupAccessAction_LAB_GROUP_ACCESS_ACTION_ALLOW       LabGroupAccessAction = 1
	LabGroupAccessAction_LAB_GROUP_ACCESS_ACTION_DENY        LabGroupAccessAction = 2
)

// Enum value maps for LabGroupAccessAction.
var (
	LabGroupAccessAction_name = map[int32]string{
		0: "LAB_GROUP_ACCESS_ACTION_UNSPECIFIED",
		1: "LAB_GROUP_ACCESS_ACTION_ALLOW",
		2: "LAB_GROUP_ACCESS_ACTION_DENY",
	}
	LabGroupAccessAction_value = map[string]int32{
		"LAB_GROUP_ACCESS_ACTION_UNSPECIFIED": 0,
		"LAB_GROUP_ACCESS_ACTION_ALLOW":       1,
		"LAB_GROUP_ACCESS_ACTION_DENY":        2,
	}
)

func (x LabGroupAccessAction) Enum() *LabGroupAccessAction {
	p := new(LabGroupAccessAction)
	*p = x
	return p
}

func (x LabGroupAccessAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LabGroupAccessAction) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_agent_protobuf_agent_proto_enumTypes[0].Descriptor()
}

func (LabGroupAccessAction) Type() protoreflect.EnumType {
	return &file_pkg_agent_protobuf_agent_proto_enumTypes[0]
}

func (x LabGroupAccessAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LabGroupAccessAction.Descriptor instead.
func (LabGroupAccessAction) EnumDescriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{0}
}

type IDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDRequest) Reset() {
	*x = IDRequest{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDRequest) ProtoMessage() {}

func (x *IDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDRequest.ProtoReflect.Descriptor instead.
func (*IDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{1}
}

func (x *IDRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceRequest) Reset() {
	*x = NamespaceRequest{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceRequest) ProtoMessage() {}

func (x *NamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceRequest.ProtoReflect.Descriptor instead.
func (*NamespaceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{2}
}

func (x *NamespaceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type NamespacedIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespacedIDRequest) Reset() {
	*x = NamespacedIDRequest{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespacedIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespacedIDRequest) ProtoMessage() {}

func (x *NamespacedIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespacedIDRequest.ProtoReflect.Descriptor instead.
func (*NamespacedIDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{3}
}

func (x *NamespacedIDRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NamespacedIDRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LabGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        *LabGroupStatus        `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabGroup) Reset() {
	*x = LabGroup{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabGroup) ProtoMessage() {}

func (x *LabGroup) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabGroup.ProtoReflect.Descriptor instead.
func (*LabGroup) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{4}
}

func (x *LabGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LabGroup) GetStatus() *LabGroupStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type LabGroupStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	VpnRegistered bool                   `protobuf:"varint,3,opt,name=vpn_registered,json=vpnRegistered,proto3" json:"vpn_registered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabGroupStatus) Reset() {
	*x = LabGroupStatus{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabGroupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabGroupStatus) ProtoMessage() {}

func (x *LabGroupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabGroupStatus.ProtoReflect.Descriptor instead.
func (*LabGroupStatus) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{5}
}

func (x *LabGroupStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *LabGroupStatus) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LabGroupStatus) GetVpnRegistered() bool {
	if x != nil {
		return x.VpnRegistered
	}
	return false
}

type LabGroupList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LabGroup            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabGroupList) Reset() {
	*x = LabGroupList{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabGroupList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabGroupList) ProtoMessage() {}

func (x *LabGroupList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabGroupList.ProtoReflect.Descriptor instead.
func (*LabGroupList) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{6}
}

func (x *LabGroupList) GetItems() []*LabGroup {
	if x != nil {
		return x.Items
	}
	return nil
}

type Lab struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SpecJson  []byte                 `protobuf:"bytes,3,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"` // Lab.spec serialized; agent is a thin wrapper, spec passes through
	Status    *LabStatus             `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// Per-device environment variables. The agent materializes these into a
	// write-only per-device Secret (referenced by the pod via envFrom) — the
	// values never travel in spec_json and never land in the Lab/Device CR.
	Env []*DeviceEnv `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty"`
	// Populated only by monitoring so the backend can associate a namespaced
	// Lab record with its LabGroup without inferring it from a namespace.
	LabGroupName  string `protobuf:"bytes,6,opt,name=lab_group_name,json=labGroupName,proto3" json:"lab_group_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lab) Reset() {
	*x = Lab{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lab) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lab) ProtoMessage() {}

func (x *Lab) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lab.ProtoReflect.Descriptor instead.
func (*Lab) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Lab) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Lab) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Lab) GetSpecJson() []byte {
	if x != nil {
		return x.SpecJson
	}
	return nil
}

func (x *Lab) GetStatus() *LabStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Lab) GetEnv() []*DeviceEnv {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Lab) GetLabGroupName() string {
	if x != nil {
		return x.LabGroupName
	}
	return ""
}

// DeviceEnv carries the env vars for one device (e.g. a task flag, a license).
type DeviceEnv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Vars          map[string]string      `protobuf:"bytes,2,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceEnv) Reset() {
	*x = DeviceEnv{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceEnv) ProtoMessage() {}

func (x *DeviceEnv) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceEnv.ProtoReflect.Descriptor instead.
func (*DeviceEnv) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceEnv) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DeviceEnv) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

type LabStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	VpnCidr       string                 `protobuf:"bytes,2,opt,name=vpn_cidr,json=vpnCidr,proto3" json:"vpn_cidr,omitempty"`
	InternetCidr  string                 `protobuf:"bytes,3,opt,name=internet_cidr,json=internetCidr,proto3" json:"internet_cidr,omitempty"`
	Ready         bool                   `protobuf:"varint,4,opt,name=ready,proto3" json:"ready,omitempty"`
	AccessUrls    []string               `protobuf:"bytes,5,rep,name=access_urls,json=accessUrls,proto3" json:"access_urls,omitempty"` // flat list of exposed URLs (kept for convenience)
	VpnReady      bool                   `protobuf:"varint,6,opt,name=vpn_ready,json=vpnReady,proto3" json:"vpn_ready,omitempty"`
	InternetReady bool                   `protobuf:"varint,7,opt,name=internet_ready,json=internetReady,proto3" json:"internet_ready,omitempty"`
	Devices       []*LabDeviceStatus     `protobuf:"bytes,8,rep,name=devices,proto3" json:"devices,omitempty"`         // per-device readiness
	Connections   []*LabConnectionStatus `protobuf:"bytes,9,rep,name=connections,proto3" json:"connections,omitempty"` // per-connection readiness
	Access        []*LabAccessEntry      `protobuf:"bytes,10,rep,name=access,proto3" json:"access,omitempty"`          // structured web-exposure entries
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabStatus) Reset() {
	*x = LabStatus{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabStatus) ProtoMessage() {}

func (x *LabStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabStatus.ProtoReflect.Descriptor instead.
func (*LabStatus) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{9}
}

func (x *LabStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *LabStatus) GetVpnCidr() string {
	if x != nil {
		return x.VpnCidr
	}
	return ""
}

func (x *LabStatus) GetInternetCidr() string {
	if x != nil {
		return x.InternetCidr
	}
	return ""
}

func (x *LabStatus) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *LabStatus) GetAccessUrls() []string {
	if x != nil {
		return x.AccessUrls
	}
	return nil
}

func (x *LabStatus) GetVpnReady() bool {
	if x != nil {
		return x.VpnReady
	}
	return false
}

func (x *LabStatus) GetInternetReady() bool {
	if x != nil {
		return x.InternetReady
	}
	return false
}

func (x *LabStatus) GetDevices() []*LabDeviceStatus {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *LabStatus) GetConnections() []*LabConnectionStatus {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *LabStatus) GetAccess() []*LabAccessEntry {
	if x != nil {
		return x.Access
	}
	return nil
}

type LabDeviceStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ready                bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	CpuMillicores        int64                  `protobuf:"varint,3,opt,name=cpu_millicores,json=cpuMillicores,proto3" json:"cpu_millicores,omitempty"`
	MemoryBytes          int64                  `protobuf:"varint,4,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	UsageAvailable       bool                   `protobuf:"varint,5,opt,name=usage_available,json=usageAvailable,proto3" json:"usage_available,omitempty"`
	CpuRequestMillicores int64                  `protobuf:"varint,6,opt,name=cpu_request_millicores,json=cpuRequestMillicores,proto3" json:"cpu_request_millicores,omitempty"`
	MemoryRequestBytes   int64                  `protobuf:"varint,7,opt,name=memory_request_bytes,json=memoryRequestBytes,proto3" json:"memory_request_bytes,omitempty"`
	CpuLimitMillicores   int64                  `protobuf:"varint,8,opt,name=cpu_limit_millicores,json=cpuLimitMillicores,proto3" json:"cpu_limit_millicores,omitempty"`
	MemoryLimitBytes     int64                  `protobuf:"varint,9,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	PodPhase             string                 `protobuf:"bytes,10,opt,name=pod_phase,json=podPhase,proto3" json:"pod_phase,omitempty"`
	PodReason            string                 `protobuf:"bytes,11,opt,name=pod_reason,json=podReason,proto3" json:"pod_reason,omitempty"`
	RestartCount         int32                  `protobuf:"varint,12,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LabDeviceStatus) Reset() {
	*x = LabDeviceStatus{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabDeviceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabDeviceStatus) ProtoMessage() {}

func (x *LabDeviceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabDeviceStatus.ProtoReflect.Descriptor instead.
func (*LabDeviceStatus) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{10}
}

func (x *LabDeviceStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LabDeviceStatus) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *LabDeviceStatus) GetCpuMillicores() int64 {
	if x != nil {
		return x.CpuMillicores
	}
	return 0
}

func (x *LabDeviceStatus) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *LabDeviceStatus) GetUsageAvailable() bool {
	if x != nil {
		return x.UsageAvailable
	}
	return false
}

func (x *LabDeviceStatus) GetCpuRequestMillicores() int64 {
	if x != nil {
		return x.CpuRequestMillicores
	}
	return 0
}

func (x *LabDeviceStatus) GetMemoryRequestBytes() int64 {
	if x != nil {
		return x.MemoryRequestBytes
	}
	return 0
}

func (x *LabDeviceStatus) GetCpuLimitMillicores() int64 {
	if x != nil {
		return x.CpuLimitMillicores
	}
	return 0
}

func (x *LabDeviceStatus) GetMemoryLimitBytes() int64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *LabDeviceStatus) GetPodPhase() string {
	if x != nil {
		return x.PodPhase
	}
	return ""
}

func (x *LabDeviceStatus) GetPodReason() string {
	if x != nil {
		return x.PodReason
	}
	return ""
}

func (x *LabDeviceStatus) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

type LabConnectionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ready         bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabConnectionStatus) Reset() {
	*x = LabConnectionStatus{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabConnectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabConnectionStatus) ProtoMessage() {}

func (x *LabConnectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabConnectionStatus.ProtoReflect.Descriptor instead.
func (*LabConnectionStatus) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{11}
}

func (x *LabConnectionStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LabConnectionStatus) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type LabAccessEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabAccessEntry) Reset() {
	*x = LabAccessEntry{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabAccessEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabAccessEntry) ProtoMessage() {}

func (x *LabAccessEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabAccessEntry.ProtoReflect.Descriptor instead.
func (*LabAccessEntry) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{12}
}

func (x *LabAccessEntry) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *LabAccessEntry) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *LabAccessEntry) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *LabAccessEntry) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type LabList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Lab                 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabList) Reset() {
	*x = LabList{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabList) ProtoMessage() {}

func (x *LabList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabList.ProtoReflect.Descriptor instead.
func (*LabList) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{13}
}

func (x *LabList) GetItems() []*Lab {
	if x != nil {
		return x.Items
	}
	return nil
}

type LabGroupClient struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Status    *LabGroupClientStatus  `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// Populated only by monitoring; CRUD callers resolve group scope themselves.
	LabGroupName  string `protobuf:"bytes,5,opt,name=lab_group_name,json=labGroupName,proto3" json:"lab_group_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabGroupClient) Reset() {
	*x = LabGroupClient{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabGroupClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabGroupClient) ProtoMessage() {}

func (x *LabGroupClient) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabGroupClient.ProtoReflect.Descriptor instead.
func (*LabGroupClient) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{14}
}

func (x *LabGroupClient) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LabGroupClient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LabGroupClient) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *LabGroupClient) GetStatus() *LabGroupClientStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *LabGroupClient) GetLabGroupName() string {
	if x != nil {
		return x.LabGroupName
	}
	return ""
}

type LabGroupClientStatus struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	AssignedIp string                 `protobuf:"bytes,1,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"`
	Ready      bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	// Assembled WireGuard client config. On CreateLabGroupClient the agent fills
	// in the real private key it generated; on Get it carries the placeholder
	// (the cluster never holds the private key).
	Config        string                    `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Statistics    *LabGroupClientStatistics `protobuf:"bytes,5,opt,name=statistics,proto3" json:"statistics,omitempty"` // live WireGuard peer stats (bytes + handshake)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabGroupClientStatus) Reset() {
	*x = LabGroupClientStatus{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabGroupClientStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabGroupClientStatus) ProtoMessage() {}

func (x *LabGroupClientStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabGroupClientStatus.ProtoReflect.Descriptor instead.
func (*LabGroupClientStatus) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{15}
}

func (x *LabGroupClientStatus) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}

func (x *LabGroupClientStatus) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *LabGroupClientStatus) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *LabGroupClientStatus) GetStatistics() *LabGroupClientStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

// LabGroupClientStatistics mirrors the CRD status the VPN server writes per peer.
// WireGuard natively exposes transfer bytes + last handshake only (no packet counts).
type LabGroupClientStatistics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LastHandshakeUnix int64                  `protobuf:"varint,1,opt,name=last_handshake_unix,json=lastHandshakeUnix,proto3" json:"last_handshake_unix,omitempty"` // unix seconds; 0 = never handshaked
	RxBytes           int64                  `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes           int64                  `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LabGroupClientStatistics) Reset() {
	*x = LabGroupClientStatistics{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabGroupClientStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabGroupClientStatistics) ProtoMessage() {}

func (x *LabGroupClientStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabGroupClientStatistics.ProtoReflect.Descriptor instead.
func (*LabGroupClientStatistics) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{16}
}

func (x *LabGroupClientStatistics) GetLastHandshakeUnix() int64 {
	if x != nil {
		return x.LastHandshakeUnix
	}
	return 0
}

func (x *LabGroupClientStatistics) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *LabGroupClientStatistics) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

type LabGroupClientList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LabGroupClient      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabGroupClientList) Reset() {
	*x = LabGroupClientList{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabGroupClientList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabGroupClientList) ProtoMessage() {}

func (x *LabGroupClientList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabGroupClientList.ProtoReflect.Descriptor instead.
func (*LabGroupClientList) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{17}
}

func (x *LabGroupClientList) GetItems() []*LabGroupClient {
	if x != nil {
		return x.Items
	}
	return nil
}

type LabGroupAccessPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The agent resolves the namespace from this LabGroup, preventing a caller
	// from applying a policy to a namespace outside the group.
	LabGroupName string                      `protobuf:"bytes,1,opt,name=lab_group_name,json=labGroupName,proto3" json:"lab_group_name,omitempty"`
	Rules        []*LabGroupAccessRule       `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	Status       *LabGroupAccessPolicyStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// Populated only by monitoring; mutations resolve scope from LabGroup name.
	Namespace     string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabGroupAccessPolicy) Reset() {
	*x = LabGroupAccessPolicy{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabGroupAccessPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabGroupAccessPolicy) ProtoMessage() {}

func (x *LabGroupAccessPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabGroupAccessPolicy.ProtoReflect.Descriptor instead.
func (*LabGroupAccessPolicy) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{18}
}

func (x *LabGroupAccessPolicy) GetLabGroupName() string {
	if x != nil {
		return x.LabGroupName
	}
	return ""
}

func (x *LabGroupAccessPolicy) GetRules() []*LabGroupAccessRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *LabGroupAccessPolicy) GetStatus() *LabGroupAccessPolicyStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *LabGroupAccessPolicy) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type LabGroupAccessRule struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Action LabGroupAccessAction   `protobuf:"varint,1,opt,name=action,proto3,enum=labmanager.LabGroupAccessAction" json:"action,omitempty"`
	// Empty means every VPN client in the LabGroup.
	ClientNames []string `protobuf:"bytes,2,rep,name=client_names,json=clientNames,proto3" json:"client_names,omitempty"`
	// Empty means every Lab in the LabGroup.
	LabNames      []string `protobuf:"bytes,3,rep,name=lab_names,json=labNames,proto3" json:"lab_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabGroupAccessRule) Reset() {
	*x = LabGroupAccessRule{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabGroupAccessRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabGroupAccessRule) ProtoMessage() {}

func (x *LabGroupAccessRule) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabGroupAccessRule.ProtoReflect.Descriptor instead.
func (*LabGroupAccessRule) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{19}
}

func (x *LabGroupAccessRule) GetAction() LabGroupAccessAction {
	if x != nil {
		return x.Action
	}
	return LabGroupAccessAction_LAB_GROUP_ACCESS_ACTION_UNSPECIFIED
}

func (x *LabGroupAccessRule) GetClientNames() []string {
	if x != nil {
		return x.ClientNames
	}
	return nil
}

func (x *LabGroupAccessRule) GetLabNames() []string {
	if x != nil {
		return x.LabNames
	}
	return nil
}

type LabGroupAccessPolicyStatus struct {
	state              protoimpl.MessageState          `protogen:"open.v1"`
	ObservedGeneration int64                           `protobuf:"varint,1,opt,name=observed_generation,json=observedGeneration,proto3" json:"observed_generation,omitempty"`
	State              string                          `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	AppliedAtUnixMs    int64                           `protobuf:"varint,3,opt,name=applied_at_unix_ms,json=appliedAtUnixMs,proto3" json:"applied_at_unix_ms,omitempty"`
	LastError          string                          `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Rules              []*LabGroupAccessRuleStatistics `protobuf:"bytes,5,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LabGroupAccessPolicyStatus) Reset() {
	*x = LabGroupAccessPolicyStatus{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabGroupAccessPolicyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabGroupAccessPolicyStatus) ProtoMessage() {}

func (x *LabGroupAccessPolicyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabGroupAccessPolicyStatus.ProtoReflect.Descriptor instead.
func (*LabGroupAccessPolicyStatus) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{20}
}

func (x *LabGroupAccessPolicyStatus) GetObservedGeneration() int64 {
	if x != nil {
		return x.ObservedGeneration
	}
	return 0
}

func (x *LabGroupAccessPolicyStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *LabGroupAccessPolicyStatus) GetAppliedAtUnixMs() int64 {
	if x != nil {
		return x.AppliedAtUnixMs
	}
	return 0
}

func (x *LabGroupAccessPolicyStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *LabGroupAccessPolicyStatus) GetRules() []*LabGroupAccessRuleStatistics {
	if x != nil {
		return x.Rules
	}
	return nil
}

type LabGroupAccessRuleStatistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientName    string                 `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	LabName       string                 `protobuf:"bytes,2,opt,name=lab_name,json=labName,proto3" json:"lab_name,omitempty"`
	Action        LabGroupAccessAction   `protobuf:"varint,3,opt,name=action,proto3,enum=labmanager.LabGroupAccessAction" json:"action,omitempty"`
	Packets       int64                  `protobuf:"varint,4,opt,name=packets,proto3" json:"packets,omitempty"`
	Bytes         int64                  `protobuf:"varint,5,opt,name=bytes,proto3" json:"bytes,omitempty"`
	CounterReset  bool                   `protobuf:"varint,6,opt,name=counter_reset,json=counterReset,proto3" json:"counter_reset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabGroupAccessRuleStatistics) Reset() {
	*x = LabGroupAccessRuleStatistics{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabGroupAccessRuleStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabGroupAccessRuleStatistics) ProtoMessage() {}

func (x *LabGroupAccessRuleStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabGroupAccessRuleStatistics.ProtoReflect.Descriptor instead.
func (*LabGroupAccessRuleStatistics) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{21}
}

func (x *LabGroupAccessRuleStatistics) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *LabGroupAccessRuleStatistics) GetLabName() string {
	if x != nil {
		return x.LabName
	}
	return ""
}

func (x *LabGroupAccessRuleStatistics) GetAction() LabGroupAccessAction {
	if x != nil {
		return x.Action
	}
	return LabGroupAccessAction_LAB_GROUP_ACCESS_ACTION_UNSPECIFIED
}

func (x *LabGroupAccessRuleStatistics) GetPackets() int64 {
	if x != nil {
		return x.Packets
	}
	return 0
}

func (x *LabGroupAccessRuleStatistics) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *LabGroupAccessRuleStatistics) GetCounterReset() bool {
	if x != nil {
		return x.CounterReset
	}
	return false
}

type MonitoringRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The agent bounds this to protect the Kubernetes API from a too-fast caller.
	MinIntervalMs int64 `protobuf:"varint,1,opt,name=min_interval_ms,json=minIntervalMs,proto3" json:"min_interval_ms,omitempty"`
	// Reserved for a future resumable agent journal. Current agents always send
	// a new snapshot on connection/reconnection.
	ResumeAfterSequence int64 `protobuf:"varint,2,opt,name=resume_after_sequence,json=resumeAfterSequence,proto3" json:"resume_after_sequence,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MonitoringRequest) Reset() {
	*x = MonitoringRequest{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringRequest) ProtoMessage() {}

func (x *MonitoringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringRequest.ProtoReflect.Descriptor instead.
func (*MonitoringRequest) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{22}
}

func (x *MonitoringRequest) GetMinIntervalMs() int64 {
	if x != nil {
		return x.MinIntervalMs
	}
	return 0
}

func (x *MonitoringRequest) GetResumeAfterSequence() int64 {
	if x != nil {
		return x.ResumeAfterSequence
	}
	return 0
}

type MonitoringDeletedKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	LabGroupName  string                 `protobuf:"bytes,2,opt,name=lab_group_name,json=labGroupName,proto3" json:"lab_group_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoringDeletedKey) Reset() {
	*x = MonitoringDeletedKey{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringDeletedKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringDeletedKey) ProtoMessage() {}

func (x *MonitoringDeletedKey) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringDeletedKey.ProtoReflect.Descriptor instead.
func (*MonitoringDeletedKey) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{23}
}

func (x *MonitoringDeletedKey) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MonitoringDeletedKey) GetLabGroupName() string {
	if x != nil {
		return x.LabGroupName
	}
	return ""
}

func (x *MonitoringDeletedKey) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MonitoringDeletedKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MonitoringUpdate struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	AgentId          string                  `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Sequence         int64                   `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ObservedAtUnixMs int64                   `protobuf:"varint,3,opt,name=observed_at_unix_ms,json=observedAtUnixMs,proto3" json:"observed_at_unix_ms,omitempty"`
	SchemaVersion    uint32                  `protobuf:"varint,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Snapshot         bool                    `protobuf:"varint,5,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Groups           []*LabGroup             `protobuf:"bytes,10,rep,name=groups,proto3" json:"groups,omitempty"`
	Labs             []*Lab                  `protobuf:"bytes,11,rep,name=labs,proto3" json:"labs,omitempty"`
	Clients          []*LabGroupClient       `protobuf:"bytes,12,rep,name=clients,proto3" json:"clients,omitempty"`
	DeletedKeys      []*MonitoringDeletedKey `protobuf:"bytes,13,rep,name=deleted_keys,json=deletedKeys,proto3" json:"deleted_keys,omitempty"`
	Policies         []*LabGroupAccessPolicy `protobuf:"bytes,14,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MonitoringUpdate) Reset() {
	*x = MonitoringUpdate{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringUpdate) ProtoMessage() {}

func (x *MonitoringUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringUpdate.ProtoReflect.Descriptor instead.
func (*MonitoringUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{24}
}

func (x *MonitoringUpdate) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MonitoringUpdate) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MonitoringUpdate) GetObservedAtUnixMs() int64 {
	if x != nil {
		return x.ObservedAtUnixMs
	}
	return 0
}

func (x *MonitoringUpdate) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *MonitoringUpdate) GetSnapshot() bool {
	if x != nil {
		return x.Snapshot
	}
	return false
}

func (x *MonitoringUpdate) GetGroups() []*LabGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *MonitoringUpdate) GetLabs() []*Lab {
	if x != nil {
		return x.Labs
	}
	return nil
}

func (x *MonitoringUpdate) GetClients() []*LabGroupClient {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *MonitoringUpdate) GetDeletedKeys() []*MonitoringDeletedKey {
	if x != nil {
		return x.DeletedKeys
	}
	return nil
}

func (x *MonitoringUpdate) GetPolicies() []*LabGroupAccessPolicy {
	if x != nil {
		return x.Policies
	}
	return nil
}

// NodeCapacity reports a node's allocatable resources and how much is already
// requested by scheduled pods, so a caller can compute remaining headroom.
type NodeCapacity struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Name                     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AllocatableCpuMillicores int64                  `protobuf:"varint,2,opt,name=allocatable_cpu_millicores,json=allocatableCpuMillicores,proto3" json:"allocatable_cpu_millicores,omitempty"`
	AllocatableMemoryBytes   int64                  `protobuf:"varint,3,opt,name=allocatable_memory_bytes,json=allocatableMemoryBytes,proto3" json:"allocatable_memory_bytes,omitempty"`
	RequestedCpuMillicores   int64                  `protobuf:"varint,4,opt,name=requested_cpu_millicores,json=requestedCpuMillicores,proto3" json:"requested_cpu_millicores,omitempty"` // sum of scheduled pod container requests
	RequestedMemoryBytes     int64                  `protobuf:"varint,5,opt,name=requested_memory_bytes,json=requestedMemoryBytes,proto3" json:"requested_memory_bytes,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *NodeCapacity) Reset() {
	*x = NodeCapacity{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCapacity) ProtoMessage() {}

func (x *NodeCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCapacity.ProtoReflect.Descriptor instead.
func (*NodeCapacity) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{25}
}

func (x *NodeCapacity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeCapacity) GetAllocatableCpuMillicores() int64 {
	if x != nil {
		return x.AllocatableCpuMillicores
	}
	return 0
}

func (x *NodeCapacity) GetAllocatableMemoryBytes() int64 {
	if x != nil {
		return x.AllocatableMemoryBytes
	}
	return 0
}

func (x *NodeCapacity) GetRequestedCpuMillicores() int64 {
	if x != nil {
		return x.RequestedCpuMillicores
	}
	return 0
}

func (x *NodeCapacity) GetRequestedMemoryBytes() int64 {
	if x != nil {
		return x.RequestedMemoryBytes
	}
	return 0
}

// CapacityResponse aggregates per-node capacity plus cluster totals. Remaining
// headroom = allocatable - requested; divide by a lab's summed device requests
// to estimate how many more labs fit.
type CapacityResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Nodes                    []*NodeCapacity        `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	AllocatableCpuMillicores int64                  `protobuf:"varint,2,opt,name=allocatable_cpu_millicores,json=allocatableCpuMillicores,proto3" json:"allocatable_cpu_millicores,omitempty"`
	AllocatableMemoryBytes   int64                  `protobuf:"varint,3,opt,name=allocatable_memory_bytes,json=allocatableMemoryBytes,proto3" json:"allocatable_memory_bytes,omitempty"`
	RequestedCpuMillicores   int64                  `protobuf:"varint,4,opt,name=requested_cpu_millicores,json=requestedCpuMillicores,proto3" json:"requested_cpu_millicores,omitempty"`
	RequestedMemoryBytes     int64                  `protobuf:"varint,5,opt,name=requested_memory_bytes,json=requestedMemoryBytes,proto3" json:"requested_memory_bytes,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CapacityResponse) Reset() {
	*x = CapacityResponse{}
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapacityResponse) ProtoMessage() {}

func (x *CapacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_agent_protobuf_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapacityResponse.ProtoReflect.Descriptor instead.
func (*CapacityResponse) Descriptor() ([]byte, []int) {
	return file_pkg_agent_protobuf_agent_proto_rawDescGZIP(), []int{26}
}

func (x *CapacityResponse) GetNodes() []*NodeCapacity {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *CapacityResponse) GetAllocatableCpuMillicores() int64 {
	if x != nil {
		return x.AllocatableCpuMillicores
	}
	return 0
}

func (x *CapacityResponse) GetAllocatableMemoryBytes() int64 {
	if x != nil {
		return x.AllocatableMemoryBytes
	}
	return 0
}

func (x *CapacityResponse) GetRequestedCpuMillicores() int64 {
	if x != nil {
		return x.RequestedCpuMillicores
	}
	return 0
}

func (x *CapacityResponse) GetRequestedMemoryBytes() int64 {
	if x != nil {
		return x.RequestedMemoryBytes
	}
	return 0
}

var File_pkg_agent_protobuf_agent_proto protoreflect.FileDescriptor

const file_pkg_agent_protobuf_agent_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/agent/protobuf/agent.proto\x12\n" +
	"labmanager\"\a\n" +
	"\x05Empty\"\x1f\n" +
	"\tIDRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"0\n" +
	"\x10NamespaceRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"G\n" +
	"\x13NamespacedIDRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"R\n" +
	"\bLabGroup\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x06status\x18\x02 \x01(\v2\x1a.labmanager.LabGroupStatusR\x06status\"k\n" +
	"\x0eLabGroupStatus\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12%\n" +
	"\x0evpn_registered\x18\x03 \x01(\bR\rvpnRegistered\":\n" +
	"\fLabGroupList\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.labmanager.LabGroupR\x05items\"\xd2\x01\n" +
	"\x03Lab\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tspec_json\x18\x03 \x01(\fR\bspecJson\x12-\n" +
	"\x06status\x18\x04 \x01(\v2\x15.labmanager.LabStatusR\x06status\x12'\n" +
	"\x03env\x18\x05 \x03(\v2\x15.labmanager.DeviceEnvR\x03env\x12$\n" +
	"\x0elab_group_name\x18\x06 \x01(\tR\flabGroupName\"\x91\x01\n" +
	"\tDeviceEnv\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x123\n" +
	"\x04vars\x18\x02 \x03(\v2\x1f.labmanager.DeviceEnv.VarsEntryR\x04vars\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x03\n" +
	"\tLabStatus\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x19\n" +
	"\bvpn_cidr\x18\x02 \x01(\tR\avpnCidr\x12#\n" +
	"\rinternet_cidr\x18\x03 \x01(\tR\finternetCidr\x12\x14\n" +
	"\x05ready\x18\x04 \x01(\bR\x05ready\x12\x1f\n" +
	"\vaccess_urls\x18\x05 \x03(\tR\n" +
	"accessUrls\x12\x1b\n" +
	"\tvpn_ready\x18\x06 \x01(\bR\bvpnReady\x12%\n" +
	"\x0einternet_ready\x18\a \x01(\bR\rinternetReady\x125\n" +
	"\adevices\x18\b \x03(\v2\x1b.labmanager.LabDeviceStatusR\adevices\x12A\n" +
	"\vconnections\x18\t \x03(\v2\x1f.labmanager.LabConnectionStatusR\vconnections\x122\n" +
	"\x06access\x18\n" +
	" \x03(\v2\x1a.labmanager.LabAccessEntryR\x06access\"\xd7\x03\n" +
	"\x0fLabDeviceStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\x12%\n" +
	"\x0ecpu_millicores\x18\x03 \x01(\x03R\rcpuMillicores\x12!\n" +
	"\fmemory_bytes\x18\x04 \x01(\x03R\vmemoryBytes\x12'\n" +
	"\x0fusage_available\x18\x05 \x01(\bR\x0eusageAvailable\x124\n" +
	"\x16cpu_request_millicores\x18\x06 \x01(\x03R\x14cpuRequestMillicores\x120\n" +
	"\x14memory_request_bytes\x18\a \x01(\x03R\x12memoryRequestBytes\x120\n" +
	"\x14cpu_limit_millicores\x18\b \x01(\x03R\x12cpuLimitMillicores\x12,\n" +
	"\x12memory_limit_bytes\x18\t \x01(\x03R\x10memoryLimitBytes\x12\x1b\n" +
	"\tpod_phase\x18\n" +
	" \x01(\tR\bpodPhase\x12\x1d\n" +
	"\n" +
	"pod_reason\x18\v \x01(\tR\tpodReason\x12#\n" +
	"\rrestart_count\x18\f \x01(\x05R\frestartCount\"?\n" +
	"\x13LabConnectionStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\"j\n" +
	"\x0eLabAccessEntry\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"0\n" +
	"\aLabList\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.labmanager.LabR\x05items\"\xc1\x01\n" +
	"\x0eLabGroupClient\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x128\n" +
	"\x06status\x18\x04 \x01(\v2 .labmanager.LabGroupClientStatusR\x06status\x12$\n" +
	"\x0elab_group_name\x18\x05 \x01(\tR\flabGroupName\"\xb1\x01\n" +
	"\x14LabGroupClientStatus\x12\x1f\n" +
	"\vassigned_ip\x18\x01 \x01(\tR\n" +
	"assignedIp\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\x12\x16\n" +
	"\x06config\x18\x04 \x01(\tR\x06config\x12D\n" +
	"\n" +
	"statistics\x18\x05 \x01(\v2$.labmanager.LabGroupClientStatisticsR\n" +
	"statisticsJ\x04\b\x02\x10\x03\"\x80\x01\n" +
	"\x18LabGroupClientStatistics\x12.\n" +
	"\x13last_handshake_unix\x18\x01 \x01(\x03R\x11lastHandshakeUnix\x12\x19\n" +
	"\brx_bytes\x18\x02 \x01(\x03R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x03 \x01(\x03R\atxBytes\"F\n" +
	"\x12LabGroupClientList\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.labmanager.LabGroupClientR\x05items\"\xd0\x01\n" +
	"\x14LabGroupAccessPolicy\x12$\n" +
	"\x0elab_group_name\x18\x01 \x01(\tR\flabGroupName\x124\n" +
	"\x05rules\x18\x02 \x03(\v2\x1e.labmanager.LabGroupAccessRuleR\x05rules\x12>\n" +
	"\x06status\x18\x03 \x01(\v2&.labmanager.LabGroupAccessPolicyStatusR\x06status\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\"\x8e\x01\n" +
	"\x12LabGroupAccessRule\x128\n" +
	"\x06action\x18\x01 \x01(\x0e2 .labmanager.LabGroupAccessActionR\x06action\x12!\n" +
	"\fclient_names\x18\x02 \x03(\tR\vclientNames\x12\x1b\n" +
	"\tlab_names\x18\x03 \x03(\tR\blabNames\"\xef\x01\n" +
	"\x1aLabGroupAccessPolicyStatus\x12/\n" +
	"\x13observed_generation\x18\x01 \x01(\x03R\x12observedGeneration\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12+\n" +
	"\x12applied_at_unix_ms\x18\x03 \x01(\x03R\x0fappliedAtUnixMs\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\x12>\n" +
	"\x05rules\x18\x05 \x03(\v2(.labmanager.LabGroupAccessRuleStatisticsR\x05rules\"\xe9\x01\n" +
	"\x1cLabGroupAccessRuleStatistics\x12\x1f\n" +
	"\vclient_name\x18\x01 \x01(\tR\n" +
	"clientName\x12\x19\n" +
	"\blab_name\x18\x02 \x01(\tR\alabName\x128\n" +
	"\x06action\x18\x03 \x01(\x0e2 .labmanager.LabGroupAccessActionR\x06action\x12\x18\n" +
	"\apackets\x18\x04 \x01(\x03R\apackets\x12\x14\n" +
	"\x05bytes\x18\x05 \x01(\x03R\x05bytes\x12#\n" +
	"\rcounter_reset\x18\x06 \x01(\bR\fcounterReset\"o\n" +
	"\x11MonitoringRequest\x12&\n" +
	"\x0fmin_interval_ms\x18\x01 \x01(\x03R\rminIntervalMs\x122\n" +
	"\x15resume_after_sequence\x18\x02 \x01(\x03R\x13resumeAfterSequence\"\x82\x01\n" +
	"\x14MonitoringDeletedKey\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12$\n" +
	"\x0elab_group_name\x18\x02 \x01(\tR\flabGroupName\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\xc7\x03\n" +
	"\x10MonitoringUpdate\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12-\n" +
	"\x13observed_at_unix_ms\x18\x03 \x01(\x03R\x10observedAtUnixMs\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\rR\rschemaVersion\x12\x1a\n" +
	"\bsnapshot\x18\x05 \x01(\bR\bsnapshot\x12,\n" +
	"\x06groups\x18\n" +
	" \x03(\v2\x14.labmanager.LabGroupR\x06groups\x12#\n" +
	"\x04labs\x18\v \x03(\v2\x0f.labmanager.LabR\x04labs\x124\n" +
	"\aclients\x18\f \x03(\v2\x1a.labmanager.LabGroupClientR\aclients\x12C\n" +
	"\fdeleted_keys\x18\r \x03(\v2 .labmanager.MonitoringDeletedKeyR\vdeletedKeys\x12<\n" +
	"\bpolicies\x18\x0e \x03(\v2 .labmanager.LabGroupAccessPolicyR\bpolicies\"\x8a\x02\n" +
	"\fNodeCapacity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\x1aallocatable_cpu_millicores\x18\x02 \x01(\x03R\x18allocatableCpuMillicores\x128\n" +
	"\x18allocatable_memory_bytes\x18\x03 \x01(\x03R\x16allocatableMemoryBytes\x128\n" +
	"\x18requested_cpu_millicores\x18\x04 \x01(\x03R\x16requestedCpuMillicores\x124\n" +
	"\x16requested_memory_bytes\x18\x05 \x01(\x03R\x14requestedMemoryBytes\"\xaa\x02\n" +
	"\x10CapacityResponse\x12.\n" +
	"\x05nodes\x18\x01 \x03(\v2\x18.labmanager.NodeCapacityR\x05nodes\x12<\n" +
	"\x1aallocatable_cpu_millicores\x18\x02 \x01(\x03R\x18allocatableCpuMillicores\x128\n" +
	"\x18allocatable_memory_bytes\x18\x03 \x01(\x03R\x16allocatableMemoryBytes\x128\n" +
	"\x18requested_cpu_millicores\x18\x04 \x01(\x03R\x16requestedCpuMillicores\x124\n" +
	"\x16requested_memory_bytes\x18\x05 \x01(\x03R\x14requestedMemoryBytes*\x84\x01\n" +
	"\x14LabGroupAccessAction\x12'\n" +
	"#LAB_GROUP_ACCESS_ACTION_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dLAB_GROUP_ACCESS_ACTION_ALLOW\x10\x01\x12 \n" +
	"\x1cLAB_GROUP_ACCESS_ACTION_DENY\x10\x022\xca\t\n" +
	"\n" +
	"LabManager\x12.\n" +
	"\x04Ping\x12\x11.labmanager.Empty\x1a\x11.labmanager.Empty\"\x00\x12>\n" +
	"\x0eCreateLabGroup\x12\x14.labmanager.LabGroup\x1a\x14.labmanager.LabGroup\"\x00\x12<\n" +
	"\vGetLabGroup\x12\x15.labmanager.IDRequest\x1a\x14.labmanager.LabGroup\"\x00\x12>\n" +
	"\rListLabGroups\x12\x11.labmanager.Empty\x1a\x18.labmanager.LabGroupList\"\x00\x12>\n" +
	"\x0eUpdateLabGroup\x12\x14.labmanager.LabGroup\x1a\x14.labmanager.LabGroup\"\x00\x12<\n" +
	"\x0eDeleteLabGroup\x12\x15.labmanager.IDRequest\x1a\x11.labmanager.Empty\"\x00\x12/\n" +
	"\tCreateLab\x12\x0f.labmanager.Lab\x1a\x0f.labmanager.Lab\"\x00\x12<\n" +
	"\x06GetLab\x12\x1f.labmanager.NamespacedIDRequest\x1a\x0f.labmanager.Lab\"\x00\x12?\n" +
	"\bListLabs\x12\x1c.labmanager.NamespaceRequest\x1a\x13.labmanager.LabList\"\x00\x12/\n" +
	"\tUpdateLab\x12\x0f.labmanager.Lab\x1a\x0f.labmanager.Lab\"\x00\x12A\n" +
	"\tDeleteLab\x12\x1f.labmanager.NamespacedIDRequest\x1a\x11.labmanager.Empty\"\x00\x12P\n" +
	"\x14CreateLabGroupClient\x12\x1a.labmanager.LabGroupClient\x1a\x1a.labmanager.LabGroupClient\"\x00\x12R\n" +
	"\x11GetLabGroupClient\x12\x1f.labmanager.NamespacedIDRequest\x1a\x1a.labmanager.LabGroupClient\"\x00\x12U\n" +
	"\x13ListLabGroupClients\x12\x1c.labmanager.NamespaceRequest\x1a\x1e.labmanager.LabGroupClientList\"\x00\x12L\n" +
	"\x14DeleteLabGroupClient\x12\x1f.labmanager.NamespacedIDRequest\x1a\x11.labmanager.Empty\"\x00\x12P\n" +
	"\x17ReconcileLabGroupAccess\x12 .labmanager.LabGroupAccessPolicy\x1a\x11.labmanager.Empty\"\x00\x12M\n" +
	"\n" +
	"Monitoring\x12\x1d.labmanager.MonitoringRequest\x1a\x1c.labmanager.MonitoringUpdate\"\x000\x01\x12@\n" +
	"\vGetCapacity\x12\x11.labmanager.Empty\x1a\x1c.labmanager.CapacityResponse\"\x00B6Z4github.com/cybericebox/laboratory/pkg/agent/protobufb\x06proto3"

var (
	file_pkg_agent_protobuf_agent_proto_rawDescOnce sync.Once
	file_pkg_agent_protobuf_agent_proto_rawDescData []byte
)

func file_pkg_agent_protobuf_agent_proto_rawDescGZIP() []byte {
	file_pkg_agent_protobuf_agent_proto_rawDescOnce.Do(func() {
		file_pkg_agent_protobuf_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_agent_protobuf_agent_proto_rawDesc), len(file_pkg_agent_protobuf_agent_proto_rawDesc)))
	})
	return file_pkg_agent_protobuf_agent_proto_rawDescData
}

var file_pkg_agent_protobuf_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_agent_protobuf_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_pkg_agent_protobuf_agent_proto_goTypes = []any{
	(LabGroupAccessAction)(0),            // 0: labmanager.LabGroupAccessAction
	(*Empty)(nil),                        // 1: labmanager.Empty
	(*IDRequest)(nil),                    // 2: labmanager.IDRequest
	(*NamespaceRequest)(nil),             // 3: labmanager.NamespaceRequest
	(*NamespacedIDRequest)(nil),          // 4: labmanager.NamespacedIDRequest
	(*LabGroup)(nil),                     // 5: labmanager.LabGroup
	(*LabGroupStatus)(nil),               // 6: labmanager.LabGroupStatus
	(*LabGroupList)(nil),                 // 7: labmanager.LabGroupList
	(*Lab)(nil),                          // 8: labmanager.Lab
	(*DeviceEnv)(nil),                    // 9: labmanager.DeviceEnv
	(*LabStatus)(nil),                    // 10: labmanager.LabStatus
	(*LabDeviceStatus)(nil),              // 11: labmanager.LabDeviceStatus
	(*LabConnectionStatus)(nil),          // 12: labmanager.LabConnectionStatus
	(*LabAccessEntry)(nil),               // 13: labmanager.LabAccessEntry
	(*LabList)(nil),                      // 14: labmanager.LabList
	(*LabGroupClient)(nil),               // 15: labmanager.LabGroupClient
	(*LabGroupClientStatus)(nil),         // 16: labmanager.LabGroupClientStatus
	(*LabGroupClientStatistics)(nil),     // 17: labmanager.LabGroupClientStatistics
	(*LabGroupClientList)(nil),           // 18: labmanager.LabGroupClientList
	(*LabGroupAccessPolicy)(nil),         // 19: labmanager.LabGroupAccessPolicy
	(*LabGroupAccessRule)(nil),           // 20: labmanager.LabGroupAccessRule
	(*LabGroupAccessPolicyStatus)(nil),   // 21: labmanager.LabGroupAccessPolicyStatus
	(*LabGroupAccessRuleStatistics)(nil), // 22: labmanager.LabGroupAccessRuleStatistics
	(*MonitoringRequest)(nil),            // 23: labmanager.MonitoringRequest
	(*MonitoringDeletedKey)(nil),         // 24: labmanager.MonitoringDeletedKey
	(*MonitoringUpdate)(nil),             // 25: labmanager.MonitoringUpdate
	(*NodeCapacity)(nil),                 // 26: labmanager.NodeCapacity
	(*CapacityResponse)(nil),             // 27: labmanager.CapacityResponse
	nil,                                  // 28: labmanager.DeviceEnv.VarsEntry
}
var file_pkg_agent_protobuf_agent_proto_depIdxs = []int32{
	6,  // 0: labmanager.LabGroup.status:type_name -> labmanager.LabGroupStatus
	5,  // 1: labmanager.LabGroupList.items:type_name -> labmanager.LabGroup
	10, // 2: labmanager.Lab.status:type_name -> labmanager.LabStatus
	9,  // 3: labmanager.Lab.env:type_name -> labmanager.DeviceEnv
	28, // 4: labmanager.DeviceEnv.vars:type_name -> labmanager.DeviceEnv.VarsEntry
	11, // 5: labmanager.LabStatus.devices:type_name -> labmanager.LabDeviceStatus
	12, // 6: labmanager.LabStatus.connections:type_name -> labmanager.LabConnectionStatus
	13, // 7: labmanager.LabStatus.access:type_name -> labmanager.LabAccessEntry
	8,  // 8: labmanager.LabList.items:type_name -> labmanager.Lab
	16, // 9: labmanager.LabGroupClient.status:type_name -> labmanager.LabGroupClientStatus
	17, // 10: labmanager.LabGroupClientStatus.statistics:type_name -> labmanager.LabGroupClientStatistics
	15, // 11: labmanager.LabGroupClientList.items:type_name -> labmanager.LabGroupClient
	20, // 12: labmanager.LabGroupAccessPolicy.rules:type_name -> labmanager.LabGroupAccessRule
	21, // 13: labmanager.LabGroupAccessPolicy.status:type_name -> labmanager.LabGroupAccessPolicyStatus
	0,  // 14: labmanager.LabGroupAccessRule.action:type_name -> labmanager.LabGroupAccessAction
	22, // 15: labmanager.LabGroupAccessPolicyStatus.rules:type_name -> labmanager.LabGroupAccessRuleStatistics
	0,  // 16: labmanager.LabGroupAccessRuleStatistics.action:type_name -> labmanager.LabGroupAccessAction
	5,  // 17: labmanager.MonitoringUpdate.groups:type_name -> labmanager.LabGroup
	8,  // 18: labmanager.MonitoringUpdate.labs:type_name -> labmanager.Lab
	15, // 19: labmanager.MonitoringUpdate.clients:type_name -> labmanager.LabGroupClient
	24, // 20: labmanager.MonitoringUpdate.deleted_keys:type_name -> labmanager.MonitoringDeletedKey
	19, // 21: labmanager.MonitoringUpdate.policies:type_name -> labmanager.LabGroupAccessPolicy
	26, // 22: labmanager.CapacityResponse.nodes:type_name -> labmanager.NodeCapacity
	1,  // 23: labmanager.LabManager.Ping:input_type -> labmanager.Empty
	5,  // 24: labmanager.LabManager.CreateLabGroup:input_type -> labmanager.LabGroup
	2,  // 25: labmanager.LabManager.GetLabGroup:input_type -> labmanager.IDRequest
	1,  // 26: labmanager.LabManager.ListLabGroups:input_type -> labmanager.Empty
	5,  // 27: labmanager.LabManager.UpdateLabGroup:input_type -> labmanager.LabGroup
	2,  // 28: labmanager.LabManager.DeleteLabGroup:input_type -> labmanager.IDRequest
	8,  // 29: labmanager.LabManager.CreateLab:input_type -> labmanager.Lab
	4,  // 30: labmanager.LabManager.GetLab:input_type -> labmanager.NamespacedIDRequest
	3,  // 31: labmanager.LabManager.ListLabs:input_type -> labmanager.NamespaceRequest
	8,  // 32: labmanager.LabManager.UpdateLab:input_type -> labmanager.Lab
	4,  // 33: labmanager.LabManager.DeleteLab:input_type -> labmanager.NamespacedIDRequest
	15, // 34: labmanager.LabManager.CreateLabGroupClient:input_type -> labmanager.LabGroupClient
	4,  // 35: labmanager.LabManager.GetLabGroupClient:input_type -> labmanager.NamespacedIDRequest
	3,  // 36: labmanager.LabManager.ListLabGroupClients:input_type -> labmanager.NamespaceRequest
	4,  // 37: labmanager.LabManager.DeleteLabGroupClient:input_type -> labmanager.NamespacedIDRequest
	19, // 38: labmanager.LabManager.ReconcileLabGroupAccess:input_type -> labmanager.LabGroupAccessPolicy
	23, // 39: labmanager.LabManager.Monitoring:input_type -> labmanager.MonitoringRequest
	1,  // 40: labmanager.LabManager.GetCapacity:input_type -> labmanager.Empty
	1,  // 41: labmanager.LabManager.Ping:output_type -> labmanager.Empty
	5,  // 42: labmanager.LabManager.CreateLabGroup:output_type -> labmanager.LabGroup
	5,  // 43: labmanager.LabManager.GetLabGroup:output_type -> labmanager.LabGroup
	7,  // 44: labmanager.LabManager.ListLabGroups:output_type -> labmanager.LabGroupList
	5,  // 45: labmanager.LabManager.UpdateLabGroup:output_type -> labmanager.LabGroup
	1,  // 46: labmanager.LabManager.DeleteLabGroup:output_type -> labmanager.Empty
	8,  // 47: labmanager.LabManager.CreateLab:output_type -> labmanager.Lab
	8,  // 48: labmanager.LabManager.GetLab:output_type -> labmanager.Lab
	14, // 49: labmanager.LabManager.ListLabs:output_type -> labmanager.LabList
	8,  // 50: labmanager.LabManager.UpdateLab:output_type -> labmanager.Lab
	1,  // 51: labmanager.LabManager.DeleteLab:output_type -> labmanager.Empty
	15, // 52: labmanager.LabManager.CreateLabGroupClient:output_type -> labmanager.LabGroupClient
	15, // 53: labmanager.LabManager.GetLabGroupClient:output_type -> labmanager.LabGroupClient
	18, // 54: labmanager.LabManager.ListLabGroupClients:output_type -> labmanager.LabGroupClientList
	1,  // 55: labmanager.LabManager.DeleteLabGroupClient:output_type -> labmanager.Empty
	1,  // 56: labmanager.LabManager.ReconcileLabGroupAccess:output_type -> labmanager.Empty
	25, // 57: labmanager.LabManager.Monitoring:output_type -> labmanager.MonitoringUpdate
	27, // 58: labmanager.LabManager.GetCapacity:output_type -> labmanager.CapacityResponse
	41, // [41:59] is the sub-list for method output_type
	23, // [23:41] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_pkg_agent_protobuf_agent_proto_init() }
func file_pkg_agent_protobuf_agent_proto_init() {
	if File_pkg_agent_protobuf_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_agent_protobuf_agent_proto_rawDesc), len(file_pkg_agent_protobuf_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_agent_protobuf_agent_proto_goTypes,
		DependencyIndexes: file_pkg_agent_protobuf_agent_proto_depIdxs,
		EnumInfos:         file_pkg_agent_protobuf_agent_proto_enumTypes,
		MessageInfos:      file_pkg_agent_protobuf_agent_proto_msgTypes,
	}.Build()
	File_pkg_agent_protobuf_agent_proto = out.File
	file_pkg_agent_protobuf_agent_proto_goTypes = nil
	file_pkg_agent_protobuf_agent_proto_depIdxs = nil
}
