/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apilaboratoryv1alpha1 "github.com/cybericebox/laboratory/api/laboratory/v1alpha1"
	versioned "github.com/cybericebox/laboratory/clientset/client/versioned"
	internalinterfaces "github.com/cybericebox/laboratory/clientset/informers/externalversions/internalinterfaces"
	laboratoryv1alpha1 "github.com/cybericebox/laboratory/clientset/listers/laboratory/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// LabTrafficReportInformer provides access to a shared informer and lister for
// LabTrafficReports. Prefer using the type-safe variant (see [TypedLabTrafficReportInformer]).
type LabTrafficReportInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() laboratoryv1alpha1.LabTrafficReportLister
}

// TypedLabTrafficReportInformer provides access to a shared informer and lister for
// LabTrafficReports, including the type-safe TypedInformer variant.
// It is a superset of LabTrafficReportInformer.
type TypedLabTrafficReportInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() LabTrafficReportIndexInformer
	Lister() laboratoryv1alpha1.LabTrafficReportLister
}

// LabTrafficReportIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type LabTrafficReportIndexInformer cache.TypedSharedIndexInformer[*apilaboratoryv1alpha1.LabTrafficReport]

// LabTrafficReportHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for LabTrafficReport.
type LabTrafficReportHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apilaboratoryv1alpha1.LabTrafficReport]

// LabTrafficReportDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for LabTrafficReport.
type LabTrafficReportDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apilaboratoryv1alpha1.LabTrafficReport]

// LabTrafficReportFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for LabTrafficReport.
type LabTrafficReportFilteringHandler = cache.TypedFilteringResourceEventHandler[*apilaboratoryv1alpha1.LabTrafficReport]

// LabTrafficReportIndexers is a specialization of [cache.TypedIndexers] for LabTrafficReport.
type LabTrafficReportIndexers = cache.TypedIndexers[*apilaboratoryv1alpha1.LabTrafficReport]

// DeletedLabTrafficReport is a specialization of [cache.DeletedObject] for LabTrafficReport.
type DeletedLabTrafficReport = cache.DeletedObject[*apilaboratoryv1alpha1.LabTrafficReport]

type labTrafficReportInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewLabTrafficReportInformer constructs a new informer for LabTrafficReport type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedLabTrafficReportInformer]).
func NewLabTrafficReportInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewLabTrafficReportInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedLabTrafficReportInformer constructs a new informer for LabTrafficReport type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedLabTrafficReportInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers LabTrafficReportIndexers) LabTrafficReportIndexInformer {
	return NewTypedLabTrafficReportInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredLabTrafficReportInformer constructs a new informer for LabTrafficReport type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredLabTrafficReportInformer]).
func NewFilteredLabTrafficReportInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedLabTrafficReportInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredLabTrafficReportInformer constructs a new informer for LabTrafficReport type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredLabTrafficReportInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers LabTrafficReportIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) LabTrafficReportIndexInformer {
	return NewTypedLabTrafficReportInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewLabTrafficReportInformerWithOptions constructs a new informer for LabTrafficReport type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedLabTrafficReportInformerWithOptions]).
func NewLabTrafficReportInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedLabTrafficReportInformerWithOptions(client, namespace, options)
}

// NewTypedLabTrafficReportInformerWithOptions constructs a new informer for LabTrafficReport type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedLabTrafficReportInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) LabTrafficReportIndexInformer {
	gvr := schema.GroupVersionResource{Group: "laboratory", Version: "v1alpha1", Resource: "labtrafficreports"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apilaboratoryv1alpha1.LabTrafficReport](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.LaboratoryV1alpha1().LabTrafficReports(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.LaboratoryV1alpha1().LabTrafficReports(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.LaboratoryV1alpha1().LabTrafficReports(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.LaboratoryV1alpha1().LabTrafficReports(namespace).Watch(ctx, opts)
			},
		}, client),
		&apilaboratoryv1alpha1.LabTrafficReport{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *labTrafficReportInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedLabTrafficReportInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *labTrafficReportInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *labTrafficReportInformer) TypedInformer() LabTrafficReportIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apilaboratoryv1alpha1.LabTrafficReport](f.factory.InformerFor(&apilaboratoryv1alpha1.LabTrafficReport{}, f.defaultInformer))
}

func (f *labTrafficReportInformer) Lister() laboratoryv1alpha1.LabTrafficReportLister {
	return laboratoryv1alpha1.NewLabTrafficReportLister(f.Informer().GetIndexer())
}

// ToTypedLabTrafficReportInformer converts an untyped informer into a TypedLabTrafficReportInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *LabTrafficReport. If that is not the case, calling type-safe methods of the returned
// TypedLabTrafficReportInformer leads to runtime panics. A safer alternative is to pass
// around a TypedLabTrafficReportInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedLabTrafficReportInformer(informer LabTrafficReportInformer) TypedLabTrafficReportInformer {
	if informer, ok := informer.(TypedLabTrafficReportInformer); ok {
		return informer
	}
	return &labTrafficReportTypedInformerAdapter{informer}
}

type labTrafficReportTypedInformerAdapter struct {
	LabTrafficReportInformer
}

func (a *labTrafficReportTypedInformerAdapter) TypedInformer() LabTrafficReportIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apilaboratoryv1alpha1.LabTrafficReport](a.Informer())
}

// ToLabTrafficReportIndexInformer converts an untyped informer into a LabTrafficReportIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *LabTrafficReport. If that is not the case, calling type-safe methods of the returned
// LabTrafficReportIndexInformer leads to runtime panics. A safer alternative is to pass
// around a LabTrafficReportIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToLabTrafficReportIndexInformer(informer cache.SharedIndexInformer) LabTrafficReportIndexInformer {
	if informer, ok := informer.(LabTrafficReportIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apilaboratoryv1alpha1.LabTrafficReport](informer)
}
