/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apilaboratoryv1alpha1 "github.com/cybericebox/laboratory/api/laboratory/v1alpha1"
	versioned "github.com/cybericebox/laboratory/clientset/client/versioned"
	internalinterfaces "github.com/cybericebox/laboratory/clientset/informers/externalversions/internalinterfaces"
	laboratoryv1alpha1 "github.com/cybericebox/laboratory/clientset/listers/laboratory/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MaintenanceWindowInformer provides access to a shared informer and lister for
// MaintenanceWindows. Prefer using the type-safe variant (see [TypedMaintenanceWindowInformer]).
type MaintenanceWindowInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() laboratoryv1alpha1.MaintenanceWindowLister
}

// TypedMaintenanceWindowInformer provides access to a shared informer and lister for
// MaintenanceWindows, including the type-safe TypedInformer variant.
// It is a superset of MaintenanceWindowInformer.
type TypedMaintenanceWindowInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() MaintenanceWindowIndexInformer
	Lister() laboratoryv1alpha1.MaintenanceWindowLister
}

// MaintenanceWindowIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type MaintenanceWindowIndexInformer cache.TypedSharedIndexInformer[*apilaboratoryv1alpha1.MaintenanceWindow]

// MaintenanceWindowHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for MaintenanceWindow.
type MaintenanceWindowHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apilaboratoryv1alpha1.MaintenanceWindow]

// MaintenanceWindowDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for MaintenanceWindow.
type MaintenanceWindowDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apilaboratoryv1alpha1.MaintenanceWindow]

// MaintenanceWindowFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for MaintenanceWindow.
type MaintenanceWindowFilteringHandler = cache.TypedFilteringResourceEventHandler[*apilaboratoryv1alpha1.MaintenanceWindow]

// MaintenanceWindowIndexers is a specialization of [cache.TypedIndexers] for MaintenanceWindow.
type MaintenanceWindowIndexers = cache.TypedIndexers[*apilaboratoryv1alpha1.MaintenanceWindow]

// DeletedMaintenanceWindow is a specialization of [cache.DeletedObject] for MaintenanceWindow.
type DeletedMaintenanceWindow = cache.DeletedObject[*apilaboratoryv1alpha1.MaintenanceWindow]

type maintenanceWindowInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewMaintenanceWindowInformer constructs a new informer for MaintenanceWindow type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedMaintenanceWindowInformer]).
func NewMaintenanceWindowInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewMaintenanceWindowInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedMaintenanceWindowInformer constructs a new informer for MaintenanceWindow type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedMaintenanceWindowInformer(client versioned.Interface, resyncPeriod time.Duration, indexers MaintenanceWindowIndexers) MaintenanceWindowIndexInformer {
	return NewTypedMaintenanceWindowInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredMaintenanceWindowInformer constructs a new informer for MaintenanceWindow type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredMaintenanceWindowInformer]).
func NewFilteredMaintenanceWindowInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedMaintenanceWindowInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredMaintenanceWindowInformer constructs a new informer for MaintenanceWindow type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredMaintenanceWindowInformer(client versioned.Interface, resyncPeriod time.Duration, indexers MaintenanceWindowIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) MaintenanceWindowIndexInformer {
	return NewTypedMaintenanceWindowInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewMaintenanceWindowInformerWithOptions constructs a new informer for MaintenanceWindow type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedMaintenanceWindowInformerWithOptions]).
func NewMaintenanceWindowInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedMaintenanceWindowInformerWithOptions(client, options)
}

// NewTypedMaintenanceWindowInformerWithOptions constructs a new informer for MaintenanceWindow type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedMaintenanceWindowInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) MaintenanceWindowIndexInformer {
	gvr := schema.GroupVersionResource{Group: "laboratory", Version: "v1alpha1", Resource: "maintenancewindows"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apilaboratoryv1alpha1.MaintenanceWindow](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.LaboratoryV1alpha1().MaintenanceWindows().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.LaboratoryV1alpha1().MaintenanceWindows().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.LaboratoryV1alpha1().MaintenanceWindows().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.LaboratoryV1alpha1().MaintenanceWindows().Watch(ctx, opts)
			},
		}, client),
		&apilaboratoryv1alpha1.MaintenanceWindow{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *maintenanceWindowInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedMaintenanceWindowInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *maintenanceWindowInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *maintenanceWindowInformer) TypedInformer() MaintenanceWindowIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apilaboratoryv1alpha1.MaintenanceWindow](f.factory.InformerFor(&apilaboratoryv1alpha1.MaintenanceWindow{}, f.defaultInformer))
}

func (f *maintenanceWindowInformer) Lister() laboratoryv1alpha1.MaintenanceWindowLister {
	return laboratoryv1alpha1.NewMaintenanceWindowLister(f.Informer().GetIndexer())
}

// ToTypedMaintenanceWindowInformer converts an untyped informer into a TypedMaintenanceWindowInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *MaintenanceWindow. If that is not the case, calling type-safe methods of the returned
// TypedMaintenanceWindowInformer leads to runtime panics. A safer alternative is to pass
// around a TypedMaintenanceWindowInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedMaintenanceWindowInformer(informer MaintenanceWindowInformer) TypedMaintenanceWindowInformer {
	if informer, ok := informer.(TypedMaintenanceWindowInformer); ok {
		return informer
	}
	return &maintenanceWindowTypedInformerAdapter{informer}
}

type maintenanceWindowTypedInformerAdapter struct {
	MaintenanceWindowInformer
}

func (a *maintenanceWindowTypedInformerAdapter) TypedInformer() MaintenanceWindowIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apilaboratoryv1alpha1.MaintenanceWindow](a.Informer())
}

// ToMaintenanceWindowIndexInformer converts an untyped informer into a MaintenanceWindowIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *MaintenanceWindow. If that is not the case, calling type-safe methods of the returned
// MaintenanceWindowIndexInformer leads to runtime panics. A safer alternative is to pass
// around a MaintenanceWindowIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToMaintenanceWindowIndexInformer(informer cache.SharedIndexInformer) MaintenanceWindowIndexInformer {
	if informer, ok := informer.(MaintenanceWindowIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apilaboratoryv1alpha1.MaintenanceWindow](informer)
}
