/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apilaboratoryv1alpha1 "github.com/cybericebox/laboratory/api/laboratory/v1alpha1"
	versioned "github.com/cybericebox/laboratory/clientset/client/versioned"
	internalinterfaces "github.com/cybericebox/laboratory/clientset/informers/externalversions/internalinterfaces"
	laboratoryv1alpha1 "github.com/cybericebox/laboratory/clientset/listers/laboratory/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TenantInformer provides access to a shared informer and lister for
// Tenants. Prefer using the type-safe variant (see [TypedTenantInformer]).
type TenantInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() laboratoryv1alpha1.TenantLister
}

// TypedTenantInformer provides access to a shared informer and lister for
// Tenants, including the type-safe TypedInformer variant.
// It is a superset of TenantInformer.
type TypedTenantInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() TenantIndexInformer
	Lister() laboratoryv1alpha1.TenantLister
}

// TenantIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type TenantIndexInformer cache.TypedSharedIndexInformer[*apilaboratoryv1alpha1.Tenant]

// TenantHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for Tenant.
type TenantHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apilaboratoryv1alpha1.Tenant]

// TenantDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for Tenant.
type TenantDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apilaboratoryv1alpha1.Tenant]

// TenantFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for Tenant.
type TenantFilteringHandler = cache.TypedFilteringResourceEventHandler[*apilaboratoryv1alpha1.Tenant]

// TenantIndexers is a specialization of [cache.TypedIndexers] for Tenant.
type TenantIndexers = cache.TypedIndexers[*apilaboratoryv1alpha1.Tenant]

// DeletedTenant is a specialization of [cache.DeletedObject] for Tenant.
type DeletedTenant = cache.DeletedObject[*apilaboratoryv1alpha1.Tenant]

type tenantInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewTenantInformer constructs a new informer for Tenant type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedTenantInformer]).
func NewTenantInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewTenantInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedTenantInformer constructs a new informer for Tenant type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedTenantInformer(client versioned.Interface, resyncPeriod time.Duration, indexers TenantIndexers) TenantIndexInformer {
	return NewTypedTenantInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredTenantInformer constructs a new informer for Tenant type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredTenantInformer]).
func NewFilteredTenantInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedTenantInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredTenantInformer constructs a new informer for Tenant type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredTenantInformer(client versioned.Interface, resyncPeriod time.Duration, indexers TenantIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) TenantIndexInformer {
	return NewTypedTenantInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewTenantInformerWithOptions constructs a new informer for Tenant type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedTenantInformerWithOptions]).
func NewTenantInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedTenantInformerWithOptions(client, options)
}

// NewTypedTenantInformerWithOptions constructs a new informer for Tenant type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedTenantInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) TenantIndexInformer {
	gvr := schema.GroupVersionResource{Group: "laboratory", Version: "v1alpha1", Resource: "tenants"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apilaboratoryv1alpha1.Tenant](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.LaboratoryV1alpha1().Tenants().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.LaboratoryV1alpha1().Tenants().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.LaboratoryV1alpha1().Tenants().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.LaboratoryV1alpha1().Tenants().Watch(ctx, opts)
			},
		}, client),
		&apilaboratoryv1alpha1.Tenant{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *tenantInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedTenantInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *tenantInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *tenantInformer) TypedInformer() TenantIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apilaboratoryv1alpha1.Tenant](f.factory.InformerFor(&apilaboratoryv1alpha1.Tenant{}, f.defaultInformer))
}

func (f *tenantInformer) Lister() laboratoryv1alpha1.TenantLister {
	return laboratoryv1alpha1.NewTenantLister(f.Informer().GetIndexer())
}

// ToTypedTenantInformer converts an untyped informer into a TypedTenantInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *Tenant. If that is not the case, calling type-safe methods of the returned
// TypedTenantInformer leads to runtime panics. A safer alternative is to pass
// around a TypedTenantInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedTenantInformer(informer TenantInformer) TypedTenantInformer {
	if informer, ok := informer.(TypedTenantInformer); ok {
		return informer
	}
	return &tenantTypedInformerAdapter{informer}
}

type tenantTypedInformerAdapter struct {
	TenantInformer
}

func (a *tenantTypedInformerAdapter) TypedInformer() TenantIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apilaboratoryv1alpha1.Tenant](a.Informer())
}

// ToTenantIndexInformer converts an untyped informer into a TenantIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *Tenant. If that is not the case, calling type-safe methods of the returned
// TenantIndexInformer leads to runtime panics. A safer alternative is to pass
// around a TenantIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToTenantIndexInformer(informer cache.SharedIndexInformer) TenantIndexInformer {
	if informer, ok := informer.(TenantIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apilaboratoryv1alpha1.Tenant](informer)
}
