//go:build linux

package nodeagent

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"sync"
	"testing"

	containers "github.com/containerd/containerd/api/services/containers/v1"
	task "github.com/containerd/containerd/api/types/task"
	lab "github.com/cybericebox/laboratory/api/laboratory/v1alpha1"
	"github.com/cybericebox/laboratory/internal/names"
	specs "github.com/opencontainers/runtime-spec/specs-go"
	"google.golang.org/protobuf/types/known/anypb"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
)

// Actual retirement shape: two positive initial scope declarations survive the
// current stopped writer. Initial certificates are generated by native adapters.
func retainedRetirementProducerFixture(t *testing.T) (*LifecycleReporter, client.Client, *lab.Lab) {
	t.Helper()
	o, _ := scopeProducerAdapter(t, nil, nil)
	paths := []string{}
	for _, name := range []string{"original-container", "original-sandbox", "original-pod"} {
		p := filepath.Join(o.CgroupRoot, name)
		if err := os.MkdirAll(p, 0700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(p, "cgroup.events"), []byte("populated 0\n"), 0600); err != nil {
			t.Fatal(err)
		}
		paths = append(paths, p)
	}
	old := lab.OwnedRuntimeIdentity{ScopeKind: "LabFabric", ScopeUID: "lab", OwnerUID: "lab", Namespace: "ns", LabName: "l", Generation: 1, OperationID: "initial", Revision: 1, NodeName: "node", NodeBootID: "boot", ContainerIDs: []string{"original-container", "original-sandbox"}, CgroupPaths: paths, PortKeys: []string{}, AttachmentsComplete: true}
	never := *old.DeepCopy()
	never.ScopeKind, never.ScopeUID, never.CgroupPaths = "NeverMaterialized", "device", paths[:2]
	current := *old.DeepCopy()
	current.Generation, current.OperationID, current.Revision = 2, "stop", 2
	pod := *never.DeepCopy()
	pod.ScopeKind, pod.PodUID, pod.Generation, pod.OperationID, pod.Revision = "", "original-pod", 2, "stop", 2
	now := metav1.Now()
	parent := &lab.Lab{ObjectMeta: metav1.ObjectMeta{Name: "l", Namespace: "ns", UID: "lab", Generation: 2}, Spec: lab.LabSpec{Lifecycle: &lab.LabLifecycleSpec{DesiredState: "Stopped", SnapshotMode: "Skip", OperationID: "stop", Revision: 2}}, Status: lab.LabStatus{ScopeInventory: []lab.OwnedRuntimeIdentity{old, never, current}, Lifecycle: &lab.LabLifecycleStatus{LabUID: "lab", OperationID: "stop", Revision: 2, ObservedGeneration: 2, ObservedState: "Stopped", StoppedAt: &now}, Resources: &lab.RuntimeAllocation{OperationID: "stop", Revision: 2, RuntimeState: "Released", ObservedAt: &now, ReleasedAt: &now}}}
	device := &lab.Device{ObjectMeta: metav1.ObjectMeta{Name: "d", Namespace: "ns", UID: "device", OwnerReferences: []metav1.OwnerReference{{Kind: "Lab", Name: "l", UID: "lab"}}}, Spec: lab.DeviceSpec{LabRef: "l", Name: "d", Type: lab.DeviceTypeContainer}, Status: lab.DeviceStatus{RuntimeInventory: []lab.OwnedRuntimeIdentity{pod}}}
	scheme := runtime.NewScheme()
	_ = lab.AddToScheme(scheme)
	_ = corev1.AddToScheme(scheme)
	c := fake.NewClientBuilder().WithScheme(scheme).WithStatusSubresource(&lab.Lab{}, &lab.Device{}).WithIndex(&corev1.Pod{}, "spec.nodeName", func(object client.Object) []string { return []string{object.(*corev1.Pod).Spec.NodeName} }).WithObjects(parent, device).Build()
	o.Reader = c
	// Native disappearance is observed from the retained positive original
	// inventory; an empty containerd list cannot invent that inventory.
	if err := o.writeRecord("inventory", pod, pod); err != nil {
		t.Fatal(err)
	}
	if err := o.recordObligation(pod); err != nil {
		t.Fatal(err)
	}
	for _, id := range parent.Status.ScopeInventory {
		report := o.ObserveScope(context.Background(), id)
		if report.RuntimeState != "Released" || report.Error != "" {
			t.Fatalf("prior native scope certificate fixture failed: %+v", report)
		}
		parent.Status.ScopeReports = append(parent.Status.ScopeReports, report)
	}
	device.Status.RuntimeReports = []lab.OwnedRuntimeReport{o.ObserveOwnedRuntime(context.Background(), pod)}
	if device.Status.RuntimeReports[0].RuntimeState != "Released" {
		t.Fatalf("prior current native Pod certificate fixture failed: %+v", device.Status.RuntimeReports)
	}
	device.Status.PodName, device.Status.NodeName = "original", "node"
	for _, obj := range []client.Object{parent, device} {
		if err := c.Get(context.Background(), client.ObjectKeyFromObject(obj), obj); err != nil {
			t.Fatal(err)
		}
	}
	// Reloading above obtains current resource versions; install only genuine
	// observations, retaining the original positive declaration identities.
	for _, id := range parent.Status.ScopeInventory {
		var cert lab.OwnedRuntimeReport
		if err := o.readRecord("scope-fabric-released", id, &cert); err != nil {
			t.Fatal(err)
		}
		parent.Status.ScopeReports = append(parent.Status.ScopeReports, cert)
	}
	var cert lab.OwnedRuntimeReport
	if err := o.readRecord("runtime-released", pod, &cert); err != nil {
		t.Fatal(err)
	}
	device.Status.RuntimeReports = []lab.OwnedRuntimeReport{cert}
	device.Status.PodName, device.Status.NodeName = "original", "node"
	if err := c.Status().Update(context.Background(), parent); err != nil {
		t.Fatal(err)
	}
	if err := c.Status().Update(context.Background(), device); err != nil {
		t.Fatal(err)
	}
	intent := lab.LifecycleRetirementIntent{ExpectedUID: "lab", StopOperationID: "stop", StopRevision: 2, Generation: 2, OperationID: "retire", Revision: 3, RequestedAt: metav1.Now()}
	raw, _ := json.Marshal(intent)
	parent.Annotations = map[string]string{names.AnnotationLifecycleRetirement: string(raw)}
	if err := c.Update(context.Background(), parent); err != nil {
		t.Fatal(err)
	}
	return &LifecycleReporter{Client: c, Reader: c, Observer: o}, c, parent
}

func TestRetirementHistoricalScopesNormalReporterMustRescanAllRetainedDebt(t *testing.T) {
	r, c, parent := retainedRetirementProducerFixture(t)
	if err := r.sync(context.Background()); err != nil {
		t.Fatal(err)
	}
	var got lab.Lab
	if err := c.Get(context.Background(), client.ObjectKeyFromObject(parent), &got); err != nil {
		t.Fatal(err)
	}
	if len(got.Status.ScopeReports) != 3 {
		t.Fatalf("retained history erased: %+v", got.Status.ScopeReports)
	}
	for _, report := range got.Status.ScopeReports {
		if report.RuntimeState != "Released" || report.RetirementOperationID != "retire" || report.RetirementRevision != 3 || report.RuntimeAbsentAt == nil || report.CgroupAbsentAt == nil || report.AttachmentsAbsentAt == nil {
			t.Fatalf("retained original scope did not receive genuine new retirement challenge: %+v", report)
		}
	}
	var device lab.Device
	if err := c.Get(context.Background(), client.ObjectKey{Namespace: "ns", Name: "d"}, &device); err != nil {
		t.Fatal(err)
	}
	if len(device.Status.RuntimeReports) != 1 || device.Status.RuntimeReports[0].RetirementOperationID != "retire" {
		t.Fatal("current original writer challenge was not preserved")
	}
}

func TestRetirementHistoricalScopesCannotCopyCachedACKOverLiveDebt(t *testing.T) {
	for _, mode := range []string{"populated-original", "live-original", "live-replacement"} {
		t.Run(mode, func(t *testing.T) {
			r, c, parent := retainedRetirementProducerFixture(t)
			path := parent.Status.ScopeInventory[0].CgroupPaths[0]
			if mode != "live-replacement" {
				if err := os.WriteFile(filepath.Join(path, "cgroup.events"), []byte("populated 1\n"), 0600); err != nil {
					t.Fatal(err)
				}
			}
			if mode == "live-original" {
				r.Observer.Runtime = scopeRuntimeAdapter(t, nil, &task.Process{ID: "original-container", Pid: 42, Status: task.Status_RUNNING})
			}
			if mode == "live-replacement" {
				path = filepath.Join(r.Observer.CgroupRoot, "replacement")
				if err := os.MkdirAll(path, 0700); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(filepath.Join(path, "cgroup.events"), []byte("populated 1\n"), 0600); err != nil {
					t.Fatal(err)
				}
				owner := *parent.Status.ScopeInventory[1].DeepCopy()
				owner.ScopeKind, owner.PodUID, owner.Generation, owner.OperationID, owner.Revision = "", "replacement-pod", 2, "stop", 2
				owner.ContainerIDs, owner.CgroupPaths = []string{"replacement"}, []string{path}
				if err := r.Observer.recordObligation(owner); err != nil {
					t.Fatal(err)
				}
				spec, _ := json.Marshal(specs.Spec{Linux: &specs.Linux{CgroupsPath: "replacement"}})
				item := &containers.Container{ID: "replacement", Labels: map[string]string{"io.kubernetes.pod.uid": "replacement-pod", "io.kubernetes.pod.namespace": "ns"}, Spec: &anypb.Any{TypeUrl: "types.containerd.io/opencontainers/runtime-spec/1/Spec", Value: spec}}
				r.Observer.Runtime = scopeRuntimeAdapter(t, []*containers.Container{item}, &task.Process{ID: "replacement", Pid: 43, Status: task.Status_RUNNING})
			}
			_ = r.sync(context.Background()) // failure is honest native debt, never an ACK
			var got lab.Lab
			if err := c.Get(context.Background(), client.ObjectKeyFromObject(parent), &got); err != nil {
				t.Fatal(err)
			}
			for _, report := range got.Status.ScopeReports {
				if report.RetirementOperationID == "retire" || report.RetirementRevision == 3 {
					t.Fatalf("cached certificate acknowledged live native debt: %+v", report)
				}
			}
		})
	}
}

func TestRetirementHistoricalScopesRejectChangedCurrentAuthority(t *testing.T) {
	changes := map[string]func(*lab.Lab){
		"replacement-uid":   func(l *lab.Lab) { l.UID = "replacement" },
		"new-start":         func(l *lab.Lab) { l.Spec.Lifecycle.DesiredState = "Running" },
		"operation":         func(l *lab.Lab) { l.Spec.Lifecycle.OperationID = "replacement" },
		"revision":          func(l *lab.Lab) { l.Spec.Lifecycle.Revision++ },
		"generation":        func(l *lab.Lab) { l.Generation++ },
		"stop-header":       func(l *lab.Lab) { l.Status.Lifecycle.OperationID = "replacement" },
		"stop-not-complete": func(l *lab.Lab) { l.Status.Lifecycle.ObservedState = "Unknown" },
		"unknown-resource":  func(l *lab.Lab) { l.Status.Resources.RuntimeState = "Unknown" },
		"missing-challenge": func(l *lab.Lab) { delete(l.Annotations, names.AnnotationLifecycleRetirement) },
		"required-barrier-unset": func(l *lab.Lab) {
			l.Spec.Lifecycle.SnapshotMode = "Required"
			l.Status.Lifecycle.SnapshotComplete = false
		},
		"access-unfenced": func(l *lab.Lab) { l.Spec.VPN.Enabled = true },
	}
	for name, change := range changes {
		t.Run(name, func(t *testing.T) {
			r, c, parent := retainedRetirementProducerFixture(t)
			var live lab.Lab
			if err := c.Get(context.Background(), client.ObjectKeyFromObject(parent), &live); err != nil {
				t.Fatal(err)
			}
			change(&live)
			status := live.Status.DeepCopy()
			if err := c.Update(context.Background(), &live); err != nil {
				t.Fatal(err)
			}
			live.Status = *status
			if err := c.Status().Update(context.Background(), &live); err != nil {
				t.Fatal(err)
			}
			_ = r.sync(context.Background())
			if err := c.Get(context.Background(), client.ObjectKeyFromObject(parent), &live); err != nil {
				t.Fatal(err)
			}
			for _, report := range live.Status.ScopeReports {
				if report.RetirementOperationID == "retire" {
					t.Fatal("invalid current authority received fresh retirement acknowledgement")
				}
			}
		})
	}
}

func TestRetirementHistoricalNeverRequiresExactOriginalCertificateAndOwner(t *testing.T) {
	for _, mode := range []string{"missing-certificate", "foreign-certificate", "replacement-device", "foreign-device-owner", "changed-node-boot"} {
		t.Run(mode, func(t *testing.T) {
			r, c, parent := retainedRetirementProducerFixture(t)
			id := parent.Status.ScopeInventory[1]
			switch mode {
			case "missing-certificate":
				if err := os.Remove(r.Observer.recordPath("scope-fabric-released", id)); err != nil {
					t.Fatal(err)
				}
			case "foreign-certificate":
				var cert lab.OwnedRuntimeReport
				if err := r.Observer.readRecord("scope-fabric-released", id, &cert); err != nil {
					t.Fatal(err)
				}
				cert.Identity.ContainerIDs = []string{"foreign"}
				if err := r.Observer.writeRecord("scope-fabric-released", id, cert); err != nil {
					t.Fatal(err)
				}
			case "replacement-device", "foreign-device-owner":
				var d lab.Device
				if err := c.Get(context.Background(), client.ObjectKey{Namespace: "ns", Name: "d"}, &d); err != nil {
					t.Fatal(err)
				}
				if mode == "replacement-device" {
					d.UID = "replacement"
				} else {
					d.OwnerReferences[0].UID = "foreign"
				}
				if err := c.Update(context.Background(), &d); err != nil {
					t.Fatal(err)
				}
			case "changed-node-boot":
				r.Observer.BootID = "replacement-boot"
			}
			_ = r.sync(context.Background())
			var live lab.Lab
			if err := c.Get(context.Background(), client.ObjectKeyFromObject(parent), &live); err != nil {
				t.Fatal(err)
			}
			for _, report := range live.Status.ScopeReports {
				if report.Identity.ScopeKind == "NeverMaterialized" && report.RetirementOperationID == "retire" {
					t.Fatal("unbound prior certificate or owner minted new historical ACK")
				}
			}
		})
	}
}

func TestRetirementHistoricalScopesChangedNonceAtNativeBarrierRefusesOldACK(t *testing.T) {
	r, c, parent := retainedRetirementProducerFixture(t)
	var once sync.Once
	r.Observer.Network.Flows.client = scopeFlowAdapterWith(t, func() map[string]uint32 { return nil }, func() {
		once.Do(func() {
			var live lab.Lab
			if err := c.Get(context.Background(), client.ObjectKeyFromObject(parent), &live); err != nil {
				t.Error(err)
				return
			}
			in, valid := lab.ParseLifecycleRetirement(live.Annotations[names.AnnotationLifecycleRetirement])
			if !valid {
				t.Error("fixture challenge missing")
				return
			}
			in.OperationID, in.Revision = "replacement-challenge", 4
			raw, _ := json.Marshal(in)
			live.Annotations[names.AnnotationLifecycleRetirement] = string(raw)
			if err := c.Update(context.Background(), &live); err != nil {
				t.Error(err)
			}
		})
	})
	if err := r.sync(context.Background()); err == nil {
		t.Fatal("changed challenge did not refuse sampled scope publication")
	}
	var live lab.Lab
	if err := c.Get(context.Background(), client.ObjectKeyFromObject(parent), &live); err != nil {
		t.Fatal(err)
	}
	for _, report := range live.Status.ScopeReports {
		if report.RetirementOperationID == "retire" {
			t.Fatal("old native scan stamped a superseded challenge")
		}
	}
}

func TestRetirementIntermediateFencePreservesEveryOriginalDebt(t *testing.T) {
	r, _, parent := retainedRetirementProducerFixture(t)
	id := parent.Status.ScopeInventory[1]
	in, _ := lab.ParseLifecycleRetirement(parent.Annotations[names.AnnotationLifecycleRetirement])
	enriched := *id.DeepCopy()
	enriched.AttachmentsComplete = false
	enriched.ContainerIDs = append(enriched.ContainerIDs, "newly-discovered")
	if err := r.Observer.retirementScopeCurrent(context.Background(), enriched, in); err != nil {
		t.Fatalf("valid in-progress native debt rejected: %v", err)
	}
	for _, field := range []string{"container", "cgroup", "tuple"} {
		copy := *enriched.DeepCopy()
		switch field {
		case "container":
			copy.ContainerIDs = copy.ContainerIDs[1:]
		case "cgroup":
			copy.CgroupPaths = copy.CgroupPaths[1:]
		case "tuple":
			copy.Incarnation++
		}
		if err := r.Observer.retirementScopeCurrent(context.Background(), copy, in); err == nil {
			t.Fatalf("intermediate fence dropped original %s authority", field)
		}
	}
}
