/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	allocationv1alpha1 "github.com/cybericebox/laboratory/api/allocation/v1alpha1"
	applyconfigurationallocationv1alpha1 "github.com/cybericebox/laboratory/clientset/applyconfiguration/allocation/v1alpha1"
	scheme "github.com/cybericebox/laboratory/clientset/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PoolsGetter has a method to return a PoolInterface.
// A group's client should implement this interface.
type PoolsGetter interface {
	Pools() PoolInterface
}

// PoolInterface has methods to work with Pool resources.
type PoolInterface interface {
	Create(ctx context.Context, pool *allocationv1alpha1.Pool, opts v1.CreateOptions) (*allocationv1alpha1.Pool, error)
	Update(ctx context.Context, pool *allocationv1alpha1.Pool, opts v1.UpdateOptions) (*allocationv1alpha1.Pool, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, pool *allocationv1alpha1.Pool, opts v1.UpdateOptions) (*allocationv1alpha1.Pool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*allocationv1alpha1.Pool, error)
	List(ctx context.Context, opts v1.ListOptions) (*allocationv1alpha1.PoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *allocationv1alpha1.Pool, err error)
	Apply(ctx context.Context, pool *applyconfigurationallocationv1alpha1.PoolApplyConfiguration, opts v1.ApplyOptions) (result *allocationv1alpha1.Pool, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, pool *applyconfigurationallocationv1alpha1.PoolApplyConfiguration, opts v1.ApplyOptions) (result *allocationv1alpha1.Pool, err error)
	PoolExpansion
}

// pools implements PoolInterface
type pools struct {
	*gentype.ClientWithListAndApply[*allocationv1alpha1.Pool, *allocationv1alpha1.PoolList, *applyconfigurationallocationv1alpha1.PoolApplyConfiguration]
}

// newPools returns a Pools
func newPools(c *AllocationV1alpha1Client) *pools {
	return &pools{
		gentype.NewClientWithListAndApply[*allocationv1alpha1.Pool, *allocationv1alpha1.PoolList, *applyconfigurationallocationv1alpha1.PoolApplyConfiguration](
			"pools",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *allocationv1alpha1.Pool { return &allocationv1alpha1.Pool{} },
			func() *allocationv1alpha1.PoolList { return &allocationv1alpha1.PoolList{} },
			gentype.PrefersProtobuf[*allocationv1alpha1.Pool](),
		),
	}
}
