/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AccessEntryApplyConfiguration represents a declarative configuration of the AccessEntry type for use
// with apply.
//
// AccessEntry describes a single externally reachable endpoint.
type AccessEntryApplyConfiguration struct {
	Device   *string `json:"device,omitempty"`
	Port     *int32  `json:"port,omitempty"`
	Protocol *string `json:"protocol,omitempty"`
	URL      *string `json:"url,omitempty"`
}

// AccessEntryApplyConfiguration constructs a declarative configuration of the AccessEntry type for use with
// apply.
func AccessEntry() *AccessEntryApplyConfiguration {
	return &AccessEntryApplyConfiguration{}
}

// WithDevice sets the Device field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Device field is set to the value of the last call.
func (b *AccessEntryApplyConfiguration) WithDevice(value string) *AccessEntryApplyConfiguration {
	b.Device = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *AccessEntryApplyConfiguration) WithPort(value int32) *AccessEntryApplyConfiguration {
	b.Port = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *AccessEntryApplyConfiguration) WithProtocol(value string) *AccessEntryApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *AccessEntryApplyConfiguration) WithURL(value string) *AccessEntryApplyConfiguration {
	b.URL = &value
	return b
}
