/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ConnectionTemplateApplyConfiguration represents a declarative configuration of the ConnectionTemplate type for use
// with apply.
type ConnectionTemplateApplyConfiguration struct {
	Endpoints []EndpointSpecApplyConfiguration `json:"endpoints,omitempty"`
}

// ConnectionTemplateApplyConfiguration constructs a declarative configuration of the ConnectionTemplate type for use with
// apply.
func ConnectionTemplate() *ConnectionTemplateApplyConfiguration {
	return &ConnectionTemplateApplyConfiguration{}
}
func (b ConnectionTemplateApplyConfiguration) IsApplyConfiguration() {}

// WithEndpoints adds the given value to the Endpoints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Endpoints field.
func (b *ConnectionTemplateApplyConfiguration) WithEndpoints(values ...*EndpointSpecApplyConfiguration) *ConnectionTemplateApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEndpoints")
		}
		b.Endpoints = append(b.Endpoints, *values[i])
	}
	return b
}
