/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DeviceStatusApplyConfiguration represents a declarative configuration of the DeviceStatus type for use
// with apply.
type DeviceStatusApplyConfiguration struct {
	Ready       *bool   `json:"ready,omitempty"`
	NodeName    *string `json:"nodeName,omitempty"`
	NodeAddress *string `json:"nodeAddress,omitempty"`
	PodIP       *string `json:"podIP,omitempty"`
	PodName     *string `json:"podName,omitempty"`
	VNI         *uint   `json:"vni,omitempty"`
	Reason      *string `json:"reason,omitempty"`
}

// DeviceStatusApplyConfiguration constructs a declarative configuration of the DeviceStatus type for use with
// apply.
func DeviceStatus() *DeviceStatusApplyConfiguration {
	return &DeviceStatusApplyConfiguration{}
}
func (b DeviceStatusApplyConfiguration) IsApplyConfiguration() {}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *DeviceStatusApplyConfiguration) WithReady(value bool) *DeviceStatusApplyConfiguration {
	b.Ready = &value
	return b
}

// WithNodeName sets the NodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeName field is set to the value of the last call.
func (b *DeviceStatusApplyConfiguration) WithNodeName(value string) *DeviceStatusApplyConfiguration {
	b.NodeName = &value
	return b
}

// WithNodeAddress sets the NodeAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeAddress field is set to the value of the last call.
func (b *DeviceStatusApplyConfiguration) WithNodeAddress(value string) *DeviceStatusApplyConfiguration {
	b.NodeAddress = &value
	return b
}

// WithPodIP sets the PodIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodIP field is set to the value of the last call.
func (b *DeviceStatusApplyConfiguration) WithPodIP(value string) *DeviceStatusApplyConfiguration {
	b.PodIP = &value
	return b
}

// WithPodName sets the PodName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodName field is set to the value of the last call.
func (b *DeviceStatusApplyConfiguration) WithPodName(value string) *DeviceStatusApplyConfiguration {
	b.PodName = &value
	return b
}

// WithVNI sets the VNI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VNI field is set to the value of the last call.
func (b *DeviceStatusApplyConfiguration) WithVNI(value uint) *DeviceStatusApplyConfiguration {
	b.VNI = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *DeviceStatusApplyConfiguration) WithReason(value string) *DeviceStatusApplyConfiguration {
	b.Reason = &value
	return b
}
