/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	laboratoryv1alpha1 "github.com/cybericebox/laboratory/api/laboratory/v1alpha1"
)

// DeviceSpecApplyConfiguration represents a declarative configuration of the DeviceSpec type for use
// with apply.
type DeviceSpecApplyConfiguration struct {
	LabRef         *string                            `json:"labRef,omitempty"`
	Name           *string                            `json:"name,omitempty"`
	Type           *laboratoryv1alpha1.DeviceType     `json:"type,omitempty"`
	Image          *string                            `json:"image,omitempty"`
	SecurityPreset *laboratoryv1alpha1.SecurityPreset `json:"securityPreset,omitempty"`
	Interfaces     []InterfaceSpecApplyConfiguration  `json:"interfaces,omitempty"`
	Exposure       *ExposureSpecApplyConfiguration    `json:"exposure,omitempty"`
}

// DeviceSpecApplyConfiguration constructs a declarative configuration of the DeviceSpec type for use with
// apply.
func DeviceSpec() *DeviceSpecApplyConfiguration {
	return &DeviceSpecApplyConfiguration{}
}
func (b DeviceSpecApplyConfiguration) IsApplyConfiguration() {}

// WithLabRef sets the LabRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabRef field is set to the value of the last call.
func (b *DeviceSpecApplyConfiguration) WithLabRef(value string) *DeviceSpecApplyConfiguration {
	b.LabRef = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DeviceSpecApplyConfiguration) WithName(value string) *DeviceSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *DeviceSpecApplyConfiguration) WithType(value laboratoryv1alpha1.DeviceType) *DeviceSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *DeviceSpecApplyConfiguration) WithImage(value string) *DeviceSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithSecurityPreset sets the SecurityPreset field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityPreset field is set to the value of the last call.
func (b *DeviceSpecApplyConfiguration) WithSecurityPreset(value laboratoryv1alpha1.SecurityPreset) *DeviceSpecApplyConfiguration {
	b.SecurityPreset = &value
	return b
}

// WithInterfaces adds the given value to the Interfaces field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Interfaces field.
func (b *DeviceSpecApplyConfiguration) WithInterfaces(values ...*InterfaceSpecApplyConfiguration) *DeviceSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithInterfaces")
		}
		b.Interfaces = append(b.Interfaces, *values[i])
	}
	return b
}

// WithExposure sets the Exposure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Exposure field is set to the value of the last call.
func (b *DeviceSpecApplyConfiguration) WithExposure(value *ExposureSpecApplyConfiguration) *DeviceSpecApplyConfiguration {
	b.Exposure = value
	return b
}
