/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DeviceStatusApplyConfiguration represents a declarative configuration of the DeviceStatus type for use
// with apply.
//
// DeviceStatus defines the observed state of Device.
type DeviceStatusApplyConfiguration struct {
	// RuntimeInventory is controller-owned and retained through API Pod deletion.
	RuntimeInventory []OwnedRuntimeIdentityApplyConfiguration `json:"runtimeInventory,omitempty"`
	// RuntimeReports are patched only by the bound node-agent.
	RuntimeReports []OwnedRuntimeReportApplyConfiguration `json:"runtimeReports,omitempty"`
	Ready          *bool                                  `json:"ready,omitempty"`
	NodeName       *string                                `json:"nodeName,omitempty"`
	// NodeAddress is the node IP used as Geneve VTEP address.
	NodeAddress *string `json:"nodeAddress,omitempty"`
	PodIP       *string `json:"podIP,omitempty"`
	// PodName is the current pod backing this device. A device runs one pod
	// (Deployment, replicas=1, or a bare Pod with state persistence) whose name
	// changes on recreation, so the
	// node-agent keys the device's per-pod OVS port on this stable pointer.
	PodName *string `json:"podName,omitempty"`
	// VNI is set only for unmanaged-switch and hub device types.
	VNI    *uint   `json:"vni,omitempty"`
	Reason *string `json:"reason,omitempty"`
	// State is the snapshot state of a device with spec.state.enabled.
	State *DeviceStateStatusApplyConfiguration `json:"state,omitempty"`
	// Scheduling is the pod's place on its way from the scheduler queue to Ready.
	Scheduling *PodScheduleApplyConfiguration `json:"scheduling,omitempty"`
}

// DeviceStatusApplyConfiguration constructs a declarative configuration of the DeviceStatus type for use with
// apply.
func DeviceStatus() *DeviceStatusApplyConfiguration {
	return &DeviceStatusApplyConfiguration{}
}

// WithRuntimeInventory adds the given value to the RuntimeInventory field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RuntimeInventory field.
func (b *DeviceStatusApplyConfiguration) WithRuntimeInventory(values ...*OwnedRuntimeIdentityApplyConfiguration) *DeviceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRuntimeInventory")
		}
		b.RuntimeInventory = append(b.RuntimeInventory, *values[i])
	}
	return b
}

// WithRuntimeReports adds the given value to the RuntimeReports field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RuntimeReports field.
func (b *DeviceStatusApplyConfiguration) WithRuntimeReports(values ...*OwnedRuntimeReportApplyConfiguration) *DeviceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRuntimeReports")
		}
		b.RuntimeReports = append(b.RuntimeReports, *values[i])
	}
	return b
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *DeviceStatusApplyConfiguration) WithReady(value bool) *DeviceStatusApplyConfiguration {
	b.Ready = &value
	return b
}

// WithNodeName sets the NodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeName field is set to the value of the last call.
func (b *DeviceStatusApplyConfiguration) WithNodeName(value string) *DeviceStatusApplyConfiguration {
	b.NodeName = &value
	return b
}

// WithNodeAddress sets the NodeAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeAddress field is set to the value of the last call.
func (b *DeviceStatusApplyConfiguration) WithNodeAddress(value string) *DeviceStatusApplyConfiguration {
	b.NodeAddress = &value
	return b
}

// WithPodIP sets the PodIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodIP field is set to the value of the last call.
func (b *DeviceStatusApplyConfiguration) WithPodIP(value string) *DeviceStatusApplyConfiguration {
	b.PodIP = &value
	return b
}

// WithPodName sets the PodName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodName field is set to the value of the last call.
func (b *DeviceStatusApplyConfiguration) WithPodName(value string) *DeviceStatusApplyConfiguration {
	b.PodName = &value
	return b
}

// WithVNI sets the VNI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VNI field is set to the value of the last call.
func (b *DeviceStatusApplyConfiguration) WithVNI(value uint) *DeviceStatusApplyConfiguration {
	b.VNI = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *DeviceStatusApplyConfiguration) WithReason(value string) *DeviceStatusApplyConfiguration {
	b.Reason = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *DeviceStatusApplyConfiguration) WithState(value *DeviceStateStatusApplyConfiguration) *DeviceStatusApplyConfiguration {
	b.State = value
	return b
}

// WithScheduling sets the Scheduling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scheduling field is set to the value of the last call.
func (b *DeviceStatusApplyConfiguration) WithScheduling(value *PodScheduleApplyConfiguration) *DeviceStatusApplyConfiguration {
	b.Scheduling = value
	return b
}
