/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeviceStateInfoApplyConfiguration represents a declarative configuration of the DeviceStateInfo type for use
// with apply.
//
// DeviceStateInfo is the organizer-facing view of a device's snapshots.
type DeviceStateInfoApplyConfiguration struct {
	LastSnapshotAt *v1.Time `json:"lastSnapshotAt,omitempty"`
	RestoredAt     *v1.Time `json:"restoredAt,omitempty"`
	SizeBytes      *int64   `json:"sizeBytes,omitempty"`
	// QuotaWarning is set while snapshots are refused or failing.
	QuotaWarning *string `json:"quotaWarning,omitempty"`
	// Rescue is true while the device runs in rescue mode.
	Rescue *bool `json:"rescue,omitempty"`
}

// DeviceStateInfoApplyConfiguration constructs a declarative configuration of the DeviceStateInfo type for use with
// apply.
func DeviceStateInfo() *DeviceStateInfoApplyConfiguration {
	return &DeviceStateInfoApplyConfiguration{}
}

// WithLastSnapshotAt sets the LastSnapshotAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSnapshotAt field is set to the value of the last call.
func (b *DeviceStateInfoApplyConfiguration) WithLastSnapshotAt(value v1.Time) *DeviceStateInfoApplyConfiguration {
	b.LastSnapshotAt = &value
	return b
}

// WithRestoredAt sets the RestoredAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestoredAt field is set to the value of the last call.
func (b *DeviceStateInfoApplyConfiguration) WithRestoredAt(value v1.Time) *DeviceStateInfoApplyConfiguration {
	b.RestoredAt = &value
	return b
}

// WithSizeBytes sets the SizeBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SizeBytes field is set to the value of the last call.
func (b *DeviceStateInfoApplyConfiguration) WithSizeBytes(value int64) *DeviceStateInfoApplyConfiguration {
	b.SizeBytes = &value
	return b
}

// WithQuotaWarning sets the QuotaWarning field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QuotaWarning field is set to the value of the last call.
func (b *DeviceStateInfoApplyConfiguration) WithQuotaWarning(value string) *DeviceStateInfoApplyConfiguration {
	b.QuotaWarning = &value
	return b
}

// WithRescue sets the Rescue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Rescue field is set to the value of the last call.
func (b *DeviceStateInfoApplyConfiguration) WithRescue(value bool) *DeviceStateInfoApplyConfiguration {
	b.Rescue = &value
	return b
}
