/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DHCPRangeApplyConfiguration represents a declarative configuration of the DHCPRange type for use
// with apply.
//
// DHCPRange is an inclusive host-offset interval within the lab /24.
// An enabled DHCP server must have at least one range.
type DHCPRangeApplyConfiguration struct {
	Start *int32 `json:"start,omitempty"`
	End   *int32 `json:"end,omitempty"`
}

// DHCPRangeApplyConfiguration constructs a declarative configuration of the DHCPRange type for use with
// apply.
func DHCPRange() *DHCPRangeApplyConfiguration {
	return &DHCPRangeApplyConfiguration{}
}

// WithStart sets the Start field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Start field is set to the value of the last call.
func (b *DHCPRangeApplyConfiguration) WithStart(value int32) *DHCPRangeApplyConfiguration {
	b.Start = &value
	return b
}

// WithEnd sets the End field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the End field is set to the value of the last call.
func (b *DHCPRangeApplyConfiguration) WithEnd(value int32) *DHCPRangeApplyConfiguration {
	b.End = &value
	return b
}
