/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DHCPServerApplyConfiguration represents a declarative configuration of the DHCPServer type for use
// with apply.
//
// DHCPServer enables the embedded DHCP server for a network segment.
// Subnet and gateway are derived from the lab's allocated CIDR (Status.*.CIDR).
type DHCPServerApplyConfiguration struct {
	Enabled *bool                         `json:"enabled,omitempty"`
	Ranges  []DHCPRangeApplyConfiguration `json:"ranges,omitempty"`
	// DNS is advertised only by the internet gateway's DHCP server.
	DNS *string `json:"dns,omitempty"`
}

// DHCPServerApplyConfiguration constructs a declarative configuration of the DHCPServer type for use with
// apply.
func DHCPServer() *DHCPServerApplyConfiguration {
	return &DHCPServerApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *DHCPServerApplyConfiguration) WithEnabled(value bool) *DHCPServerApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithRanges adds the given value to the Ranges field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Ranges field.
func (b *DHCPServerApplyConfiguration) WithRanges(values ...*DHCPRangeApplyConfiguration) *DHCPServerApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRanges")
		}
		b.Ranges = append(b.Ranges, *values[i])
	}
	return b
}

// WithDNS sets the DNS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DNS field is set to the value of the last call.
func (b *DHCPServerApplyConfiguration) WithDNS(value string) *DHCPServerApplyConfiguration {
	b.DNS = &value
	return b
}
