/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// EndpointSpecApplyConfiguration represents a declarative configuration of the EndpointSpec type for use
// with apply.
//
// EndpointSpec references a device interface in a Connection.
type EndpointSpecApplyConfiguration struct {
	// Device is the name of the Device CRD within the same Lab.
	Device *string `json:"device,omitempty"`
	// Interface is the interface name on the device; omit for unmanaged-switch/hub.
	Interface *string `json:"interface,omitempty"`
}

// EndpointSpecApplyConfiguration constructs a declarative configuration of the EndpointSpec type for use with
// apply.
func EndpointSpec() *EndpointSpecApplyConfiguration {
	return &EndpointSpecApplyConfiguration{}
}

// WithDevice sets the Device field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Device field is set to the value of the last call.
func (b *EndpointSpecApplyConfiguration) WithDevice(value string) *EndpointSpecApplyConfiguration {
	b.Device = &value
	return b
}

// WithInterface sets the Interface field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interface field is set to the value of the last call.
func (b *EndpointSpecApplyConfiguration) WithInterface(value string) *EndpointSpecApplyConfiguration {
	b.Interface = &value
	return b
}
