/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ExposureSpecApplyConfiguration represents a declarative configuration of the ExposureSpec type for use
// with apply.
//
// ExposureSpec declares how a device is externally reachable.
type ExposureSpecApplyConfiguration struct {
	Web *WebExposureApplyConfiguration `json:"web,omitempty"`
}

// ExposureSpecApplyConfiguration constructs a declarative configuration of the ExposureSpec type for use with
// apply.
func ExposureSpec() *ExposureSpecApplyConfiguration {
	return &ExposureSpecApplyConfiguration{}
}

// WithWeb sets the Web field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Web field is set to the value of the last call.
func (b *ExposureSpecApplyConfiguration) WithWeb(value *WebExposureApplyConfiguration) *ExposureSpecApplyConfiguration {
	b.Web = value
	return b
}
