/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// GroupLifecycleSpecApplyConfiguration represents a declarative configuration of the GroupLifecycleSpec type for use
// with apply.
//
// GroupLifecycleSpec stops only group services after every child is released.
// A start affects VPN/gateway only, never a child's lifecycle or terminal intent.
type GroupLifecycleSpecApplyConfiguration struct {
	DesiredState          *string `json:"desiredState,omitempty"`
	OperationID           *string `json:"operationId,omitempty"`
	Revision              *int64  `json:"revision,omitempty"`
	RequireAllLabsStopped *bool   `json:"requireAllLabsStopped,omitempty"`
}

// GroupLifecycleSpecApplyConfiguration constructs a declarative configuration of the GroupLifecycleSpec type for use with
// apply.
func GroupLifecycleSpec() *GroupLifecycleSpecApplyConfiguration {
	return &GroupLifecycleSpecApplyConfiguration{}
}

// WithDesiredState sets the DesiredState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DesiredState field is set to the value of the last call.
func (b *GroupLifecycleSpecApplyConfiguration) WithDesiredState(value string) *GroupLifecycleSpecApplyConfiguration {
	b.DesiredState = &value
	return b
}

// WithOperationID sets the OperationID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OperationID field is set to the value of the last call.
func (b *GroupLifecycleSpecApplyConfiguration) WithOperationID(value string) *GroupLifecycleSpecApplyConfiguration {
	b.OperationID = &value
	return b
}

// WithRevision sets the Revision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Revision field is set to the value of the last call.
func (b *GroupLifecycleSpecApplyConfiguration) WithRevision(value int64) *GroupLifecycleSpecApplyConfiguration {
	b.Revision = &value
	return b
}

// WithRequireAllLabsStopped sets the RequireAllLabsStopped field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequireAllLabsStopped field is set to the value of the last call.
func (b *GroupLifecycleSpecApplyConfiguration) WithRequireAllLabsStopped(value bool) *GroupLifecycleSpecApplyConfiguration {
	b.RequireAllLabsStopped = &value
	return b
}
