/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// LabGroupAccessPolicyStatusApplyConfiguration represents a declarative configuration of the LabGroupAccessPolicyStatus type for use
// with apply.
//
// LabGroupAccessPolicyStatus is written only by the in-namespace VPN
// reconciler after it has applied the matching policy generation.
type LabGroupAccessPolicyStatusApplyConfiguration struct {
	ObservedGeneration *int64                                             `json:"observedGeneration,omitempty"`
	State              *string                                            `json:"state,omitempty"`
	AppliedAt          *v1.Time                                           `json:"appliedAt,omitempty"`
	LastError          *string                                            `json:"lastError,omitempty"`
	Rules              []LabGroupAccessPolicyRuleStatusApplyConfiguration `json:"rules,omitempty"`
}

// LabGroupAccessPolicyStatusApplyConfiguration constructs a declarative configuration of the LabGroupAccessPolicyStatus type for use with
// apply.
func LabGroupAccessPolicyStatus() *LabGroupAccessPolicyStatusApplyConfiguration {
	return &LabGroupAccessPolicyStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *LabGroupAccessPolicyStatusApplyConfiguration) WithObservedGeneration(value int64) *LabGroupAccessPolicyStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *LabGroupAccessPolicyStatusApplyConfiguration) WithState(value string) *LabGroupAccessPolicyStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithAppliedAt sets the AppliedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppliedAt field is set to the value of the last call.
func (b *LabGroupAccessPolicyStatusApplyConfiguration) WithAppliedAt(value v1.Time) *LabGroupAccessPolicyStatusApplyConfiguration {
	b.AppliedAt = &value
	return b
}

// WithLastError sets the LastError field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastError field is set to the value of the last call.
func (b *LabGroupAccessPolicyStatusApplyConfiguration) WithLastError(value string) *LabGroupAccessPolicyStatusApplyConfiguration {
	b.LastError = &value
	return b
}

// WithRules adds the given value to the Rules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Rules field.
func (b *LabGroupAccessPolicyStatusApplyConfiguration) WithRules(values ...*LabGroupAccessPolicyRuleStatusApplyConfiguration) *LabGroupAccessPolicyStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRules")
		}
		b.Rules = append(b.Rules, *values[i])
	}
	return b
}
