/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LabGroupVPNStatusApplyConfiguration represents a declarative configuration of the LabGroupVPNStatus type for use
// with apply.
//
// LabGroupVPNStatus exposes VPN server connection details.
type LabGroupVPNStatusApplyConfiguration struct {
	// ClientSubnet is the group subnet containing the tunnel-only test gateway.
	ClientSubnet *string `json:"clientSubnet,omitempty"`
	// PublicKey is the WireGuard public key used as routing key for demux.
	PublicKey *string `json:"publicKey,omitempty"`
	// Endpoint is the public UDP address of the VPN server (host:port) advertised to clients.
	Endpoint *string `json:"endpoint,omitempty"`
	// SecretRef is "<namespace>/<name>" of the vpn-server-keypair Secret.
	SecretRef *string `json:"secretRef,omitempty"`
	// Registered is true when the VPN deployment has at least one ready replica,
	// including while Lab devices are suspended.
	Registered *bool `json:"registered,omitempty"`
}

// LabGroupVPNStatusApplyConfiguration constructs a declarative configuration of the LabGroupVPNStatus type for use with
// apply.
func LabGroupVPNStatus() *LabGroupVPNStatusApplyConfiguration {
	return &LabGroupVPNStatusApplyConfiguration{}
}

// WithClientSubnet sets the ClientSubnet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientSubnet field is set to the value of the last call.
func (b *LabGroupVPNStatusApplyConfiguration) WithClientSubnet(value string) *LabGroupVPNStatusApplyConfiguration {
	b.ClientSubnet = &value
	return b
}

// WithPublicKey sets the PublicKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicKey field is set to the value of the last call.
func (b *LabGroupVPNStatusApplyConfiguration) WithPublicKey(value string) *LabGroupVPNStatusApplyConfiguration {
	b.PublicKey = &value
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *LabGroupVPNStatusApplyConfiguration) WithEndpoint(value string) *LabGroupVPNStatusApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *LabGroupVPNStatusApplyConfiguration) WithSecretRef(value string) *LabGroupVPNStatusApplyConfiguration {
	b.SecretRef = &value
	return b
}

// WithRegistered sets the Registered field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Registered field is set to the value of the last call.
func (b *LabGroupVPNStatusApplyConfiguration) WithRegistered(value bool) *LabGroupVPNStatusApplyConfiguration {
	b.Registered = &value
	return b
}
