/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	laboratoryv1alpha1 "github.com/cybericebox/laboratory/api/laboratory/v1alpha1"
)

// LabGroupAccessPolicyRuleStatusApplyConfiguration represents a declarative configuration of the LabGroupAccessPolicyRuleStatus type for use
// with apply.
type LabGroupAccessPolicyRuleStatusApplyConfiguration struct {
	ClientName   *string                                  `json:"clientName,omitempty"`
	LabName      *string                                  `json:"labName,omitempty"`
	Action       *laboratoryv1alpha1.LabGroupAccessAction `json:"action,omitempty"`
	Packets      *int64                                   `json:"packets,omitempty"`
	Bytes        *int64                                   `json:"bytes,omitempty"`
	CounterReset *bool                                    `json:"counterReset,omitempty"`
}

// LabGroupAccessPolicyRuleStatusApplyConfiguration constructs a declarative configuration of the LabGroupAccessPolicyRuleStatus type for use with
// apply.
func LabGroupAccessPolicyRuleStatus() *LabGroupAccessPolicyRuleStatusApplyConfiguration {
	return &LabGroupAccessPolicyRuleStatusApplyConfiguration{}
}
func (b LabGroupAccessPolicyRuleStatusApplyConfiguration) IsApplyConfiguration() {}

// WithClientName sets the ClientName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientName field is set to the value of the last call.
func (b *LabGroupAccessPolicyRuleStatusApplyConfiguration) WithClientName(value string) *LabGroupAccessPolicyRuleStatusApplyConfiguration {
	b.ClientName = &value
	return b
}

// WithLabName sets the LabName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabName field is set to the value of the last call.
func (b *LabGroupAccessPolicyRuleStatusApplyConfiguration) WithLabName(value string) *LabGroupAccessPolicyRuleStatusApplyConfiguration {
	b.LabName = &value
	return b
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *LabGroupAccessPolicyRuleStatusApplyConfiguration) WithAction(value laboratoryv1alpha1.LabGroupAccessAction) *LabGroupAccessPolicyRuleStatusApplyConfiguration {
	b.Action = &value
	return b
}

// WithPackets sets the Packets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Packets field is set to the value of the last call.
func (b *LabGroupAccessPolicyRuleStatusApplyConfiguration) WithPackets(value int64) *LabGroupAccessPolicyRuleStatusApplyConfiguration {
	b.Packets = &value
	return b
}

// WithBytes sets the Bytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bytes field is set to the value of the last call.
func (b *LabGroupAccessPolicyRuleStatusApplyConfiguration) WithBytes(value int64) *LabGroupAccessPolicyRuleStatusApplyConfiguration {
	b.Bytes = &value
	return b
}

// WithCounterReset sets the CounterReset field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CounterReset field is set to the value of the last call.
func (b *LabGroupAccessPolicyRuleStatusApplyConfiguration) WithCounterReset(value bool) *LabGroupAccessPolicyRuleStatusApplyConfiguration {
	b.CounterReset = &value
	return b
}
