/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// LabGroupVPNSpecApplyConfiguration represents a declarative configuration of the LabGroupVPNSpec type for use
// with apply.
//
// LabGroupVPNSpec holds VPN server configuration.
type LabGroupVPNSpecApplyConfiguration struct {
	// KeypairSecretRef points to an existing WireGuard keypair Secret.
	// If omitted, operator generates a keypair and stores it in Secret vpn-server-keypair.
	KeypairSecretRef *v1.SecretReference `json:"keypairSecretRef,omitempty"`
}

// LabGroupVPNSpecApplyConfiguration constructs a declarative configuration of the LabGroupVPNSpec type for use with
// apply.
func LabGroupVPNSpec() *LabGroupVPNSpecApplyConfiguration {
	return &LabGroupVPNSpecApplyConfiguration{}
}

// WithKeypairSecretRef sets the KeypairSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeypairSecretRef field is set to the value of the last call.
func (b *LabGroupVPNSpecApplyConfiguration) WithKeypairSecretRef(value v1.SecretReference) *LabGroupVPNSpecApplyConfiguration {
	b.KeypairSecretRef = &value
	return b
}
