/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LabGroupGatewaySpecApplyConfiguration represents a declarative configuration of the LabGroupGatewaySpec type for use
// with apply.
//
// LabGroupGatewaySpec holds the internet gateway configuration.
type LabGroupGatewaySpecApplyConfiguration struct {
	// Size is the size of the gateway pod; absent = the chart's default. Fixed once set.
	Size *GroupPodSizeApplyConfiguration `json:"size,omitempty"`
}

// LabGroupGatewaySpecApplyConfiguration constructs a declarative configuration of the LabGroupGatewaySpec type for use with
// apply.
func LabGroupGatewaySpec() *LabGroupGatewaySpecApplyConfiguration {
	return &LabGroupGatewaySpecApplyConfiguration{}
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *LabGroupGatewaySpecApplyConfiguration) WithSize(value *GroupPodSizeApplyConfiguration) *LabGroupGatewaySpecApplyConfiguration {
	b.Size = value
	return b
}
