/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LabGroupSpecApplyConfiguration represents a declarative configuration of the LabGroupSpec type for use
// with apply.
//
// LabGroupSpec defines the desired state of LabGroup.
type LabGroupSpecApplyConfiguration struct {
	// Shared dependency from Group7 owner, identical definition at integration.
	Lifecycle *GroupLifecycleSpecApplyConfiguration `json:"lifecycle,omitempty"`
	VPN       *LabGroupVPNSpecApplyConfiguration    `json:"vpn,omitempty"`
	// Gateway holds the internet gateway pod's settings.
	Gateway   *LabGroupGatewaySpecApplyConfiguration `json:"gateway,omitempty"`
	Suspended *bool                                  `json:"suspended,omitempty"`
}

// LabGroupSpecApplyConfiguration constructs a declarative configuration of the LabGroupSpec type for use with
// apply.
func LabGroupSpec() *LabGroupSpecApplyConfiguration {
	return &LabGroupSpecApplyConfiguration{}
}

// WithLifecycle sets the Lifecycle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Lifecycle field is set to the value of the last call.
func (b *LabGroupSpecApplyConfiguration) WithLifecycle(value *GroupLifecycleSpecApplyConfiguration) *LabGroupSpecApplyConfiguration {
	b.Lifecycle = value
	return b
}

// WithVPN sets the VPN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VPN field is set to the value of the last call.
func (b *LabGroupSpecApplyConfiguration) WithVPN(value *LabGroupVPNSpecApplyConfiguration) *LabGroupSpecApplyConfiguration {
	b.VPN = value
	return b
}

// WithGateway sets the Gateway field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Gateway field is set to the value of the last call.
func (b *LabGroupSpecApplyConfiguration) WithGateway(value *LabGroupGatewaySpecApplyConfiguration) *LabGroupSpecApplyConfiguration {
	b.Gateway = value
	return b
}

// WithSuspended sets the Suspended field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspended field is set to the value of the last call.
func (b *LabGroupSpecApplyConfiguration) WithSuspended(value bool) *LabGroupSpecApplyConfiguration {
	b.Suspended = &value
	return b
}
