/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// LabLifecycleSpecApplyConfiguration represents a declarative configuration of the LabLifecycleSpec type for use
// with apply.
//
// LabLifecycleSpec is explicit revision-fenced intent. Its absence means Running.
// Acceptance of intent never proves capture, access revocation or runtime release.
type LabLifecycleSpecApplyConfiguration struct {
	DesiredState *string `json:"desiredState,omitempty"`
	OperationID  *string `json:"operationId,omitempty"`
	Revision     *int64  `json:"revision,omitempty"`
	SnapshotMode *string `json:"snapshotMode,omitempty"`
	// Terminal is monotonic: solved laboratories can never be restarted.
	Terminal       *bool    `json:"terminal,omitempty"`
	RetentionUntil *v1.Time `json:"retentionUntil,omitempty"`
}

// LabLifecycleSpecApplyConfiguration constructs a declarative configuration of the LabLifecycleSpec type for use with
// apply.
func LabLifecycleSpec() *LabLifecycleSpecApplyConfiguration {
	return &LabLifecycleSpecApplyConfiguration{}
}

// WithDesiredState sets the DesiredState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DesiredState field is set to the value of the last call.
func (b *LabLifecycleSpecApplyConfiguration) WithDesiredState(value string) *LabLifecycleSpecApplyConfiguration {
	b.DesiredState = &value
	return b
}

// WithOperationID sets the OperationID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OperationID field is set to the value of the last call.
func (b *LabLifecycleSpecApplyConfiguration) WithOperationID(value string) *LabLifecycleSpecApplyConfiguration {
	b.OperationID = &value
	return b
}

// WithRevision sets the Revision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Revision field is set to the value of the last call.
func (b *LabLifecycleSpecApplyConfiguration) WithRevision(value int64) *LabLifecycleSpecApplyConfiguration {
	b.Revision = &value
	return b
}

// WithSnapshotMode sets the SnapshotMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SnapshotMode field is set to the value of the last call.
func (b *LabLifecycleSpecApplyConfiguration) WithSnapshotMode(value string) *LabLifecycleSpecApplyConfiguration {
	b.SnapshotMode = &value
	return b
}

// WithTerminal sets the Terminal field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Terminal field is set to the value of the last call.
func (b *LabLifecycleSpecApplyConfiguration) WithTerminal(value bool) *LabLifecycleSpecApplyConfiguration {
	b.Terminal = &value
	return b
}

// WithRetentionUntil sets the RetentionUntil field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetentionUntil field is set to the value of the last call.
func (b *LabLifecycleSpecApplyConfiguration) WithRetentionUntil(value v1.Time) *LabLifecycleSpecApplyConfiguration {
	b.RetentionUntil = &value
	return b
}
