/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LabNetworkSpecApplyConfiguration represents a declarative configuration of the LabNetworkSpec type for use
// with apply.
//
// LabNetworkSpec configures a network segment (VPN or internet) attached to the lab.
type LabNetworkSpecApplyConfiguration struct {
	Enabled    *bool                         `json:"enabled,omitempty"`
	DHCPServer *DHCPServerApplyConfiguration `json:"dhcpServer,omitempty"`
}

// LabNetworkSpecApplyConfiguration constructs a declarative configuration of the LabNetworkSpec type for use with
// apply.
func LabNetworkSpec() *LabNetworkSpecApplyConfiguration {
	return &LabNetworkSpecApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *LabNetworkSpecApplyConfiguration) WithEnabled(value bool) *LabNetworkSpecApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithDHCPServer sets the DHCPServer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DHCPServer field is set to the value of the last call.
func (b *LabNetworkSpecApplyConfiguration) WithDHCPServer(value *DHCPServerApplyConfiguration) *LabNetworkSpecApplyConfiguration {
	b.DHCPServer = value
	return b
}
