/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	laboratoryv1alpha1 "github.com/cybericebox/laboratory/api/laboratory/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// LabStatusApplyConfiguration represents a declarative configuration of the LabStatus type for use
// with apply.
type LabStatusApplyConfiguration struct {
	Phase       *laboratoryv1alpha1.Phase           `json:"phase,omitempty"`
	VPN         *LabNetworkStatusApplyConfiguration `json:"vpn,omitempty"`
	Internet    *LabNetworkStatusApplyConfiguration `json:"internet,omitempty"`
	Devices     []DeviceRefApplyConfiguration       `json:"devices,omitempty"`
	Connections []ConnectionRefApplyConfiguration   `json:"connections,omitempty"`
	Access      []AccessEntryApplyConfiguration     `json:"access,omitempty"`
	Conditions  []v1.ConditionApplyConfiguration    `json:"conditions,omitempty"`
}

// LabStatusApplyConfiguration constructs a declarative configuration of the LabStatus type for use with
// apply.
func LabStatus() *LabStatusApplyConfiguration {
	return &LabStatusApplyConfiguration{}
}
func (b LabStatusApplyConfiguration) IsApplyConfiguration() {}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *LabStatusApplyConfiguration) WithPhase(value laboratoryv1alpha1.Phase) *LabStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithVPN sets the VPN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VPN field is set to the value of the last call.
func (b *LabStatusApplyConfiguration) WithVPN(value *LabNetworkStatusApplyConfiguration) *LabStatusApplyConfiguration {
	b.VPN = value
	return b
}

// WithInternet sets the Internet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Internet field is set to the value of the last call.
func (b *LabStatusApplyConfiguration) WithInternet(value *LabNetworkStatusApplyConfiguration) *LabStatusApplyConfiguration {
	b.Internet = value
	return b
}

// WithDevices adds the given value to the Devices field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Devices field.
func (b *LabStatusApplyConfiguration) WithDevices(values ...*DeviceRefApplyConfiguration) *LabStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDevices")
		}
		b.Devices = append(b.Devices, *values[i])
	}
	return b
}

// WithConnections adds the given value to the Connections field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Connections field.
func (b *LabStatusApplyConfiguration) WithConnections(values ...*ConnectionRefApplyConfiguration) *LabStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConnections")
		}
		b.Connections = append(b.Connections, *values[i])
	}
	return b
}

// WithAccess adds the given value to the Access field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Access field.
func (b *LabStatusApplyConfiguration) WithAccess(values ...*AccessEntryApplyConfiguration) *LabStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAccess")
		}
		b.Access = append(b.Access, *values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *LabStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *LabStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
