/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	laboratoryv1alpha1 "github.com/cybericebox/laboratory/api/laboratory/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// LabStatusApplyConfiguration represents a declarative configuration of the LabStatus type for use
// with apply.
//
// LabStatus defines the observed state of Lab.
type LabStatusApplyConfiguration struct {
	Phase       *laboratoryv1alpha1.Phase           `json:"phase,omitempty"`
	VPN         *LabNetworkStatusApplyConfiguration `json:"vpn,omitempty"`
	Internet    *LabNetworkStatusApplyConfiguration `json:"internet,omitempty"`
	Devices     []DeviceRefApplyConfiguration       `json:"devices,omitempty"`
	Connections []ConnectionRefApplyConfiguration   `json:"connections,omitempty"`
	Access      []AccessEntryApplyConfiguration     `json:"access,omitempty"`
	// Launch reports the launch pacing state: the resolved class, the admission
	// time and, while the lab is Queued, its place in the queue.
	Launch *LabLaunchStatusApplyConfiguration `json:"launch,omitempty"`
	// StatePersistence records how this lab runs its devices, decided once on the
	// first reconcile: true = bare Pods with snapshot-backed state, false =
	// Deployments. It never changes afterwards, whatever the platform switch says.
	StatePersistence *bool `json:"statePersistence,omitempty"`
	// ImageCache records whether this lab pulls its images through the platform
	// image cache, decided once on the first reconcile like StatePersistence.
	ImageCache *bool `json:"imageCache,omitempty"`
	// ImageDigests are the digests the image tags of the lab's container devices
	// (and the netconfig image) were pinned to when the lab was created with the
	// image cache on, keyed by the image as written in the spec.
	ImageDigests map[string]string `json:"imageDigests,omitempty"`
	// ImageWarning lists the images that could not be pinned and are pulled by
	// their tag; empty when all were.
	ImageWarning *string `json:"imageWarning,omitempty"`
	// Conditions surfaces reconciler progress/blocking reasons
	// (e.g. Ready=False reason=WaitingForInterface) for kubectl and clients.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// LabStatusApplyConfiguration constructs a declarative configuration of the LabStatus type for use with
// apply.
func LabStatus() *LabStatusApplyConfiguration {
	return &LabStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *LabStatusApplyConfiguration) WithPhase(value laboratoryv1alpha1.Phase) *LabStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithVPN sets the VPN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VPN field is set to the value of the last call.
func (b *LabStatusApplyConfiguration) WithVPN(value *LabNetworkStatusApplyConfiguration) *LabStatusApplyConfiguration {
	b.VPN = value
	return b
}

// WithInternet sets the Internet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Internet field is set to the value of the last call.
func (b *LabStatusApplyConfiguration) WithInternet(value *LabNetworkStatusApplyConfiguration) *LabStatusApplyConfiguration {
	b.Internet = value
	return b
}

// WithDevices adds the given value to the Devices field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Devices field.
func (b *LabStatusApplyConfiguration) WithDevices(values ...*DeviceRefApplyConfiguration) *LabStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDevices")
		}
		b.Devices = append(b.Devices, *values[i])
	}
	return b
}

// WithConnections adds the given value to the Connections field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Connections field.
func (b *LabStatusApplyConfiguration) WithConnections(values ...*ConnectionRefApplyConfiguration) *LabStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConnections")
		}
		b.Connections = append(b.Connections, *values[i])
	}
	return b
}

// WithAccess adds the given value to the Access field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Access field.
func (b *LabStatusApplyConfiguration) WithAccess(values ...*AccessEntryApplyConfiguration) *LabStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAccess")
		}
		b.Access = append(b.Access, *values[i])
	}
	return b
}

// WithLaunch sets the Launch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Launch field is set to the value of the last call.
func (b *LabStatusApplyConfiguration) WithLaunch(value *LabLaunchStatusApplyConfiguration) *LabStatusApplyConfiguration {
	b.Launch = value
	return b
}

// WithStatePersistence sets the StatePersistence field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StatePersistence field is set to the value of the last call.
func (b *LabStatusApplyConfiguration) WithStatePersistence(value bool) *LabStatusApplyConfiguration {
	b.StatePersistence = &value
	return b
}

// WithImageCache sets the ImageCache field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageCache field is set to the value of the last call.
func (b *LabStatusApplyConfiguration) WithImageCache(value bool) *LabStatusApplyConfiguration {
	b.ImageCache = &value
	return b
}

// WithImageDigests puts the entries into the ImageDigests field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ImageDigests field,
// overwriting an existing map entries in ImageDigests field with the same key.
func (b *LabStatusApplyConfiguration) WithImageDigests(entries map[string]string) *LabStatusApplyConfiguration {
	if b.ImageDigests == nil && len(entries) > 0 {
		b.ImageDigests = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ImageDigests[k] = v
	}
	return b
}

// WithImageWarning sets the ImageWarning field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImageWarning field is set to the value of the last call.
func (b *LabStatusApplyConfiguration) WithImageWarning(value string) *LabStatusApplyConfiguration {
	b.ImageWarning = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *LabStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *LabStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
