/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LabSpecApplyConfiguration represents a declarative configuration of the LabSpec type for use
// with apply.
//
// LabSpec defines the desired state of Lab.
type LabSpecApplyConfiguration struct {
	// Lifecycle is absent for legacy running laboratories.
	Lifecycle *LabLifecycleSpecApplyConfiguration `json:"lifecycle,omitempty"`
	VPN       *LabNetworkSpecApplyConfiguration   `json:"vpn,omitempty"`
	Internet  *LabNetworkSpecApplyConfiguration   `json:"internet,omitempty"`
	// Devices of the lab, switches and hubs included. The ceiling is fixed in code (names.MaxLabDevices).
	Devices     []DeviceTemplateApplyConfiguration     `json:"devices,omitempty"`
	Connections []ConnectionTemplateApplyConfiguration `json:"connections,omitempty"`
}

// LabSpecApplyConfiguration constructs a declarative configuration of the LabSpec type for use with
// apply.
func LabSpec() *LabSpecApplyConfiguration {
	return &LabSpecApplyConfiguration{}
}

// WithLifecycle sets the Lifecycle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Lifecycle field is set to the value of the last call.
func (b *LabSpecApplyConfiguration) WithLifecycle(value *LabLifecycleSpecApplyConfiguration) *LabSpecApplyConfiguration {
	b.Lifecycle = value
	return b
}

// WithVPN sets the VPN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VPN field is set to the value of the last call.
func (b *LabSpecApplyConfiguration) WithVPN(value *LabNetworkSpecApplyConfiguration) *LabSpecApplyConfiguration {
	b.VPN = value
	return b
}

// WithInternet sets the Internet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Internet field is set to the value of the last call.
func (b *LabSpecApplyConfiguration) WithInternet(value *LabNetworkSpecApplyConfiguration) *LabSpecApplyConfiguration {
	b.Internet = value
	return b
}

// WithDevices adds the given value to the Devices field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Devices field.
func (b *LabSpecApplyConfiguration) WithDevices(values ...*DeviceTemplateApplyConfiguration) *LabSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDevices")
		}
		b.Devices = append(b.Devices, *values[i])
	}
	return b
}

// WithConnections adds the given value to the Connections field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Connections field.
func (b *LabSpecApplyConfiguration) WithConnections(values ...*ConnectionTemplateApplyConfiguration) *LabSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConnections")
		}
		b.Connections = append(b.Connections, *values[i])
	}
	return b
}
