/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LabTrafficCoverageSpanApplyConfiguration represents a declarative configuration of the LabTrafficCoverageSpan type for use
// with apply.
//
// LabTrafficCoverageSpan is one actually observed collector interval. Separate
// spans preserve restart/replica gaps instead of treating their envelope as watched.
type LabTrafficCoverageSpanApplyConfiguration struct {
	FromMs *int64 `json:"fromMs,omitempty"`
	ToMs   *int64 `json:"toMs,omitempty"`
	// Partial also covers truncation or unavailable accounting within this span.
	Partial  *bool   `json:"partial,omitempty"`
	Source   *string `json:"source,omitempty"`
	Instance *string `json:"instance,omitempty"`
	BootID   *string `json:"bootID,omitempty"`
}

// LabTrafficCoverageSpanApplyConfiguration constructs a declarative configuration of the LabTrafficCoverageSpan type for use with
// apply.
func LabTrafficCoverageSpan() *LabTrafficCoverageSpanApplyConfiguration {
	return &LabTrafficCoverageSpanApplyConfiguration{}
}

// WithFromMs sets the FromMs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FromMs field is set to the value of the last call.
func (b *LabTrafficCoverageSpanApplyConfiguration) WithFromMs(value int64) *LabTrafficCoverageSpanApplyConfiguration {
	b.FromMs = &value
	return b
}

// WithToMs sets the ToMs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ToMs field is set to the value of the last call.
func (b *LabTrafficCoverageSpanApplyConfiguration) WithToMs(value int64) *LabTrafficCoverageSpanApplyConfiguration {
	b.ToMs = &value
	return b
}

// WithPartial sets the Partial field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Partial field is set to the value of the last call.
func (b *LabTrafficCoverageSpanApplyConfiguration) WithPartial(value bool) *LabTrafficCoverageSpanApplyConfiguration {
	b.Partial = &value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *LabTrafficCoverageSpanApplyConfiguration) WithSource(value string) *LabTrafficCoverageSpanApplyConfiguration {
	b.Source = &value
	return b
}

// WithInstance sets the Instance field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Instance field is set to the value of the last call.
func (b *LabTrafficCoverageSpanApplyConfiguration) WithInstance(value string) *LabTrafficCoverageSpanApplyConfiguration {
	b.Instance = &value
	return b
}

// WithBootID sets the BootID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootID field is set to the value of the last call.
func (b *LabTrafficCoverageSpanApplyConfiguration) WithBootID(value string) *LabTrafficCoverageSpanApplyConfiguration {
	b.BootID = &value
	return b
}
