/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	laboratoryv1alpha1 "github.com/cybericebox/laboratory/api/laboratory/v1alpha1"
)

// LabTrafficReportSpecApplyConfiguration represents a declarative configuration of the LabTrafficReportSpec type for use
// with apply.
//
// LabTrafficReportSpec identifies the writer of a report. The report carries
// facts only; nothing here configures behaviour.
type LabTrafficReportSpecApplyConfiguration struct {
	Kind *laboratoryv1alpha1.LabTrafficSurface `json:"kind,omitempty"`
	// Instance is the writing pod (the VPN pod, or one proxy replica).
	Instance *string `json:"instance,omitempty"`
}

// LabTrafficReportSpecApplyConfiguration constructs a declarative configuration of the LabTrafficReportSpec type for use with
// apply.
func LabTrafficReportSpec() *LabTrafficReportSpecApplyConfiguration {
	return &LabTrafficReportSpecApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *LabTrafficReportSpecApplyConfiguration) WithKind(value laboratoryv1alpha1.LabTrafficSurface) *LabTrafficReportSpecApplyConfiguration {
	b.Kind = &value
	return b
}

// WithInstance sets the Instance field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Instance field is set to the value of the last call.
func (b *LabTrafficReportSpecApplyConfiguration) WithInstance(value string) *LabTrafficReportSpecApplyConfiguration {
	b.Instance = &value
	return b
}
