/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LabTrafficKernelCheckpointApplyConfiguration represents a declarative configuration of the LabTrafficKernelCheckpoint type for use
// with apply.
//
// LabTrafficKernelCheckpoint stores private raw-counter checkpoints for resume.
// Decimal strings preserve uint64 kernel values without JSON integer loss.
type LabTrafficKernelCheckpointApplyConfiguration struct {
	Subject              *string `json:"subject,omitempty"`
	LabName              *string `json:"labName,omitempty"`
	BindingID            *string `json:"bindingID,omitempty"`
	Epoch                *string `json:"epoch,omitempty"`
	PacketsOut           *string `json:"packetsOut,omitempty"`
	PacketsIn            *string `json:"packetsIn,omitempty"`
	BytesOut             *string `json:"bytesOut,omitempty"`
	BytesIn              *string `json:"bytesIn,omitempty"`
	Attempts             *string `json:"attempts,omitempty"`
	LabInitiatedAttempts *string `json:"labInitiatedAttempts,omitempty"`
}

// LabTrafficKernelCheckpointApplyConfiguration constructs a declarative configuration of the LabTrafficKernelCheckpoint type for use with
// apply.
func LabTrafficKernelCheckpoint() *LabTrafficKernelCheckpointApplyConfiguration {
	return &LabTrafficKernelCheckpointApplyConfiguration{}
}

// WithSubject sets the Subject field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Subject field is set to the value of the last call.
func (b *LabTrafficKernelCheckpointApplyConfiguration) WithSubject(value string) *LabTrafficKernelCheckpointApplyConfiguration {
	b.Subject = &value
	return b
}

// WithLabName sets the LabName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabName field is set to the value of the last call.
func (b *LabTrafficKernelCheckpointApplyConfiguration) WithLabName(value string) *LabTrafficKernelCheckpointApplyConfiguration {
	b.LabName = &value
	return b
}

// WithBindingID sets the BindingID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BindingID field is set to the value of the last call.
func (b *LabTrafficKernelCheckpointApplyConfiguration) WithBindingID(value string) *LabTrafficKernelCheckpointApplyConfiguration {
	b.BindingID = &value
	return b
}

// WithEpoch sets the Epoch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Epoch field is set to the value of the last call.
func (b *LabTrafficKernelCheckpointApplyConfiguration) WithEpoch(value string) *LabTrafficKernelCheckpointApplyConfiguration {
	b.Epoch = &value
	return b
}

// WithPacketsOut sets the PacketsOut field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PacketsOut field is set to the value of the last call.
func (b *LabTrafficKernelCheckpointApplyConfiguration) WithPacketsOut(value string) *LabTrafficKernelCheckpointApplyConfiguration {
	b.PacketsOut = &value
	return b
}

// WithPacketsIn sets the PacketsIn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PacketsIn field is set to the value of the last call.
func (b *LabTrafficKernelCheckpointApplyConfiguration) WithPacketsIn(value string) *LabTrafficKernelCheckpointApplyConfiguration {
	b.PacketsIn = &value
	return b
}

// WithBytesOut sets the BytesOut field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BytesOut field is set to the value of the last call.
func (b *LabTrafficKernelCheckpointApplyConfiguration) WithBytesOut(value string) *LabTrafficKernelCheckpointApplyConfiguration {
	b.BytesOut = &value
	return b
}

// WithBytesIn sets the BytesIn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BytesIn field is set to the value of the last call.
func (b *LabTrafficKernelCheckpointApplyConfiguration) WithBytesIn(value string) *LabTrafficKernelCheckpointApplyConfiguration {
	b.BytesIn = &value
	return b
}

// WithAttempts sets the Attempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Attempts field is set to the value of the last call.
func (b *LabTrafficKernelCheckpointApplyConfiguration) WithAttempts(value string) *LabTrafficKernelCheckpointApplyConfiguration {
	b.Attempts = &value
	return b
}

// WithLabInitiatedAttempts sets the LabInitiatedAttempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabInitiatedAttempts field is set to the value of the last call.
func (b *LabTrafficKernelCheckpointApplyConfiguration) WithLabInitiatedAttempts(value string) *LabTrafficKernelCheckpointApplyConfiguration {
	b.LabInitiatedAttempts = &value
	return b
}
