/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LabTrafficTouchApplyConfiguration represents a declarative configuration of the LabTrafficTouch type for use
// with apply.
//
// LabTrafficTouch is one cumulative aggregate row: what one VPN config (or one
// proxy token) did against one lab target since the collector booted. There is
// no time series. Times are Unix milliseconds. Only lab-internal addresses are
// ever recorded, never the address of a user.
type LabTrafficTouchApplyConfiguration struct {
	// Subject is the LabGroupClient name, for the VPN and for the proxy (the client
	// of the lab access token).
	Subject *string `json:"subject,omitempty"`
	LabName *string `json:"labName,omitempty"`
	// Device is the device or route inside the lab, when known.
	Device  *string `json:"device,omitempty"`
	DstIP   *string `json:"dstIP,omitempty"`
	Proto   *string `json:"proto,omitempty"`
	DstPort *int32  `json:"dstPort,omitempty"`
	// Attempts counts new connections (VPN) or requests (proxy).
	Attempts   *int64 `json:"attempts,omitempty"`
	PacketsOut *int64 `json:"packetsOut,omitempty"`
	PacketsIn  *int64 `json:"packetsIn,omitempty"`
	BytesOut   *int64 `json:"bytesOut,omitempty"`
	BytesIn    *int64 `json:"bytesIn,omitempty"`
	// FirstSeenMs is the first attempt, LastSeenMs the last one.
	FirstSeenMs *int64 `json:"firstSeenMs,omitempty"`
	LastSeenMs  *int64 `json:"lastSeenMs,omitempty"`
	// FirstRespondedMs is when the lab first answered; zero means it never did.
	FirstRespondedMs *int64 `json:"firstRespondedMs,omitempty"`
}

// LabTrafficTouchApplyConfiguration constructs a declarative configuration of the LabTrafficTouch type for use with
// apply.
func LabTrafficTouch() *LabTrafficTouchApplyConfiguration {
	return &LabTrafficTouchApplyConfiguration{}
}

// WithSubject sets the Subject field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Subject field is set to the value of the last call.
func (b *LabTrafficTouchApplyConfiguration) WithSubject(value string) *LabTrafficTouchApplyConfiguration {
	b.Subject = &value
	return b
}

// WithLabName sets the LabName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabName field is set to the value of the last call.
func (b *LabTrafficTouchApplyConfiguration) WithLabName(value string) *LabTrafficTouchApplyConfiguration {
	b.LabName = &value
	return b
}

// WithDevice sets the Device field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Device field is set to the value of the last call.
func (b *LabTrafficTouchApplyConfiguration) WithDevice(value string) *LabTrafficTouchApplyConfiguration {
	b.Device = &value
	return b
}

// WithDstIP sets the DstIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DstIP field is set to the value of the last call.
func (b *LabTrafficTouchApplyConfiguration) WithDstIP(value string) *LabTrafficTouchApplyConfiguration {
	b.DstIP = &value
	return b
}

// WithProto sets the Proto field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Proto field is set to the value of the last call.
func (b *LabTrafficTouchApplyConfiguration) WithProto(value string) *LabTrafficTouchApplyConfiguration {
	b.Proto = &value
	return b
}

// WithDstPort sets the DstPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DstPort field is set to the value of the last call.
func (b *LabTrafficTouchApplyConfiguration) WithDstPort(value int32) *LabTrafficTouchApplyConfiguration {
	b.DstPort = &value
	return b
}

// WithAttempts sets the Attempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Attempts field is set to the value of the last call.
func (b *LabTrafficTouchApplyConfiguration) WithAttempts(value int64) *LabTrafficTouchApplyConfiguration {
	b.Attempts = &value
	return b
}

// WithPacketsOut sets the PacketsOut field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PacketsOut field is set to the value of the last call.
func (b *LabTrafficTouchApplyConfiguration) WithPacketsOut(value int64) *LabTrafficTouchApplyConfiguration {
	b.PacketsOut = &value
	return b
}

// WithPacketsIn sets the PacketsIn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PacketsIn field is set to the value of the last call.
func (b *LabTrafficTouchApplyConfiguration) WithPacketsIn(value int64) *LabTrafficTouchApplyConfiguration {
	b.PacketsIn = &value
	return b
}

// WithBytesOut sets the BytesOut field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BytesOut field is set to the value of the last call.
func (b *LabTrafficTouchApplyConfiguration) WithBytesOut(value int64) *LabTrafficTouchApplyConfiguration {
	b.BytesOut = &value
	return b
}

// WithBytesIn sets the BytesIn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BytesIn field is set to the value of the last call.
func (b *LabTrafficTouchApplyConfiguration) WithBytesIn(value int64) *LabTrafficTouchApplyConfiguration {
	b.BytesIn = &value
	return b
}

// WithFirstSeenMs sets the FirstSeenMs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FirstSeenMs field is set to the value of the last call.
func (b *LabTrafficTouchApplyConfiguration) WithFirstSeenMs(value int64) *LabTrafficTouchApplyConfiguration {
	b.FirstSeenMs = &value
	return b
}

// WithLastSeenMs sets the LastSeenMs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSeenMs field is set to the value of the last call.
func (b *LabTrafficTouchApplyConfiguration) WithLastSeenMs(value int64) *LabTrafficTouchApplyConfiguration {
	b.LastSeenMs = &value
	return b
}

// WithFirstRespondedMs sets the FirstRespondedMs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FirstRespondedMs field is set to the value of the last call.
func (b *LabTrafficTouchApplyConfiguration) WithFirstRespondedMs(value int64) *LabTrafficTouchApplyConfiguration {
	b.FirstRespondedMs = &value
	return b
}
