/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	laboratoryv1alpha1 "github.com/cybericebox/laboratory/api/laboratory/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// LabVPNStatusApplyConfiguration represents a declarative configuration of the LabVPNStatus type for use
// with apply.
type LabVPNStatusApplyConfiguration struct {
	Phase       *laboratoryv1alpha1.LabVPNPhase  `json:"phase,omitempty"`
	DHCPEnabled *bool                            `json:"dhcpEnabled,omitempty"`
	DHCPReady   *bool                            `json:"dhcpReady,omitempty"`
	Conditions  []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// LabVPNStatusApplyConfiguration constructs a declarative configuration of the LabVPNStatus type for use with
// apply.
func LabVPNStatus() *LabVPNStatusApplyConfiguration {
	return &LabVPNStatusApplyConfiguration{}
}
func (b LabVPNStatusApplyConfiguration) IsApplyConfiguration() {}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *LabVPNStatusApplyConfiguration) WithPhase(value laboratoryv1alpha1.LabVPNPhase) *LabVPNStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithDHCPEnabled sets the DHCPEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DHCPEnabled field is set to the value of the last call.
func (b *LabVPNStatusApplyConfiguration) WithDHCPEnabled(value bool) *LabVPNStatusApplyConfiguration {
	b.DHCPEnabled = &value
	return b
}

// WithDHCPReady sets the DHCPReady field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DHCPReady field is set to the value of the last call.
func (b *LabVPNStatusApplyConfiguration) WithDHCPReady(value bool) *LabVPNStatusApplyConfiguration {
	b.DHCPReady = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *LabVPNStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *LabVPNStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
