/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MaintenanceWindowSpecApplyConfiguration represents a declarative configuration of the MaintenanceWindowSpec type for use
// with apply.
//
// MaintenanceWindowSpec announces a period in which the cluster operator may do maintenance
// (draining nodes, upgrades, restarts). Nothing in the platform refuses or delays work during a
// window; tenants read it through the management agent and plan around it (the platform's calendar
// gives the agent no capacity in the window, or the Capacity the window leaves).
type MaintenanceWindowSpecApplyConfiguration struct {
	// From is when the maintenance may start.
	From *v1.Time `json:"from,omitempty"`
	// To is when it is over; empty means open-ended (until the object is deleted or edited).
	To *v1.Time `json:"to,omitempty"`
	// Reason is shown to tenants, e.g. "kernel upgrade of the lab nodes".
	Reason *string `json:"reason,omitempty"`
	// Capacity is what the window leaves to the tenants it applies to (cpu and memory): empty means
	// nothing, the usual case of a drain or an upgrade. A resource the window does not name is zero.
	Capacity *corev1.ResourceList `json:"capacity,omitempty"`
	// Tenants lists the tenants the window applies to (Tenant names, i.e. client certificate
	// CNs); empty means all tenants.
	Tenants []string `json:"tenants,omitempty"`
}

// MaintenanceWindowSpecApplyConfiguration constructs a declarative configuration of the MaintenanceWindowSpec type for use with
// apply.
func MaintenanceWindowSpec() *MaintenanceWindowSpecApplyConfiguration {
	return &MaintenanceWindowSpecApplyConfiguration{}
}

// WithFrom sets the From field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the From field is set to the value of the last call.
func (b *MaintenanceWindowSpecApplyConfiguration) WithFrom(value v1.Time) *MaintenanceWindowSpecApplyConfiguration {
	b.From = &value
	return b
}

// WithTo sets the To field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the To field is set to the value of the last call.
func (b *MaintenanceWindowSpecApplyConfiguration) WithTo(value v1.Time) *MaintenanceWindowSpecApplyConfiguration {
	b.To = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *MaintenanceWindowSpecApplyConfiguration) WithReason(value string) *MaintenanceWindowSpecApplyConfiguration {
	b.Reason = &value
	return b
}

// WithCapacity sets the Capacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Capacity field is set to the value of the last call.
func (b *MaintenanceWindowSpecApplyConfiguration) WithCapacity(value corev1.ResourceList) *MaintenanceWindowSpecApplyConfiguration {
	b.Capacity = &value
	return b
}

// WithTenants adds the given value to the Tenants field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tenants field.
func (b *MaintenanceWindowSpecApplyConfiguration) WithTenants(values ...string) *MaintenanceWindowSpecApplyConfiguration {
	for i := range values {
		b.Tenants = append(b.Tenants, values[i])
	}
	return b
}
