/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// OwnedVNIApplyConfiguration represents a declarative configuration of the OwnedVNI type for use
// with apply.
type OwnedVNIApplyConfiguration struct {
	PoolUID         *string `json:"poolUID,omitempty"`
	LeaseGeneration *int64  `json:"leaseGeneration,omitempty"`
	OwnerUID        *string `json:"ownerUID,omitempty"`
	OperationID     *string `json:"operationID,omitempty"`
	Revision        *int64  `json:"revision,omitempty"`
	Generation      *int64  `json:"generation,omitempty"`
	Kind            *string `json:"kind,omitempty"`
	Namespace       *string `json:"namespace,omitempty"`
	Name            *string `json:"name,omitempty"`
	UID             *string `json:"uid,omitempty"`
	VNI             *uint   `json:"vni,omitempty"`
}

// OwnedVNIApplyConfiguration constructs a declarative configuration of the OwnedVNI type for use with
// apply.
func OwnedVNI() *OwnedVNIApplyConfiguration {
	return &OwnedVNIApplyConfiguration{}
}

// WithPoolUID sets the PoolUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PoolUID field is set to the value of the last call.
func (b *OwnedVNIApplyConfiguration) WithPoolUID(value string) *OwnedVNIApplyConfiguration {
	b.PoolUID = &value
	return b
}

// WithLeaseGeneration sets the LeaseGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeaseGeneration field is set to the value of the last call.
func (b *OwnedVNIApplyConfiguration) WithLeaseGeneration(value int64) *OwnedVNIApplyConfiguration {
	b.LeaseGeneration = &value
	return b
}

// WithOwnerUID sets the OwnerUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OwnerUID field is set to the value of the last call.
func (b *OwnedVNIApplyConfiguration) WithOwnerUID(value string) *OwnedVNIApplyConfiguration {
	b.OwnerUID = &value
	return b
}

// WithOperationID sets the OperationID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OperationID field is set to the value of the last call.
func (b *OwnedVNIApplyConfiguration) WithOperationID(value string) *OwnedVNIApplyConfiguration {
	b.OperationID = &value
	return b
}

// WithRevision sets the Revision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Revision field is set to the value of the last call.
func (b *OwnedVNIApplyConfiguration) WithRevision(value int64) *OwnedVNIApplyConfiguration {
	b.Revision = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *OwnedVNIApplyConfiguration) WithGeneration(value int64) *OwnedVNIApplyConfiguration {
	b.Generation = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *OwnedVNIApplyConfiguration) WithKind(value string) *OwnedVNIApplyConfiguration {
	b.Kind = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *OwnedVNIApplyConfiguration) WithNamespace(value string) *OwnedVNIApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *OwnedVNIApplyConfiguration) WithName(value string) *OwnedVNIApplyConfiguration {
	b.Name = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *OwnedVNIApplyConfiguration) WithUID(value string) *OwnedVNIApplyConfiguration {
	b.UID = &value
	return b
}

// WithVNI sets the VNI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VNI field is set to the value of the last call.
func (b *OwnedVNIApplyConfiguration) WithVNI(value uint) *OwnedVNIApplyConfiguration {
	b.VNI = &value
	return b
}
