/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// OwnedRuntimeReportApplyConfiguration represents a declarative configuration of the OwnedRuntimeReport type for use
// with apply.
//
// OwnedRuntimeReport is node-owned; identity is immutable controller inventory.
// Independent timestamps never impose a cross-owner clock ordering.
type OwnedRuntimeReportApplyConfiguration struct {
	Identity            *OwnedRuntimeIdentityApplyConfiguration `json:"identity,omitempty"`
	RuntimeState        *string                                 `json:"runtimeState,omitempty"`
	RuntimeAbsentAt     *v1.Time                                `json:"runtimeAbsentAt,omitempty"`
	CgroupAbsentAt      *v1.Time                                `json:"cgroupAbsentAt,omitempty"`
	AttachmentsAbsentAt *v1.Time                                `json:"attachmentsAbsentAt,omitempty"`
	ObservedAt          *v1.Time                                `json:"observedAt,omitempty"`
	Error               *string                                 `json:"error,omitempty"`
}

// OwnedRuntimeReportApplyConfiguration constructs a declarative configuration of the OwnedRuntimeReport type for use with
// apply.
func OwnedRuntimeReport() *OwnedRuntimeReportApplyConfiguration {
	return &OwnedRuntimeReportApplyConfiguration{}
}

// WithIdentity sets the Identity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Identity field is set to the value of the last call.
func (b *OwnedRuntimeReportApplyConfiguration) WithIdentity(value *OwnedRuntimeIdentityApplyConfiguration) *OwnedRuntimeReportApplyConfiguration {
	b.Identity = value
	return b
}

// WithRuntimeState sets the RuntimeState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RuntimeState field is set to the value of the last call.
func (b *OwnedRuntimeReportApplyConfiguration) WithRuntimeState(value string) *OwnedRuntimeReportApplyConfiguration {
	b.RuntimeState = &value
	return b
}

// WithRuntimeAbsentAt sets the RuntimeAbsentAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RuntimeAbsentAt field is set to the value of the last call.
func (b *OwnedRuntimeReportApplyConfiguration) WithRuntimeAbsentAt(value v1.Time) *OwnedRuntimeReportApplyConfiguration {
	b.RuntimeAbsentAt = &value
	return b
}

// WithCgroupAbsentAt sets the CgroupAbsentAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CgroupAbsentAt field is set to the value of the last call.
func (b *OwnedRuntimeReportApplyConfiguration) WithCgroupAbsentAt(value v1.Time) *OwnedRuntimeReportApplyConfiguration {
	b.CgroupAbsentAt = &value
	return b
}

// WithAttachmentsAbsentAt sets the AttachmentsAbsentAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AttachmentsAbsentAt field is set to the value of the last call.
func (b *OwnedRuntimeReportApplyConfiguration) WithAttachmentsAbsentAt(value v1.Time) *OwnedRuntimeReportApplyConfiguration {
	b.AttachmentsAbsentAt = &value
	return b
}

// WithObservedAt sets the ObservedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedAt field is set to the value of the last call.
func (b *OwnedRuntimeReportApplyConfiguration) WithObservedAt(value v1.Time) *OwnedRuntimeReportApplyConfiguration {
	b.ObservedAt = &value
	return b
}

// WithError sets the Error field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Error field is set to the value of the last call.
func (b *OwnedRuntimeReportApplyConfiguration) WithError(value string) *OwnedRuntimeReportApplyConfiguration {
	b.Error = &value
	return b
}
