/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PodFailureApplyConfiguration represents a declarative configuration of the PodFailure type for use
// with apply.
//
// PodFailure is the warning of a pod that did not start.
type PodFailureApplyConfiguration struct {
	// Reason is one of the Failure* constants.
	Reason *string `json:"reason,omitempty"`
	// Message is the last error the node reported (for example the image pull error).
	Message      *string  `json:"message,omitempty"`
	RestartCount *int32   `json:"restartCount,omitempty"`
	At           *v1.Time `json:"at,omitempty"`
}

// PodFailureApplyConfiguration constructs a declarative configuration of the PodFailure type for use with
// apply.
func PodFailure() *PodFailureApplyConfiguration {
	return &PodFailureApplyConfiguration{}
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *PodFailureApplyConfiguration) WithReason(value string) *PodFailureApplyConfiguration {
	b.Reason = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *PodFailureApplyConfiguration) WithMessage(value string) *PodFailureApplyConfiguration {
	b.Message = &value
	return b
}

// WithRestartCount sets the RestartCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestartCount field is set to the value of the last call.
func (b *PodFailureApplyConfiguration) WithRestartCount(value int32) *PodFailureApplyConfiguration {
	b.RestartCount = &value
	return b
}

// WithAt sets the At field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the At field is set to the value of the last call.
func (b *PodFailureApplyConfiguration) WithAt(value v1.Time) *PodFailureApplyConfiguration {
	b.At = &value
	return b
}
