/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	laboratoryv1alpha1 "github.com/cybericebox/laboratory/api/laboratory/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PodScheduleApplyConfiguration represents a declarative configuration of the PodSchedule type for use
// with apply.
//
// PodSchedule is the scheduling state of one pod: a Device, or the VPN or
// gateway pod of a LabGroup. The scheduler owns it.
type PodScheduleApplyConfiguration struct {
	State *laboratoryv1alpha1.PodScheduleState `json:"state,omitempty"`
	// QueuedAt is when the pod entered the queue.
	QueuedAt *v1.Time `json:"queuedAt,omitempty"`
	// DispatchedAt is when the scheduler let the pod start; the startup timeout counts from it.
	DispatchedAt *v1.Time `json:"dispatchedAt,omitempty"`
	// StartedAt is when the pod was first seen Ready.
	StartedAt *v1.Time `json:"startedAt,omitempty"`
	// Failure explains a Failed pod; the warning clears when the pod becomes Ready.
	Failure *PodFailureApplyConfiguration `json:"failure,omitempty"`
}

// PodScheduleApplyConfiguration constructs a declarative configuration of the PodSchedule type for use with
// apply.
func PodSchedule() *PodScheduleApplyConfiguration {
	return &PodScheduleApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *PodScheduleApplyConfiguration) WithState(value laboratoryv1alpha1.PodScheduleState) *PodScheduleApplyConfiguration {
	b.State = &value
	return b
}

// WithQueuedAt sets the QueuedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QueuedAt field is set to the value of the last call.
func (b *PodScheduleApplyConfiguration) WithQueuedAt(value v1.Time) *PodScheduleApplyConfiguration {
	b.QueuedAt = &value
	return b
}

// WithDispatchedAt sets the DispatchedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DispatchedAt field is set to the value of the last call.
func (b *PodScheduleApplyConfiguration) WithDispatchedAt(value v1.Time) *PodScheduleApplyConfiguration {
	b.DispatchedAt = &value
	return b
}

// WithStartedAt sets the StartedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartedAt field is set to the value of the last call.
func (b *PodScheduleApplyConfiguration) WithStartedAt(value v1.Time) *PodScheduleApplyConfiguration {
	b.StartedAt = &value
	return b
}

// WithFailure sets the Failure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Failure field is set to the value of the last call.
func (b *PodScheduleApplyConfiguration) WithFailure(value *PodFailureApplyConfiguration) *PodScheduleApplyConfiguration {
	b.Failure = value
	return b
}
