/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RetirementObjectIdentityApplyConfiguration represents a declarative configuration of the RetirementObjectIdentity type for use
// with apply.
//
// RetirementObjectIdentity is an exact pre-cleanup object receipt, never data.
type RetirementObjectIdentityApplyConfiguration struct {
	GroupNamespaceOwned *bool   `json:"groupNamespaceOwned,omitempty"`
	Kind                *string `json:"kind,omitempty"`
	Name                *string `json:"name,omitempty"`
	UID                 *string `json:"uid,omitempty"`
	OwnerUID            *string `json:"ownerUID,omitempty"`
}

// RetirementObjectIdentityApplyConfiguration constructs a declarative configuration of the RetirementObjectIdentity type for use with
// apply.
func RetirementObjectIdentity() *RetirementObjectIdentityApplyConfiguration {
	return &RetirementObjectIdentityApplyConfiguration{}
}

// WithGroupNamespaceOwned sets the GroupNamespaceOwned field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupNamespaceOwned field is set to the value of the last call.
func (b *RetirementObjectIdentityApplyConfiguration) WithGroupNamespaceOwned(value bool) *RetirementObjectIdentityApplyConfiguration {
	b.GroupNamespaceOwned = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *RetirementObjectIdentityApplyConfiguration) WithKind(value string) *RetirementObjectIdentityApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RetirementObjectIdentityApplyConfiguration) WithName(value string) *RetirementObjectIdentityApplyConfiguration {
	b.Name = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *RetirementObjectIdentityApplyConfiguration) WithUID(value string) *RetirementObjectIdentityApplyConfiguration {
	b.UID = &value
	return b
}

// WithOwnerUID sets the OwnerUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OwnerUID field is set to the value of the last call.
func (b *RetirementObjectIdentityApplyConfiguration) WithOwnerUID(value string) *RetirementObjectIdentityApplyConfiguration {
	b.OwnerUID = &value
	return b
}
