/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SchedulingStatusApplyConfiguration represents a declarative configuration of the SchedulingStatus type for use
// with apply.
//
// SchedulingStatus is the place of a Lab or LabGroup in the scheduler queue.
// The scheduler refreshes it at a limited rate, so Position can lag by seconds.
type SchedulingStatusApplyConfiguration struct {
	// Group is the deploy group of the object; empty for an independent one.
	Group *string `json:"group,omitempty"`
	// Position is the 1-based place among the objects that still have pods to
	// dispatch; 0 when all pods are dispatched.
	Position *int32 `json:"position,omitempty"`
	// Length is the number of such objects when Position was written.
	Length *int32 `json:"length,omitempty"`
	// Reason is why the next pod of the object is not dispatched (Wait* constants).
	Reason *string `json:"reason,omitempty"`
	// Message adds detail, for example "waiting for group intro".
	Message *string `json:"message,omitempty"`
	// Pods is the number of pods of the object and Pending how many of them are
	// not dispatched yet.
	Pods    *int32 `json:"pods,omitempty"`
	Pending *int32 `json:"pending,omitempty"`
}

// SchedulingStatusApplyConfiguration constructs a declarative configuration of the SchedulingStatus type for use with
// apply.
func SchedulingStatus() *SchedulingStatusApplyConfiguration {
	return &SchedulingStatusApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *SchedulingStatusApplyConfiguration) WithGroup(value string) *SchedulingStatusApplyConfiguration {
	b.Group = &value
	return b
}

// WithPosition sets the Position field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Position field is set to the value of the last call.
func (b *SchedulingStatusApplyConfiguration) WithPosition(value int32) *SchedulingStatusApplyConfiguration {
	b.Position = &value
	return b
}

// WithLength sets the Length field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Length field is set to the value of the last call.
func (b *SchedulingStatusApplyConfiguration) WithLength(value int32) *SchedulingStatusApplyConfiguration {
	b.Length = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *SchedulingStatusApplyConfiguration) WithReason(value string) *SchedulingStatusApplyConfiguration {
	b.Reason = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *SchedulingStatusApplyConfiguration) WithMessage(value string) *SchedulingStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithPods sets the Pods field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pods field is set to the value of the last call.
func (b *SchedulingStatusApplyConfiguration) WithPods(value int32) *SchedulingStatusApplyConfiguration {
	b.Pods = &value
	return b
}

// WithPending sets the Pending field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pending field is set to the value of the last call.
func (b *SchedulingStatusApplyConfiguration) WithPending(value int32) *SchedulingStatusApplyConfiguration {
	b.Pending = &value
	return b
}
