/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TenantPersistenceApplyConfiguration represents a declarative configuration of the TenantPersistence type for use
// with apply.
//
// TenantPersistence is the persistence policy of a tenant. The platform switch
// (chart devices.statePersistence) allows the mechanism at all, and its values are
// the ceilings of the limits below.
type TenantPersistenceApplyConfiguration struct {
	// Allowed lets the tenant's topologies ask for persistence (devices[].persistence.enabled).
	// It has no effect while the platform does not allow persistence.
	Allowed *bool `json:"allowed,omitempty"`
	// WriteQuota is the most of a participant's writes kept per device (a Kubernetes
	// quantity); capped by the platform's value, which is also the default.
	WriteQuota *string `json:"writeQuota,omitempty"`
	// MaxFileSize: a file larger than this is not snapshotted (a Kubernetes quantity);
	// capped by the platform's value, which is also the default.
	MaxFileSize *string `json:"maxFileSize,omitempty"`
}

// TenantPersistenceApplyConfiguration constructs a declarative configuration of the TenantPersistence type for use with
// apply.
func TenantPersistence() *TenantPersistenceApplyConfiguration {
	return &TenantPersistenceApplyConfiguration{}
}

// WithAllowed sets the Allowed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Allowed field is set to the value of the last call.
func (b *TenantPersistenceApplyConfiguration) WithAllowed(value bool) *TenantPersistenceApplyConfiguration {
	b.Allowed = &value
	return b
}

// WithWriteQuota sets the WriteQuota field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WriteQuota field is set to the value of the last call.
func (b *TenantPersistenceApplyConfiguration) WithWriteQuota(value string) *TenantPersistenceApplyConfiguration {
	b.WriteQuota = &value
	return b
}

// WithMaxFileSize sets the MaxFileSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxFileSize field is set to the value of the last call.
func (b *TenantPersistenceApplyConfiguration) WithMaxFileSize(value string) *TenantPersistenceApplyConfiguration {
	b.MaxFileSize = &value
	return b
}
