/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TenantEnrollmentApplyConfiguration represents a declarative configuration of the TenantEnrollment type for use
// with apply.
//
// TenantEnrollment holds the state of the tenant's enrollment token. Only its hash is
// stored; the token itself is in the Secret tenant-<name>-enrollment of the tenants namespace
// until it is used or replaced.
type TenantEnrollmentApplyConfiguration struct {
	// TokenHash is the hex SHA-256 of the token.
	TokenHash *string `json:"tokenHash,omitempty"`
	// IssuedAt is when the token was generated.
	IssuedAt *v1.Time `json:"issuedAt,omitempty"`
	// ExpiresAt is when an unused token stops working.
	ExpiresAt *v1.Time `json:"expiresAt,omitempty"`
	// UsedAt is when the token was used to enroll; a used token never works again.
	UsedAt *v1.Time `json:"usedAt,omitempty"`
}

// TenantEnrollmentApplyConfiguration constructs a declarative configuration of the TenantEnrollment type for use with
// apply.
func TenantEnrollment() *TenantEnrollmentApplyConfiguration {
	return &TenantEnrollmentApplyConfiguration{}
}

// WithTokenHash sets the TokenHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TokenHash field is set to the value of the last call.
func (b *TenantEnrollmentApplyConfiguration) WithTokenHash(value string) *TenantEnrollmentApplyConfiguration {
	b.TokenHash = &value
	return b
}

// WithIssuedAt sets the IssuedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IssuedAt field is set to the value of the last call.
func (b *TenantEnrollmentApplyConfiguration) WithIssuedAt(value v1.Time) *TenantEnrollmentApplyConfiguration {
	b.IssuedAt = &value
	return b
}

// WithExpiresAt sets the ExpiresAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpiresAt field is set to the value of the last call.
func (b *TenantEnrollmentApplyConfiguration) WithExpiresAt(value v1.Time) *TenantEnrollmentApplyConfiguration {
	b.ExpiresAt = &value
	return b
}

// WithUsedAt sets the UsedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UsedAt field is set to the value of the last call.
func (b *TenantEnrollmentApplyConfiguration) WithUsedAt(value v1.Time) *TenantEnrollmentApplyConfiguration {
	b.UsedAt = &value
	return b
}
