/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TenantSpecApplyConfiguration represents a declarative configuration of the TenantSpec type for use
// with apply.
//
// TenantSpec is the policy of one tenant of the management agent. The tenant is
// identified by the Tenant's name: the client certificate issued for it carries
// CN = name, and the agent resolves the caller's tenant by that CN.
type TenantSpecApplyConfiguration struct {
	// Persistence is what the tenant may do with device state persistence.
	Persistence *TenantPersistenceApplyConfiguration `json:"persistence,omitempty"`
	// ReceivesLabErrors lets the agent send this tenant the laboratory's own errors (operator, node-agent, proxy, demux, VPN and
	// gateway pods) in MonitoringUpdate.errors. They are platform-wide and carry no tenant data, but a tenant that is only a customer
	// of the cluster has no business with them: set it for the platform's own backend only. A tenant's failed lab deploys are always
	// sent, whatever this says.
	ReceivesLabErrors *bool `json:"receivesLabErrors,omitempty"`
	// Quota caps the CPU and memory requests of the tenant's running pods.
	// Absent: no limit.
	Quota *TenantQuotaApplyConfiguration `json:"quota,omitempty"`
	// Images is the tenant's image policy and registry credentials.
	Images *TenantImagesApplyConfiguration `json:"images,omitempty"`
}

// TenantSpecApplyConfiguration constructs a declarative configuration of the TenantSpec type for use with
// apply.
func TenantSpec() *TenantSpecApplyConfiguration {
	return &TenantSpecApplyConfiguration{}
}

// WithPersistence sets the Persistence field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Persistence field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithPersistence(value *TenantPersistenceApplyConfiguration) *TenantSpecApplyConfiguration {
	b.Persistence = value
	return b
}

// WithReceivesLabErrors sets the ReceivesLabErrors field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReceivesLabErrors field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithReceivesLabErrors(value bool) *TenantSpecApplyConfiguration {
	b.ReceivesLabErrors = &value
	return b
}

// WithQuota sets the Quota field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Quota field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithQuota(value *TenantQuotaApplyConfiguration) *TenantSpecApplyConfiguration {
	b.Quota = value
	return b
}

// WithImages sets the Images field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Images field is set to the value of the last call.
func (b *TenantSpecApplyConfiguration) WithImages(value *TenantImagesApplyConfiguration) *TenantSpecApplyConfiguration {
	b.Images = value
	return b
}
