/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TenantQuotaApplyConfiguration represents a declarative configuration of the TenantQuota type for use
// with apply.
//
// TenantQuota caps the sum of the CPU and memory requests of the tenant's dispatched
// pods. Each limit is an absolute quantity ("32", "500Gi") or a percentage of what
// the nodes lab pods can run on allocate ("50%"). Absent: no limit.
type TenantQuotaApplyConfiguration struct {
	CPU    *string `json:"cpu,omitempty"`
	Memory *string `json:"memory,omitempty"`
}

// TenantQuotaApplyConfiguration constructs a declarative configuration of the TenantQuota type for use with
// apply.
func TenantQuota() *TenantQuotaApplyConfiguration {
	return &TenantQuotaApplyConfiguration{}
}

// WithCPU sets the CPU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CPU field is set to the value of the last call.
func (b *TenantQuotaApplyConfiguration) WithCPU(value string) *TenantQuotaApplyConfiguration {
	b.CPU = &value
	return b
}

// WithMemory sets the Memory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Memory field is set to the value of the last call.
func (b *TenantQuotaApplyConfiguration) WithMemory(value string) *TenantQuotaApplyConfiguration {
	b.Memory = &value
	return b
}
