/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VPNBootRecordApplyConfiguration represents a declarative configuration of the VPNBootRecord type for use
// with apply.
//
// VPNBootRecord is the independent startup witness, including idle groups with
// no per-Lab VPN legs. It is separate from policy and traffic acknowledgements.
type VPNBootRecordApplyConfiguration struct {
	VPNRuntimeIdentityApplyConfiguration `json:""`
	GroupUID                             *string  `json:"groupUID,omitempty"`
	PublishedAt                          *v1.Time `json:"publishedAt,omitempty"`
}

// VPNBootRecordApplyConfiguration constructs a declarative configuration of the VPNBootRecord type for use with
// apply.
func VPNBootRecord() *VPNBootRecordApplyConfiguration {
	return &VPNBootRecordApplyConfiguration{}
}

// WithBootID sets the BootID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootID field is set to the value of the last call.
func (b *VPNBootRecordApplyConfiguration) WithBootID(value string) *VPNBootRecordApplyConfiguration {
	b.VPNRuntimeIdentityApplyConfiguration.BootID = &value
	return b
}

// WithPodName sets the PodName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodName field is set to the value of the last call.
func (b *VPNBootRecordApplyConfiguration) WithPodName(value string) *VPNBootRecordApplyConfiguration {
	b.VPNRuntimeIdentityApplyConfiguration.PodName = &value
	return b
}

// WithPodUID sets the PodUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodUID field is set to the value of the last call.
func (b *VPNBootRecordApplyConfiguration) WithPodUID(value string) *VPNBootRecordApplyConfiguration {
	b.VPNRuntimeIdentityApplyConfiguration.PodUID = &value
	return b
}

// WithContainerID sets the ContainerID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerID field is set to the value of the last call.
func (b *VPNBootRecordApplyConfiguration) WithContainerID(value string) *VPNBootRecordApplyConfiguration {
	b.VPNRuntimeIdentityApplyConfiguration.ContainerID = &value
	return b
}

// WithRestartCount sets the RestartCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestartCount field is set to the value of the last call.
func (b *VPNBootRecordApplyConfiguration) WithRestartCount(value int32) *VPNBootRecordApplyConfiguration {
	b.VPNRuntimeIdentityApplyConfiguration.RestartCount = &value
	return b
}

// WithGroupUID sets the GroupUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupUID field is set to the value of the last call.
func (b *VPNBootRecordApplyConfiguration) WithGroupUID(value string) *VPNBootRecordApplyConfiguration {
	b.GroupUID = &value
	return b
}

// WithPublishedAt sets the PublishedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublishedAt field is set to the value of the last call.
func (b *VPNBootRecordApplyConfiguration) WithPublishedAt(value v1.Time) *VPNBootRecordApplyConfiguration {
	b.PublishedAt = &value
	return b
}
