/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// VPNRuntimeIdentityApplyConfiguration represents a declarative configuration of the VPNRuntimeIdentity type for use
// with apply.
//
// VPNRuntimeIdentity binds an acknowledgement to one process boot and native
// container identity. Empty identities cannot certify a current access fence.
type VPNRuntimeIdentityApplyConfiguration struct {
	BootID       *string `json:"bootId,omitempty"`
	PodName      *string `json:"podName,omitempty"`
	PodUID       *string `json:"podUID,omitempty"`
	ContainerID  *string `json:"containerID,omitempty"`
	RestartCount *int32  `json:"restartCount,omitempty"`
}

// VPNRuntimeIdentityApplyConfiguration constructs a declarative configuration of the VPNRuntimeIdentity type for use with
// apply.
func VPNRuntimeIdentity() *VPNRuntimeIdentityApplyConfiguration {
	return &VPNRuntimeIdentityApplyConfiguration{}
}

// WithBootID sets the BootID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootID field is set to the value of the last call.
func (b *VPNRuntimeIdentityApplyConfiguration) WithBootID(value string) *VPNRuntimeIdentityApplyConfiguration {
	b.BootID = &value
	return b
}

// WithPodName sets the PodName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodName field is set to the value of the last call.
func (b *VPNRuntimeIdentityApplyConfiguration) WithPodName(value string) *VPNRuntimeIdentityApplyConfiguration {
	b.PodName = &value
	return b
}

// WithPodUID sets the PodUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodUID field is set to the value of the last call.
func (b *VPNRuntimeIdentityApplyConfiguration) WithPodUID(value string) *VPNRuntimeIdentityApplyConfiguration {
	b.PodUID = &value
	return b
}

// WithContainerID sets the ContainerID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerID field is set to the value of the last call.
func (b *VPNRuntimeIdentityApplyConfiguration) WithContainerID(value string) *VPNRuntimeIdentityApplyConfiguration {
	b.ContainerID = &value
	return b
}

// WithRestartCount sets the RestartCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestartCount field is set to the value of the last call.
func (b *VPNRuntimeIdentityApplyConfiguration) WithRestartCount(value int32) *VPNRuntimeIdentityApplyConfiguration {
	b.RestartCount = &value
	return b
}
