{{- if .Values.gateway.enabled }}
{{- $annotations := dict }}
{{- if and .Values.proxy.enabled .Values.proxy.wg.enabled .Values.proxy.service.sharedLBKey }}
{{- $_ := set $annotations "lbipam.cilium.io/sharing-key" .Values.proxy.service.sharedLBKey }}
{{- $_ := set $annotations "lbipam.cilium.io/sharing-cross-namespace" "laboratory-proxy" }}
{{- end }}
{{- $annotations = mergeOverwrite $annotations .Values.gateway.annotations }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: laboratory-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laboratory.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  infrastructure:
    annotations:
      io.cilium/lb-ipam-sharing-key: {{ .Values.proxy.sharingKey | quote }}
  listeners:
  - name: tls-passthrough
    protocol: TLS
    port: 443
    tls:
      mode: Passthrough
    allowedRoutes:
      namespaces:
        from: All
{{- end }}
