{{- if and .Values.gateway.enabled .Values.gateway.agentDomain }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: laboratory-agent
  namespace: {{ .Values.gateway.agentNamespace }}
  labels:
    {{- include "laboratory.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: laboratory-gateway
    namespace: {{ .Release.Namespace }}
  hostnames:
  - {{ .Values.gateway.agentDomain | quote }}
  rules:
  - backendRefs:
    - name: {{ .Values.gateway.agentService }}
      port: 443
{{- end }}
