{{- if and .Values.gateway.enabled .Values.proxy.enabled .Values.proxy.l7.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: laboratory-lab
  namespace: laboratory-proxy
  labels:
    {{- include "laboratory.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: laboratory-gateway
    namespace: {{ .Release.Namespace }}
  hostnames:
  - "*.{{ .Values.operator.baseDomain }}"
  rules:
  - backendRefs:
    - name: laboratory-proxy-l7
      port: 443
{{- end }}
