/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	laboratoryv1alpha1 "github.com/cybericebox/laboratory/api/laboratory/v1alpha1"
	applyconfigurationlaboratoryv1alpha1 "github.com/cybericebox/laboratory/clientset/applyconfiguration/laboratory/v1alpha1"
	scheme "github.com/cybericebox/laboratory/clientset/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DevicesGetter has a method to return a DeviceInterface.
// A group's client should implement this interface.
type DevicesGetter interface {
	Devices(namespace string) DeviceInterface
}

// DeviceInterface has methods to work with Device resources.
type DeviceInterface interface {
	Create(ctx context.Context, device *laboratoryv1alpha1.Device, opts v1.CreateOptions) (*laboratoryv1alpha1.Device, error)
	Update(ctx context.Context, device *laboratoryv1alpha1.Device, opts v1.UpdateOptions) (*laboratoryv1alpha1.Device, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, device *laboratoryv1alpha1.Device, opts v1.UpdateOptions) (*laboratoryv1alpha1.Device, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*laboratoryv1alpha1.Device, error)
	List(ctx context.Context, opts v1.ListOptions) (*laboratoryv1alpha1.DeviceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *laboratoryv1alpha1.Device, err error)
	Apply(ctx context.Context, device *applyconfigurationlaboratoryv1alpha1.DeviceApplyConfiguration, opts v1.ApplyOptions) (result *laboratoryv1alpha1.Device, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, device *applyconfigurationlaboratoryv1alpha1.DeviceApplyConfiguration, opts v1.ApplyOptions) (result *laboratoryv1alpha1.Device, err error)
	DeviceExpansion
}

// devices implements DeviceInterface
type devices struct {
	*gentype.ClientWithListAndApply[*laboratoryv1alpha1.Device, *laboratoryv1alpha1.DeviceList, *applyconfigurationlaboratoryv1alpha1.DeviceApplyConfiguration]
}

// newDevices returns a Devices
func newDevices(c *LaboratoryV1alpha1Client, namespace string) *devices {
	return &devices{
		gentype.NewClientWithListAndApply[*laboratoryv1alpha1.Device, *laboratoryv1alpha1.DeviceList, *applyconfigurationlaboratoryv1alpha1.DeviceApplyConfiguration](
			"devices",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *laboratoryv1alpha1.Device { return &laboratoryv1alpha1.Device{} },
			func() *laboratoryv1alpha1.DeviceList { return &laboratoryv1alpha1.DeviceList{} },
			gentype.PrefersProtobuf[*laboratoryv1alpha1.Device](),
		),
	}
}
