/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	laboratoryv1alpha1 "github.com/cybericebox/laboratory/api/laboratory/v1alpha1"
	applyconfigurationlaboratoryv1alpha1 "github.com/cybericebox/laboratory/clientset/applyconfiguration/laboratory/v1alpha1"
	scheme "github.com/cybericebox/laboratory/clientset/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// LabGroupClientsGetter has a method to return a LabGroupClientInterface.
// A group's client should implement this interface.
type LabGroupClientsGetter interface {
	LabGroupClients(namespace string) LabGroupClientInterface
}

// LabGroupClientInterface has methods to work with LabGroupClient resources.
type LabGroupClientInterface interface {
	Create(ctx context.Context, labGroupClient *laboratoryv1alpha1.LabGroupClient, opts v1.CreateOptions) (*laboratoryv1alpha1.LabGroupClient, error)
	Update(ctx context.Context, labGroupClient *laboratoryv1alpha1.LabGroupClient, opts v1.UpdateOptions) (*laboratoryv1alpha1.LabGroupClient, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, labGroupClient *laboratoryv1alpha1.LabGroupClient, opts v1.UpdateOptions) (*laboratoryv1alpha1.LabGroupClient, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*laboratoryv1alpha1.LabGroupClient, error)
	List(ctx context.Context, opts v1.ListOptions) (*laboratoryv1alpha1.LabGroupClientList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *laboratoryv1alpha1.LabGroupClient, err error)
	Apply(ctx context.Context, labGroupClient *applyconfigurationlaboratoryv1alpha1.LabGroupClientApplyConfiguration, opts v1.ApplyOptions) (result *laboratoryv1alpha1.LabGroupClient, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, labGroupClient *applyconfigurationlaboratoryv1alpha1.LabGroupClientApplyConfiguration, opts v1.ApplyOptions) (result *laboratoryv1alpha1.LabGroupClient, err error)
	LabGroupClientExpansion
}

// labGroupClients implements LabGroupClientInterface
type labGroupClients struct {
	*gentype.ClientWithListAndApply[*laboratoryv1alpha1.LabGroupClient, *laboratoryv1alpha1.LabGroupClientList, *applyconfigurationlaboratoryv1alpha1.LabGroupClientApplyConfiguration]
}

// newLabGroupClients returns a LabGroupClients
func newLabGroupClients(c *LaboratoryV1alpha1Client, namespace string) *labGroupClients {
	return &labGroupClients{
		gentype.NewClientWithListAndApply[*laboratoryv1alpha1.LabGroupClient, *laboratoryv1alpha1.LabGroupClientList, *applyconfigurationlaboratoryv1alpha1.LabGroupClientApplyConfiguration](
			"labgroupclients",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *laboratoryv1alpha1.LabGroupClient { return &laboratoryv1alpha1.LabGroupClient{} },
			func() *laboratoryv1alpha1.LabGroupClientList { return &laboratoryv1alpha1.LabGroupClientList{} },
			gentype.PrefersProtobuf[*laboratoryv1alpha1.LabGroupClient](),
		),
	}
}
